### ISSUE TITLE
ES6 From `node_modules` Not Transformed Properly

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#114]
# Bug Report

ES6 code from node_modules leaks into the dist .js files as it's getting ignored by the transformers.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Version 0.9.2

## Description

When You create a build that imports dependencies from node_modules, which are written in es6, for example with template strings, then these will not be converted to es5 compatible js.
This is an issue if you need to support IE 11.

## Steps to Reproduce

1. Create a shell application, build it
2. check the resulting .js file for template strings.. you'll find some.

## Expected behavior

No ES6 in the dist files.

## Actual behavior

Template strings found in the dist files.

## Possible Origin / Solution

This is actually a parcel issue: https://github.com/parcel-bundler/parcel/issues/2013
But it seems to be ignored.

**Comment by FlorianRappl** [comment]
Thanks for the report. We'll take care of it.

Potentially we'll go for a simple solution to just (for builds only, i.e., no debugging) apply a post-build action to transform all created bundles according to the `.browserlist` setting. Not sure yet how to generalize, but we'll figure something out!

:beers:

**Comment by FlorianRappl** [comment]
Landed in preview and `develop`.
