### ISSUE TITLE
Large Bundles Run Out Of Memory

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#121]
## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Piral v0.9.3 or v0.10 preview. Linux (Ubuntu, but potentially other distros / MacOSX / Windows, too)

## Description

We have a larger Piral instance that resulted in ~3 MB bundle. The bundle size is a problem itself, but that has nothing to do with Piral. Note, however, that even splitting up the bundle in smaller chunks did not provide a solution (and would be independent of the bug report anyway) to this particular problem.

## Steps to Reproduce

1. Create a new Piral instance
2. Add a couple of large dependencies (increasing the total bundle size to > 3 MB)
3. Perform `piral build`

## Expected behavior

The build is performed as expected and the resulting bundle can be used.

## Actual behavior

In the post-transform phase of the build the build is crashing with an out-of-memory exception (i.e., in Node.js already).

## Possible Origin / Solution

This is actually a babel issue. See https://github.com/babel/minify/issues/332 for more details.

Nevertheless, what is striking is two things here:

1. It worked beforehand (granted, the post-transform introduced by #114 was solved by it)
2. There is no option to deactivate the post-transform

While increasing the JS memory is always possible on user-side it should not be necessary. Right now I see the following ways for solving this issue:

1. Provide an option to disable the post-transform
2. Change the post-transform to not minify in the same sweep (i.e., only use babel for the ES6->ES5, but not for minification); instead use terser for minify
3. Not to have a post-transform and instead to treat *all* packages in *node_modules* as-if they would have been specified using `source`

Each has pros and cons. Solving this issue will potentially be done by (1) and (2), since (3) may be the most complicated and in terms of compile-time (and others) have the most side-effects / unwanted consequences.

**Comment by kpyfan** [comment]
@FlorianRappl might be worth looking into tree shaking as well. https://parceljs.org/cli.html#enable-experimental-scope-hoisting/tree-shaking-support can potentially help eliminate a lot of the unnecessarily loaded modules.

**Comment by FlorianRappl** [comment]
> Tested this locally and it dropped our bundle sizes a fair amount and also eliminated the out of memory issue. Should be a usable workaround for folks for now.

Sounds great! Keep in mind that the issue is about when the bundle size cannot be reduced any more. I already got a working solution - it will be in the next preview release for further testing.

Another remark from my side: In Parcel they scope hoisting is marked experimental and also deactivated by default. We just follow the same approach. If activating it works for you - awesome!

In case of any difficulties just open an issue here; we will always try to improve Parcel (other directly or indirectly).

**Comment by FlorianRappl** [comment]
Hi @SantoJambit would you be so kind to check if the `piral-cli@next` solves the out-of-memory problem (without any regression regarding the emitted bundle, i.e., still properly transpiled to be IE11 compatible) for you? Much appreciated!

**Comment by SantoJambit** [comment]
Hi @FlorianRappl
The out-of-memory bug is gone, and there seems to be no backticks left in the code.

But when I try to serve the dist/release folder statically, I get this error in firefox: `ReferenceError: regeneratorRuntime is not defined`. I have not tried IE yet, seems pointless when even firefox fails.

**Comment by SantoJambit** [comment]
I got the issue fixed by importing regenerator-runtime manually. I can't say much more about IE11 support, since our development setup is currently broken due infrastructure changes in progress.

**Comment by FlorianRappl** [comment]
> But when I try to serve the dist/release folder statically, I get this error in firefox: ReferenceError: regeneratorRuntime is not defined. I have not tried IE yet, seems pointless when even firefox fails.

I guess beforehand `async`/`await` has not been transpiled. Usually, this either goes against an implicit gen. with TS (or `tslib`) or with JS against the regenerator runtime, which could be included, e.g., via the `babel-polyfills`. This is not done automatically.

See: https://github.com/parcel-bundler/parcel/issues/871

We could try to automatically recognize and patch this. I would, however, not try to bring this in 0.10 directly (unless we figure out a nice way to do this). Maybe a post bundle validation / warning could work, too.

Regarding the issue. I would then close it - its in `develop` and ready with 0.10.

**Comment by FlorianRappl** [comment]
> I got the issue fixed by importing regenerator-runtime manually. I can't say much more about IE11 support, since our development setup is currently broken due infrastructure changes in progress.

Awesome - let me know if IE11 works (should be incl. with the default preset).

**Comment by SantoJambit** [comment]
In IE11, I get the following error: `Incompatible receiver, Symbol required`. It seems this happens when core-js gets transpiled:
https://github.com/zloirock/core-js/issues/514

Any way to avoid core-js getting transpiled?

**Comment by FlorianRappl** [comment]
> Any way to avoid core-js getting transpiled?

Right now not, but I think we can introduce something. But I would love to double check this beforehand.

In your app shell find the `piral-cli` in `node_modules`. Find the `lib/common/bundler.js` file and go to the following function: `function patch(staticPath: string)`.

In there you'll see an iteration over all the `folderNames`. If the `folderName` is `core-js` just return (i.e., skip this one).

Please let me know if that would be helpful - we will then have a default list of exclusions and we will also introduce exclusions to be defined by the app shell author.

**Comment by SantoJambit** [comment]
So, at first it did not work, but when I inspected the code, I found that the original node_modules files where being modified, so I deleted node_modules and tried again.. then it worked.

**Comment by FlorianRappl** [comment]
Yes we patch this to stop Babel / Parcel from using misinformation. Unfortunately, most authors (of libs) don't make the right choice and instead of using the browserlist as thought (what is your code looking like) they make it what the code *should* be compiled to.

The rule from Babel (or Parcel) is, however, to think of browserlist in your app as the *desired state* and in libs as the *current state*. That's why we reset all modules to be "just anything", which means they are all transpiled with your desired state.

Apparently, for *core-js* this does not work - and I expect there may be other packages that behave the same.

Thanks for testing it out!

**Comment by FlorianRappl** [comment]
Implemented. By default, `core-js` is excluded from the patching.

The whole patching can be customized though. Just add a special key `preservedDependencies` in the `package.json`. This should be given as an array, e.g.:

```json
{
  "preservedDependencies": ["core-js", "my-custom-dep"]
}
```
