### ISSUE TITLE
Piral Injector takes precedence over non-script injectors

### ISSUE THREAD

**Issue by kpyfan** [smapiot/piral#122]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Piral 0.9.3

## Description

In Piral 0.9.3 in debug mode, the new Piral Injector takes precedence over all injectors that are not the script injector, causing routes that should be mocked to be grabbed by the instance instead (and show not found).

## Steps to Reproduce

1. Create a new 0.9.* Piral instance using `piral new`
2. Add a `sample.json` to the `src/mocks` directory with some mocked out API calls
3. `piral debug`
4. Navigate to a mocked out API url

## Expected behavior

Content from the mocked out API call is returned based on information in `sample.json`

## Actual behavior

Piral Instance returns not found

## Possible Origin / Solution

New Piral injector in Kras server is taking precedence over JSON injector and all requests are being handled by the Piral injector instead.

Thusfar, a workaround by manually implementing the return in the `backend.js` file that is picked up by the script injector appears to correctly inject the mock route.

```jsx
module.exports = function (_, req, res) {
    if ((req.url == '/api/v1/test') && req.method === 'GET') {
    return res({
      content: JSON.stringify({
          foo: bar
      }),
    })
  }
};
```

**Comment by FlorianRappl** [comment]
Hi @kpyfan would you be so kind to check if the `piral-cli@next` (preview version) solves the problem? Thanks!

**Comment by kpyfan** [comment]
Installed `piral-cli@next` for both the scaffold and the cli of the scaffolded piral instance and can confirm that the issue is now resolved :+1:

Thanks!

**Comment by FlorianRappl** [comment]
Awesome thanks!
