### ISSUE TITLE
sample-piral example does not work on the Edge Browser

### ISSUE THREAD

**Issue by tsukhu** [smapiot/piral#128]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [0.9.3]
- [x] Are you running the latest version? Yes
- [x] Did you perform a search in the issues? Yes

## Environment Details and Version

Piral 0.9.3 , the sample "sample-piral", Edge Browser , Windows 10

## Description

The sample is excellent but it does not load on the Edge Browser 
```
 SCRIPT1028: SCRIPT1028: Expected identifier, string or number
```

## Steps to Reproduce

1. npm run start
2. Open the app on http://localhost:1234/ on the Edge Browser

## Expected behavior

Should work as it does on Chrome

## Actual behavior

The loader is shown and we get the following console error
```
 SCRIPT1028: SCRIPT1028: Expected identifier, string or number
```

## Possible Origin / Solution

I am trying to set up the transform runtime babel plugin , but not sure whats the correct way in piral. Reference : https://github.com/parcel-bundler/parcel/issues/871

**Comment by FlorianRappl** [comment]
Thanks for the report!

A few questions from my side to get a better understanding:
- How have you started the `sample-piral` app shell?
- Did you `git clone` the Piral repo and then `yarn watch:demo-full` or did you create a new pilet using the sample-piral app shell?
- Did you try to use the preview of 0.10?

Thanks!

**Comment by tsukhu** [comment]
Thanks for such a quick response !
1) I took a zip of the entire piral repo and individually ran the sample-piral project (extracted out). I just wanted to take a look at the layout implementation, post running the tutorials.
2) I did the following (on the extracted sample-piral project)
```
npm install
npm run start
```
3) Of course prior to that I have the sample feed service running and modified the piral instance to point to that and it all worked perfectly on Chrome but not on Edge

4) I guess the problem is not specific to the sample as I am facing a similar issue in another sample which I was trying to modify to work with Tailwind CSS. Again working fine on Chrome , but issues on Edge.

**Comment by tsukhu** [comment]
I haven't tried out the v0.10 so far but will do so and let you know

**Comment by FlorianRappl** [comment]
One more question: Which version of the edge browser are you using for this test?

**Comment by tsukhu** [comment]
Microsoft Edge 41.16299.1480.0

![screenshot](https://user-images.githubusercontent.com/846306/72422101-d15fbd00-37a7-11ea-9f92-58dd731ebc9c.PNG)

**Comment by tsukhu** [comment]
Good news!
I just tried out upgrading to the "next" version for piral

```
"dependencies": {
    "bootstrap": "^4.3.1",
    "piral": "next",
    "piral-auth": "next",
    "piral-search": "next",
    "reactstrap": "^8.0.1"
  },
  "devDependencies": {
    "@types/react": "^16.8.2",
    "@types/react-dom": "^16.8.0",
    "@types/react-router": "^5.0.0",
    "@types/react-router-dom": "latest",
    "piral-cli": "next",
    "sass": "^1.17.0"
  },
```

and also standardized on using yarn (instead of npm install) , though that should not cause any issue 

Now it works on Edge

![working](https://user-images.githubusercontent.com/846306/72427001-dd03b180-37b0-11ea-9b3b-ed9cb13aa450.PNG)

**Comment by FlorianRappl** [comment]
Alright, so I would propose to keep the issue open for now.

If we do not release 0.10 until start of next week I would create a 0.9.4 release, which should also fix this. Otherwise, we'll go already for the 0.10.

Would that be fine for you?

**Comment by tsukhu** [comment]
Yes - that should be fine. Thank you!

**Comment by tsukhu** [comment]
@FlorianRappl I have an update on this issue.

Post getting the sample-piral working on Edge browser using "piral debug" , I tried the same approach on the my other piral app instance generated using the CLI (also updated the version of piral) .. but unfortunately still had the issue with the Edge Browser. One thing I realized was for the sample-piral I mistakenly ran "piral build" before running "piral debug" , where as in the other project I had only run "piral debug" (without piral build). 

So I guess the version upgrade may not have been the cause , but doing the following actually made it work
1) yarn install 
2) yarn build
3) yarn debug -> Then it works on Edge Browser

If you skip step #2 then yarn debug causes the Edge Browser issue. 

Hope this helps...

**Comment by FlorianRappl** [comment]
So question is:

- Is this still an issue in v0.10?

Because right now it sounds like this is only an issue in 0.9.3 when you skip this step.

**Comment by tsukhu** [comment]
I think it's an issue in 0.10 as well when you skip the build step. Its something to do with the node modules getting updated differently in the build vs debug. But you only need to run piral build for the first time and then piral debug works fine everytime 

Come to think of it we really need Edge browser support in the final build as most of the developers  will use Chrome..

**Comment by FlorianRappl** [comment]
> Come to think of it we really need Edge browser support in the final build as most of the developers will use Chrome..

The final build is not the problem as we handle the transformation in `piral build`. Originally, there was no support for "legacy" browsers in `debug` anyway. However, since these browsers may have the nastiest bugs its not uncommon to also properly support development there (even though not used on an everyday basis).

So with the introduction of the package patching in 0.10 that was made during `piral build` we also introduced this feature already in `piral debug`, but only if run *after* `piral build`.

Right now I consider this bug being just "inconsistency". What I'll do is to introduce the patching in `debug`, too. However, both - `debug` and `build` will actually use a hash from `.cache` regarding either `yarn.lock` or `package-lock.json` to determine if the `node_modules` should still be patched.

**Comment by FlorianRappl** [comment]
Fix landed in `develop` and seems to work fine so far. The preview version (tagged: `next`) of the Piral CLI includes the fix.
