### ISSUE TITLE
Make missing files fail more obvious

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#129]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Currently, if pilet->files contains files that don't exist, the build process only warns about it in a non-colored way, but since there are a lot of other outputs and the last output line is even green, it seems to suggest that everything is okay. This should imho be colored red and fail hard (i.e. the last visible line shows that an error happened).

## Background

None

## Discussion

None

**Comment by FlorianRappl** [comment]
Is available in the preview (`next`), as well as in the `develop` branch.
