### ISSUE TITLE
Registered "modals" at root pilet is not accessible in other pilets

### ISSUE THREAD

**Issue by lamson** [smapiot/piral#131]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, OS, Browser, ...]
v0.9.7
macOS Mojave (v10.14.4)
Chrome (latest)

## Description

In my application, I would like to register a "default-modal" to be used in my pilets. This "default-modal" is registered by the piral instance for the root pilet.

From my testing, this functionality doesn't work as expected.

## Steps to Reproduce

1. Create a new piral instance
2. Use a reference of the instance to register a modal for root pilet:
```
Instance.root.registerModal("default-modal", DefaultModal");
```

3. Create a pilet given the development piral instance package
4. In the pilet, attempt to make use of the default modal via:
```
app.showModal("default-modal", options);
```

## Expected behavior

A modal will show up.

## Actual behavior

Nothing shows up while piral state did change.

## Possible Origin / Solution

Per convo with @FlorianRappl , the modal `alternative` name wasn't being used.

**Comment by FlorianRappl** [comment]
Will be available in 0.9.8.
