### ISSUE TITLE
During dev-build: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#139]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.10.0

## Description

Error: `Cannot read property 'text' of undefined`

## Steps to Reproduce

1. `piral build --fresh src/index.html`

## Expected behavior

Two things: 
- A successful build
- In case of such an exception, a stack trace might be helpful.

## Actual behavior

Cannot read property 'text' of undefined. There was no stacktrace, so I added some try/catch blocks and found it to be coming from [declaration/index.ts:58](https://github.com/smapiot/piral/blob/986aaf2b3e2977d7b2718defc713d72d9d87bc8d/src/packages/piral-cli/src/declaration/index.ts#L58):
`const moduleName = node.moduleSpecifier.text;`

## Possible Origin / Solution
...

**Comment by FlorianRappl** [comment]
Thanks for the report. We would love to get a MWE / repo on this to release a fix! Much appreciated!

**Comment by FlorianRappl** [comment]
I think the original issue is fixed and shipped with 0.10.1.

New issues (e.g., handling of currently unsupported TS parts) should be discussed and handled in dedicated issues.
