### ISSUE TITLE
SEC7113: CSS was ignored due to mime type mismatch on EDGE Browser for pilets loading own CSS

### ISSUE THREAD

**Issue by tsukhu** [smapiot/piral#144]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Version: 0.10.0
OS: Windows 10.0
Browser : Edge Microsoft Edge 41.16299.1480.0

## Description

Not sure if it is a bug or something I need to do in the pilet , but found that this issue is only coming for Edge browsers (the usual pain point)

## Steps to Reproduce

1. I am using tailwind css in both the shell and the pilets. 
2. The pilets have tailwind css with a prefix of "tr-" added to avoid any clashes. This works fine all browsers except EDGE.
One loading the pilet it does not load the css file resulting in the missing styling on EDGE browser.
```
SEC7113: CSS was ignored due to mime type mismatch
```

## Expected behavior

![CHROME_1](https://user-images.githubusercontent.com/846306/73992595-9c452580-4975-11ea-98a1-78745e2f9a7a.PNG)

## Actual behavior

![EDGE_1](https://user-images.githubusercontent.com/846306/73992601-a23b0680-4975-11ea-9667-4a139bcb7158.PNG)

## Possible Origin / Solution

Not sure , but it could be related to the dynamic css loader not providing the mime type , which is affecting the EDGE browsers

https://stackoverflow.com/questions/47151492/stylesheet-not-loading-because-mime-type-is-text-html

Also sample feed info 
https://feed.piral.io/api/v1/pilet/intermix
https://assets.piral.io/pilets/intermix/transport-pilet/1.0.4/index.js

**Comment by tsukhu** [comment]
This may be something related to how parcel handles postcss .. I'll investigate further if this is actually an issue of how I have written the pilet as well https://parceljs.org/css.html

**Comment by FlorianRappl** [comment]
My investigation shows that the URL for the CSS is wrong.

Here's the URL I get in Chromium-based browsers:
![image](https://user-images.githubusercontent.com/1766191/74012273-24352a80-498a-11ea-98a8-1e96c53b13b4.png)

And here's the URL in Edge pre Chromium:
![image](https://user-images.githubusercontent.com/1766191/74012309-3b741800-498a-11ea-9527-8a6b577f1a85.png)

So somewhere in the Pilet the resolution for the base URL does not work.

I'll investigate!

**Comment by tsukhu** [comment]
@FlorianRappl actually the app in question and link is https://intermix-portal.netlify.com/transport . The warehouse-pilet is not really implemented and is just a placeholder with a menu item added (no css)

**Comment by FlorianRappl** [comment]
> @FlorianRappl actually the app in question and link is https://intermix-portal.netlify.com/transport . The warehouse-pilet is not really implemented and is just a placeholder with a menu item added (no css)

Sorry I just picked one for the image. They all have the same problem. It does not matter which app you choose (and how its implemented).

**Comment by FlorianRappl** [comment]
Alright. Unfortunately, this is a bug in the old Microsoft Edge. This bug will not be fixed as the new Edge based on Chromium does not have this issue.

The bug affects *all* resources included by pilets (i.e., side-bundles, images, stylesheets, ...). We rely on `//# sourceURL` to point the original script to the right direction.

Luckily, we are currently thinking about a new mechanism to include the root pilet. Unfortunately, for the new mechanism we will require a rebuild of the pilet. However, if pilets are not rebuilt, the old mechanism will be used.

More details on that will follow.

**Comment by FlorianRappl** [comment]
Is available in `devel`.
