### ISSUE TITLE
Declaration Generation Mixed `type` and `declare const`

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#146]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Piral 0.10.2, MacOSX, ...

## Description

The generation of custom `ts` information is not always accurate.

For comparison if included in a referenced `exports.ts` the following content

```ts
export type MenuType = 'user' | 'footer';

export interface MenuSettings {
    type: MenuType;
}
```

changes to `declare const MenuType` etc.

## Steps to Reproduce

1. Create new Piral instance
2. Add `exports.ts` with content above
3. Reference `exports.ts` in `package.json` via `typings`

## Expected behavior

The types are pretty much the same.

## Actual behavior

The `type` declaration changes to `declare const`.

## Possible Origin / Solution

Wrong type node.

**Comment by SantoJambit** [comment]
It seems the fix broke something. All constants are being dropped from the exports. See https://github.com/SantoJambit/shell-mwe

**Comment by FlorianRappl** [comment]
It's all fine. The 0.10.3 was not yet for you because the stringify is not yet updated.

0.10.4 will be there for you!

You can, however, already try it out with the right string representation - just use the piral-cli/src/declaration/stringify.ts (or its transpiled version).

**Comment by SantoJambit** [comment]
yep, seems to work
