### ISSUE TITLE
keyof gets expanded into union

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#150]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.10.3

## Description

When exporting a type that uses keyof on an interface gets expanded to a union. This is bad when using declaration merging.

## Steps to Reproduce

1. Perform declaration merging
2. create a type that uses keyof to get the keys of the merged declaration

See https://github.com/SantoJambit/shell-mwe

## Expected behavior

```typescript
export type MergedKeys = keyof Merged;
```

## Actual behavior

```typescript
export type MergedKeys = "A" | "B" | "C" | "D";
```

## Possible Origin / Solution

Possibly related to https://github.com/microsoft/TypeScript/issues/27171

**Comment by SantoJambit** [comment]
Not entirely solved.. When the key type appears in function parameters, it still gets expanded. See the updated MWE.

**Comment by FlorianRappl** [comment]
> Not entirely solved.. When the key type appears in function parameters, it still gets expanded. See the updated MWE.

Please open new issues for such things.

In general the idea of the declaration generation was *not* to take the original, but the one seen from the transpiler when actually transpiled. That being said I understand that a `keyof` should not yet be expanded for your scenario to work correctly.

We'll try to generalize the `keyof` detection.
