### ISSUE TITLE
Piral 0.10.4 sample broken in IE11

### ISSUE THREAD

**Issue by kpyfan** [smapiot/piral#157]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Piral 0.10.4 CLI, IE 11.1246.17134.0 (Windows 10)

## Description

Polyfill not present for `Object.assign` in sample Piral instance created with `piral new`

## Steps to Reproduce

1. `piral new --target piral-test`
2. `piral debug`
3. Navigate to piral instance in IE with console open

## Expected behavior

IE experience is same as other browsers

## Actual behavior

Blank page shown and console errors generated

## Possible Origin / Solution

Adding core-js as a dependency and then having `import 'core-js/stable'` at the top of index.tsx fixes the `Object.assign` issue. However, there's still another issue (that is also present in older versions of piral).

Error is thrown: `SCRIPT5007: Unable to get property 'split' of undefined or null reference (src.f69400ca.js 116,5)`. Error is _NOT_ present in Edge (42.17134.1098.0) (this is still using old EdgeHTML engine, not Chromium).

I've been trying to track this down for the past few days, but haven't had any luck in figuring out _what_ is causing it. The error is unfortunately coming out of the parcel requires at the top and IE doesn't give us a stacktrace here.

**Comment by FlorianRappl** [comment]
Thanks for the report. We will definitely have a look here. If you find anything - let us know!

Any PR / contribution welcome.

**Comment by FlorianRappl** [comment]
I may be on the right track.

- The issue with split comes from the debug mode, where we use `new Error().stack.split(...)`. According to MDN `stack` is supported from IE10 on, however, in our scenario it seems like we would need to catch.

```js
// now
let action = '';

try {
  throw new Error();
} catch (err) {
  action = err.stack.split('\n')[6].replace(/^\s+at\s+Atom\./, '');
}

// instead of
const action = new Error().stack.split('\n')[6].replace(/^\s+at\s+Atom\./, '');
```

- Adding `core-js/stable` certainly helps, not sure yet if we should add it to the `polyfills.ts`; I guess since importing them is optional and since Piral tries to make it easy by default we should just add it there in general
