### ISSUE TITLE
When you reexporting a default import, it disappears from the output.

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#158]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.10.5

## Description

When you reexporting a default import, it disappears from the output.

## Steps to Reproduce

1. Export something as default
2. Import it and export it with a name.

## Expected behavior

It should appear in the index.d.ts

## Actual behavior

It does not appear in the index.d.ts

## Possible Origin / Solution

MWE changelog: https://github.com/SantoJambit/shell-mwe/commit/185110d1e4f8219c8a21fe452d05099123c4baa6

**Comment by FlorianRappl** [comment]
This is intentional. Once you name it the first one disappears. Note that we only support named exports - `default` is only supported if its the *only* (default) export and remains unnamed.

Reason is also simple: Naming conflicts.

**Comment by SantoJambit** [comment]
I think you misunderstood.. I am not exporting default in the final exports.ts. I am exporting a default in a file that I am including in my exports.ts. In there, I give it a new name (an actual name other than "default". There is no naming conflict in this scenario.

**Comment by FlorianRappl** [comment]
Maybe I misunderstood.

So you say that

```
import foo from './foo';

export { foo as bar };
```

disappears (`bar` is not there)?

**Comment by SantoJambit** [comment]
Without the "as bar" part, but yes. foo is not in there.

**Comment by FlorianRappl** [comment]
Alright, gotcha!
