### ISSUE TITLE
Types used in parameters of PiletCoreApi methods missing in generated output.

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#159]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.10.5

## Description

Types used in parameters of PiletCoreApi methods are not being imported into index.d.ts

## Steps to Reproduce

1. Export type declarations

## Expected behavior

Types like `DataStoreOptions` get imported from piral-core etc.

## Actual behavior

They are only referenced, but not imported.

## Possible Origin / Solution

See the output of the generated index.ts from the MWE: https://github.com/SantoJambit/shell-mwe

**Comment by FlorianRappl** [comment]
We'll have a look here.
