### ISSUE TITLE
Ternary Operator in Generics issue

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#161]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.10.5

## Description

While investigating the issues with the exports from deox, I noticed, that ternary operations in generics have an issue. Not sure if this is the only issue that causes deox types to fail, but it is probably a big part.

## Steps to Reproduce

```typescript
export type Ternary<T = undefined> = (T extends undefined ? {} : { ternary: T; });
```

## Expected behavior

```typescript
export type Ternary<T = undefined> = (T extends undefined ? {} : { ternary: T; });
```

## Actual behavior

```typescript
  export type Ternary<T = undefined> = ;
```

## Possible Origin / Solution

The MWE has been adjusted to contain this: https://github.com/SantoJambit/shell-mwe.

Sidenote: I am aware, that this is not a MWE anymore, since it contains a lot of the issues with type declarations. I just wanted to keep it together, so it's easy to check if everything remains stable with the next version. I hope that's okay.

**Comment by FlorianRappl** [comment]
> I just wanted to keep it together, so it's easy to check if everything remains stable with the next version. I hope that's okay.

It's fine.

Right now we do not support type guards in the declaration generation. We will need to see how to support them. Should be in 0.10.6.
