### ISSUE TITLE
Parenthesis of generics ternary expression get dropped.

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#165]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.10.7

## Description

Parenthesis get dropped in generics ternary expressions. Not sure if this actually changes the type, but at the very least it's more readable if the parenthesis stay.

## Steps to Reproduce
```typescript
export type Action<TType extends string, TPayload = undefined, TMeta = undefined>
    = TPayload extends undefined ? (TMeta extends undefined ? {
        type: TType;
    } : {
        type: TType;
        meta: TMeta;
    }) : (TPayload extends Error ? (TMeta extends undefined ? {
        type: TType;
        payload: TPayload;
        error: true;
    } : {
        type: TType;
        payload: TPayload;
        meta: TMeta;
        error: true;
    }) : (TMeta extends undefined ? {
        type: TType;
        payload: TPayload;
    } : {
        type: TType;
        payload: TPayload;
        meta: TMeta;
    }));
```

## Expected behavior
Parenthesis stay

## Actual behavior

Parenthesis are gone

## Possible Origin / Solution

As part of the deox issues I'm tracking, this file shows the issue:
https://github.com/SantoJambit/shell-mwe/blob/master/src/deox.ts

**Comment by FlorianRappl** [comment]
This is not really a bug. The parenthesis are not necessary here.
