### ISSUE TITLE
alias modules starting with '@' are not supported

### ISSUE THREAD

**Issue by manishajmera** [smapiot/piral#170]
# New Feature Proposal

As a developer I need Parcel to support "alias" modules. 

## Description
Currently Piral is not supported "alias" modules and my already build project have lots of aliases .So I need this feature for my project.

**Comment by FlorianRappl** [comment]
We'll try to see if there is something we can do about it.

**Comment by FlorianRappl** [comment]
I think I have a solution - will continue to experiment here and potentially already ship something with 0.11.

**Comment by FlorianRappl** [comment]
This is now solved via [parcel-plugin-at-alias](https://github.com/FlorianRappl/parcel-plugin-at-alias).
