### ISSUE TITLE
Provide Webpack Plugin

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#171]
## Description

With #110 slowly becoming ready to go we should also solidify the Piral CLI knowledge and provide a plugin that can be used with Webpack for **building pilets**. Yes, we will (most likely) keep this pilet exclusive for several reasons:

- Most of the time pilets will be build (there is just one app shell, but many many pilets)
- Building Pilets is actually more custom than building a valid app shell - actually, this can be already built using webpack using medium effort

## Background

Other stories such as #170 would also benefit. Have something that worked beforehand but does not work now due to Parcel? Use the (Webpack) plugin.

We still believe fully in Parcel and we will soon start experimenting and contributing to Parcel v2. Nevertheless, Webpack is the most dominant bundler out there and to increase adoption we should also try to be present there.

## Discussion

Right now this plugin would allow "debug" and "build". Anything else? Scaffold etc. would still be in the Piral CLI.

We know that including Parcel makes the Piral CLI "a bit" (...) heavier. But would a modular Piral CLI (I mean we already support plugins) really make sense? How would an opt-out of Parcel look like (`piral-cli-core` ?).

**Comment by FlorianRappl** [comment]
The plugin is available in an early version:
https://github.com/FlorianRappl/piral-cli-webpack

**Comment by carvinlo** [comment]
Refactoring old projects, if there is webapck support, the cost of retrofitting will be lower

**Comment by FlorianRappl** [comment]
> Refactoring old projects, if there is webapck support, the cost of retrofitting will be lower

Definitely. Look at https://github.com/FlorianRappl/piral-cli-webpack - right now only pilets are supported, but we'll add support for Piral instances soon, too.

**Comment by carvinlo** [comment]
> > Refactoring old projects, if there is webapck support, the cost of retrofitting will be lower
> 
> Definitely. Look at https://github.com/FlorianRappl/piral-cli-webpack - right now only pilets are supported, but we'll add support for Piral instances soon, too.

Exactly what i’m looking for, thanks
