### ISSUE TITLE
reexporting a default function turns into const with type any.

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#173]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.10.9

## Description

When you default export a function, then export this in a named fashion in your exports.ts file, it becomes a const with type any.

## Steps to Reproduce

1. export default function
2. import default
3. export with a name

## Expected behavior

Should export the function type

## Actual behavior

Exports a const with type any.

## Possible Origin / Solution

See the MWE: https://github.com/SantoJambit/shell-mwe/commit/b534b409730ba00bded5b6ee504f97b8910a2eb9

**Comment by FlorianRappl** [comment]
A default export is by definition no type but rather an instance that has a type.

This issue will also not be dealt with in Piral. If you think the declaration is wrong, please open an issue (and provide a failing test) to https://github.com/FlorianRappl/dets. Thanks!

(I would love to transfer this issue, but transfers only work within the same organization)
