### ISSUE TITLE
Tutorial for Migration of Existing Applications

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#180]
## Description

Another tutorial should be added, which discusses migration from an existing application. Presumably the tutorial will use `piral-core` directly, instead of `piral`.

## Background

There are many applications out there that want to have plugin capabilities or the ability to include microfrontends.

## Discussion

Are there any aspects we should go into for sure (e.g., startup, React Router, ...)?

**Comment by carvinlo** [comment]
I am pre-researching this one.
1. Migrated from other technology stack projects, such as `react-redux-saga` and` redux-react-hook`. I may want to develop corresponding piral plugins for this, such as `piral-redux-saga` and` piral-redux-hook`. And try to use these two plugins at the same time, whether using multiple providers at the same time will affect.
2. The communication between the state of the app shell application and the pilets state container. For example, when the language status of the app shell is monitored, the pilet update is triggered. It is currently preparing to listen to the `store-data` event in the` piral-redux-saga` and `piral-redux-hook` plugins to update the pilet state container, thus triggering the pilet update.
3. Plug-in development of other vue technology stack migration
Is there any other faster or better way?

**Comment by carvinlo** [comment]
If I migrate the pilets of different technology stacks in this way, the bundle size of the app shell will increase with the increase of plug-ins of different technology stacks? Is my migration method wrong?

**Comment by FlorianRappl** [comment]
Cool!

1. Sure - all these things work. You can either just include them in your pilet or share them across pilets. For the latter providing a plugin as described could be a great way.

2. Sure you can use events, but if you use Redux anyway then you could also just connect to the container and listen for state changes.

3. Not sure what "vue technology stack" refers to. Can you clarify?

> If I migrate the pilets of different technology stacks in this way, the bundle size of the app shell will increase with the increase of plug-ins of different technology stacks?

No by default converters integrate the respective technology. This enables just using the technology. Since these technologies (e.g., angular, vue, ...) come with their own runtime etc. these are bundled in. Of course, the bundle size therefore increases.

Consequently, we would not advise including all technologies you may encounter. Sharing dependencies should be avoided if possible. If only a single pilet uses a specific technology (e.g., only one pilet uses vue) the app shell should not provide vue support. Instead, only this one pilet should ship with vue (instead of the app shell).

**Comment by carvinlo** [comment]
> 3. Not sure what "vue technology stack" refers to. Can you clarify?
"vue technology stack" refers to a collection like vue + vuex ...

If you do not sharing dependencies(providing a plugin), and where to connect (initialize) the store between pages in a pilet ? Is there any sample(vuex and redux), thank you !

**Comment by FlorianRappl** [comment]
I see thanks for the clarification.

For redux you'll find some information in the README of the `piral-redux` NPM package (https://docs.piral.io/reference/plugins/piral-redux). `vuex` or similar (i.e., anything more specific to Vue) is at the moment a total green field.

**Comment by carvinlo** [comment]
Hi,
Well, at present, it seems to be a better way to put the vue and vuex libraries in the plugin and register the global module on the page.
The vuex global module mentioned here will be a module common to multiple pages in the pilet. It cannot be placed in the pilet index file or plug-in. This will cause it to be loaded during app shell initialization, resulting in an increase in requested resources.
There is currently no specific implementation of a lazy loading module, such as registering in the pilet index file, but only to load module resources when the global module is called.
Perhaps other frameworks also have this kind of requirement, which is to provide some function code common to multiple pages, but it cannot be placed in the app shell.

**Comment by FlorianRappl** [comment]
I think you look for import maps (https://docs.piral.io/tutorials/15-share-dependencies#sharing-from-pilets).

This loads deps lazy and even allows sharing between the pilets.

**Comment by carvinlo** [comment]
Yes, you are right, for general modules. But for similar [vuex modules](https://vuex.vuejs.org/guide/modules.html), there is a little bit difference, this needs to be registered in the store before the page is rendered.

**Comment by FlorianRappl** [comment]
Sure. In general you are free to provide an API for lazy loading dependencies, too.

Maybe we should even add this to Piral via a plugin, potentially in the `piral-lazy` plugin or a new `piral-lazy-deps` plugin.

The mechanism would be to extend the list of `sharedDependencies` dynamically, together with the capability of checking / waiting for it.

Imagine a set of APIs to be used like

```ts
export function setup(app) {
  app.registerDependency('redux', () => import('redux'));
  app.registerPage('/foo', app.lazy(() => import('./Foo'), ['redux']);
}
```

So its like importmaps, but API-wise nicer and allows dependent resolutions not when the pilet(s) load, but rather when dependent components load. Furthermore, the syntax in `registerDependency` could allow doing some steps *after* the dependency is loaded (and *before* the dependency is used in the components such as pages).

**Comment by carvinlo** [comment]
Sounds powerful. Does this seem to require routing lifecycle events to ensure that the page loads before loading dependencies?

**Comment by FlorianRappl** [comment]
> Does this seem to require routing lifecycle events to ensure that the dependencies are loaded before the page is rendered?

No, because it does not directly depend on routing. It detects when a component is mounted (which can be due to routing or something else) and then checks if all dependencies are available. If not, the dependencies are loaded and a loading spinner is mounted instead.

The principle behind this is similar to things like the feed connector (https://docs.piral.io/reference/plugins/piral-feeds), just for dependencies instead of data fetching.

**Comment by carvinlo** [comment]
It's a good solution to the same scene in different frameworks, thanks !
