### ISSUE TITLE
Provide Jest Utils Package

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#186]
## Description

Testing pilets is a crucial part why Piral is so good. That you can easily just run your application - without requiring much of a setup is a big benefit.

While we advocate strongly to perform unit testing on dedicated and isolated components we also want to encourage / support people when making "bigger" unit tests that involve even functionality of the app shell.

We already scaffold a small helper that allows importing (exported) functionality from the app shell. Furthermore, we want to provide a really helpful utility library (like `piral-ssr-utils`) that can be brought in for extensive unit testing - even in complicated scenarios.

For this helper library we will focus on Jest as a unit testing framework.

## Background

We see unit tests used in all kinds of variations. One pattern we've seen is additional exports from the app shell, where the additional exports should be also used in some unit tests.

As the app shell forbids exporting functionality by default (i.e., this will be resolved dynamically at runtime) we've included a small helper that allows using app shell exports in test environments. We would love to build this into a full set of helpers (and mocks) to efficiently allow this to be reused.

## Discussion

Open questions:

- What functionality should we provide?
- Where do we leave the user and provide only guidance with patterns and tutorials?
- What version of Jest (25+?) should we support?
- Should we also think about Enzyme / React Test utils or do we leave all the details up to the user?

cc @SantoJambit

**Comment by SantoJambit** [comment]
Will take a look after new year.
