### ISSUE TITLE
Watch App Shell in Mono Repo Pilet Dev Scenarios

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#190]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

I am using Mono Repo (lerna) to develop a pilet, It is perfet that if the app shell changes, then refresh。
Now is when I change the app shell code, must be restarted to update

## Background

[#143](https://github.com/smapiot/piral/issues/143#issuecomment-611897719)

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
We'll include this in 0.11.2.

Thanks for bringing this up! :beers:

**Comment by FlorianRappl** [comment]
Landed in `develop` and the preview `@next`.

We do not refresh the browser in the implementation. Instead, we show a message in the CLI that an update to the app shell is available. A manual refresh shows the latest version.

**Comment by carvinlo** [comment]
Great!
