### ISSUE TITLE
Display webpack build progress in piral-cli-webpack

### ISSUE THREAD

**Issue by vicrsp** [smapiot/piral#191]
## Description
For large and complex systems built on Piral, having the possibility to view the webpack build progress is important for debugging reasons, specially if a custom webpack configuration has to be used. 

## Background
This is not currently supported in the CLI. If the build process hangs for some reason, there is no output that gives an indication of what happened. This is important to improve the developer experience while using Piral.

## Discussion
Setting the `--progress` flag already available in the webpack cli (https://webpack.js.org/api/cli/#debug-options) would be sufficient. The user could provide the same flag on the piral CLI, which should be applied for both debug and build options. If the flag is not provided, progress will not be displayed.

**Comment by FlorianRappl** [comment]
Thanks for reporting this!

Actually, the best location for `piral-cli-webpack` related issues is its dedicated repo: https://github.com/FlorianRappl/piral-cli-webpack.

Since transferring only works within the same orga I'd keep this one open for tracking.

**Comment by FlorianRappl** [comment]
This is now available in [piral-cli-webpack](https://www.npmjs.com/package/piral-cli-webpack) starting at v0.3.1.
