### ISSUE TITLE
TypeErrors in tutorial with typescript@3.8.3

### ISSUE THREAD

**Issue by MattShrider** [smapiot/piral#193]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral@0.11.1
Windows OS
node@v10.14.2
npm@6.4.1

## Description

[Description of the bug]
![image](https://user-images.githubusercontent.com/5342565/79380431-74061400-7f2e-11ea-9eca-de91beb95719.png)

Following [tutorial 4 ](https://docs.piral.io/tutorials/04-the-pilet-api), getting a type error when trying to use createConnector, seems like it isn't picking up the React prop types from the component provided, and manually adding the prop type / interface in the generic type of the resulting connection function doesn't work either.

The code works if you ignore the type errors, so this is pretty minimal, but I would still expect the tutorials to not throw tsc errors.

## Steps to Reproduce
```tsx
//pilet/page.tsx
import * as React from 'react';

export const path = '/page';

export interface MyPageProps {
  data: Array<{
    id: number;
    userId: number;
    title: string;
    body: string;
  }>;
}

export const MyPage: React.FC<MyPageProps> = ({ data }) => (
  <div>
    <h1>Posts</h1>
    <ul>
      {data.map(item => (
        <li key={item.id}>
          <b>{item.title}</b>
          <p>{item.body}</p>
        </li>
      ))}
    </ul>
  </div>
);
```

```tsx
//pilet/index.tsx
import { PiletApi} from 'PiralTutorial';
import * as React from 'react';
import { path, MyPage } from './page';
import { Menu } from './Menu';

const apiUrl = 'https://jsonplaceholder.typicode.com/posts';

export function setup(app: PiletApi) {
  const connect = app.createConnector(() => fetch(apiUrl).then(res => res.json()));

  app.registerPage(path, connect(MyPage));
  app.registerMenu(Menu);
  app.showNotification('Hello from Piral!');
  app.registerMenu(() =>
    <a href="https://docs.piral.io" target="_blank">Documentation</a>
  );
  app.registerTile(() => <div>Welcome to Piral!</div>, {
    initialColumns: 2,
    initialRows: 1,
  });
}
```

**Comment by FlorianRappl** [comment]
Well, that expectation cannot be always fulfilled as TypeScript and its type interpretation advances.

Sure we will try our best to keep it in sync, but in general this cannot be done from one point to all points in the future.

**Comment by FlorianRappl** [comment]
Landed in `develop` and is available in the `@next` package.

**Comment by JakeHumphries** [comment]
hi there @FlorianRappl is this change in production? i am also experiencing the above issue

**Comment by FlorianRappl** [comment]
Hi @JakeHumphries, it was fixed with 0.11.2. We are not aware of any problems in that regard. If you think there is a typing issue please post a MWE - we'll have a look at it!

**Comment by JakeHumphries** [comment]
`/* eslint-disable implicit-arrow-linebreak */
import React from 'react';
import { PiletApi } from 'shell';
import { Link } from 'react-router-dom';

const Page = React.lazy(() => import(`./Page`));

export function setup(app: PiletApi): void {
  app.registerTile(
    `sample-mf`,
    () => (
      <>
        <div>Welcome to the sample-mf app!</div>
        <Link to="/page">click here to access the app</Link>
      </>
    ),
    {
      initialColumns: 4,
      initialRows: 2,
    },
  );

  app.registerTile(() => (
    <button type="button" onClick={() => app.unregisterTile(`sample-mf`)}>
      Remove sample-mf tile
    </button>
  ));

  const apiUrl = `https://jsonplaceholder.typicode.com/posts`;

  const connect = app.createConnector(() =>
    // eslint-disable-next-line prettier/prettier
    fetch(apiUrl).then(res => res.json()));

  app.registerPage(`/page`, connect(Page));
}
`

**Comment by JakeHumphries** [comment]
repo - https://github.com/JakeHumphries/sample-mf


```javascript
// pilet/src/index.tsx
import React from 'react';
import { PiletApi } from 'shell';
import { Link } from 'react-router-dom';

const Page = React.lazy(() => import(`./Page`));

export function setup(app: PiletApi): void {
  app.registerTile(
    `sample-mf`,
    () => (
      <>
        <div>Welcome to the sample-mf app!</div>
        <Link to="/page">click here to access the app</Link>
      </>
    ),
    {
      initialColumns: 4,
      initialRows: 2,
    },
  );

  app.registerTile(() => (
    <button type="button" onClick={() => app.unregisterTile(`sample-mf`)}>
      Remove sample-mf tile
    </button>
  ));

  const apiUrl = `https://jsonplaceholder.typicode.com/posts`;

  const connect = app.createConnector(() =>
    fetch(apiUrl).then(res => res.json()));

  app.registerPage(`/page`, connect(Page));
}

```

```javascript
// pilet/src/Page.tsx
import React from 'react';

export interface MyPageProps {
  data: Array<{
    id: number;
    title: string;
  }>;
}

const Page: React.FC<MyPageProps> = ({ data }): JSX.Element => (
  <div>
    <h1>My cool page</h1>
    <ul>
      {data.map(post => (
        <li key={post.id}>{post.title}</li>
      ))}
    </ul>
  </div>
);

export default Page;

```

**Comment by JakeHumphries** [comment]
thanks @FlorianRappl issue was no typing in the creatConnector updated to the below. 

```javascript 
  const connect = app.createConnector<Array<Data>>(() =>
    fetch(apiUrl).then(res => res.json()));
```
