### ISSUE TITLE
Provide Full Template(s)

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#195]
## Description

We should provide a GitHub repo template for an (admin?) portal shell, i.e., a quite fully implemented Piral instance that could be used without much changes in many cases.

Some useful pilets can also be scaffolded / made available as templates.

## Background

Having demos, esp. such demos that look very professional is important to many people. We should try to come up with something that looks more like the things we ship in real projects than the current demo instances.

## Discussion

I would suggest to use tabler as a basis. It looks decent and has everything we need. It could be also easily customized.

- Portal Template (https://preview.tabler.io/index.html, code at https://github.com/tabler/tabler)
- Icons (https://github.com/tabler/tabler-icons)

Any other ideas?

**Comment by lamson** [comment]
Let me see if I can put out something by end of April.

**Comment by FlorianRappl** [comment]
I assigned it to you, but feel no pressure here. If anything blocks you or something else comes up - just tell us.

Awesome and thanks for contributing! :beers:

**Comment by carvinlo** [comment]
How about [realworld](https://github.com/gothinkster/realworld) ?

**Comment by FlorianRappl** [comment]
We've added a monorepo using tabler-react:

https://github.com/piral-samples/piral-admin-template

We'll continually keep improving this and we'll try to document it properly using the README.
