### ISSUE TITLE
Add "ExtensionMap" interface to "PiralInstance" ts module for better developer usability.

### ISSUE THREAD

**Issue by MattShrider** [smapiot/piral#197]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

A developer can merge types in for SharedData (getData, setData), and for PiralCustomEventMap (PiletApi.on, PiletApi.emit), but there is no such map interface for Extensions or ExtensionSlots. I think this could be added alongside the other two, to share similar developer experiences for all of the different ways to share data across pilets.

Example:
```typescript
import { ExtensionSlotProps, PiletApi } from 'PiralInstance';
import * as React from 'react';

declare module "PiralInstance" {
  interface SharedData {
    counter: string;
  }

  interface PiralCustomEventMap {
    foo: string;
  }

  /* This doesn't exist yet, but I would like it to exist */
  interface ExtensionSlotMap {
    [key: string]: any;
    counter: { value: number, onValueChanged: (num: number) => void };
  }

  /* This is how you could do something like this */
  interface ExtensionSlotPropsWithName<NAME extends Extract<keyof ExtensionSlotMap, string>, PROPS extends {} = {}> extends ExtensionSlotProps<PROPS> {
    name: NAME;
    params?: ExtensionSlotMap[NAME];
  }
}

export function setup(app: PiletApi) {
    let counter = 0;
    const handleValueChanged = (newVal) => counter = newVal; //We can't catch any type errors here
    const aComponent = <app.Extension name="foo"  params={{ count: counter, onValueChanged: handleValueChanged}} />; //This should be a type error, count should be value

    setInterval(() => {
        app.setData('counter', counter++); //Error is caught by typescript, counter must be a string
        app.emit('foo', 32); // Error is caught by typescript, foo must be string
    }, 1000);
}
```

## Background

Ideally, pilet extension type errors could be caught through declaration merging, just like emitting events and storing data. I recognize that this can be avoided entirely by sharing interfaces in npm packages, but if the precedent is there for TypeMaps, we could use that for extensions too.

## Discussion

Discussion topics can include whether this feature is worth adding, and if it isn't-so-easy to add Maps for components.

**Comment by FlorianRappl** [comment]
We've added this in the latest preview.

The map is called `PiralExtensionSlotMap` and the merging should be done via the `PiralCustomExtensionSlotMap`.

Let us know if this already fulfills your expectation!

**Comment by MattShrider** [comment]
```typescript
//DisplayValue.tsx
export interface IDisplayValueProps {
    value: string | number;
    label: string;
}
//<more>
```

```typescript
//index.tsx
import { PiletApi } from 'PiralInstance';
import * as React from 'react';
import { DisplayValue, IDisplayValueProps } from './DisplayValue';

const extensionKey = 'ExtensionProducer--display';

declare module "PiralInstance" {
    interface PiralCustomExtensionSlotMap {
        [extensionKey]: IDisplayValueProps;
    }
}

export function setup(app: PiletApi) {
    app.registerExtension(extensionKey, ({params}) => (
        <DisplayValue {...params} />
    ));
}
```

This appeared to work how i'd expect. `params` in the registerExtension call, but when I go to actually use it, it seems like the params can be anything:

![image](https://user-images.githubusercontent.com/5342565/80010252-27738900-8498-11ea-857e-8e55b03093e1.png)

This should throw an error , because `{ foo: 'bar' }` does not match the interface `IDisplayValueProps`

Note that the interface DOES seem to be getting merged correctly, because the `type a = ...` line is correctly pulling in the map interface.
