### ISSUE TITLE
Document use of regeneratorRuntime

### ISSUE THREAD

**Issue by MattShrider** [smapiot/piral#200]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral@0.11.3-pre.1117
windows using WSL Ubuntu
node v10.14.2

## Description

![image](https://user-images.githubusercontent.com/5342565/80030474-3832f780-84b6-11ea-9277-98c3eda84049.png)

Emitting an event is failing due to what seems like a babel issue in one of my pilets. This may be due to the event being emitting from inside of a promise?

## Steps to Reproduce

```typescript
import { PiletApi, PiralCustomEventMap } from 'PiralInstance';
import * as React from 'react';

const emitChangedKey = 'EventProvider--changed';
const handleClickKey = 'StateConsumer--click';

declare module 'PiralInstance' {
    interface PiralCustomEventMap {
        [emitChangedKey]: string;
        [handleClickKey]: string;
    }
}

/** Takes a string and makes it upper case after waiting half a second */
const transformer = async (text: string): Promise<string> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(text.toUpperCase());
        }, 500);
    });
};

export function setup(app: PiletApi) {
    const handler = (clickText: string) => {
        console.log('Click Event Received', clickText);
        transformer(clickText)
            .then(newText => app.emit(emitChangedKey, newText))
    };

    app.on(handleClickKey, handler);
}
```
Then emit 'StateConsumer--click' with a string value to piral.

## Expected behavior

After the transfom function resolves, piral should emit a new event to 'EventProvider--changed' with the upper case value of the string.

## Actual behavior

```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at r (index.tsx:27)
    at index.tsx:27
    at HTMLBodyElement.listener (events.ts:14)
    at HTMLBodyElement.document.body.dispatchEvent (<anonymous>:7:9)
    at Object.emit (events.ts:35)
    at onClick (index.tsx:48)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.j
```

## Possible Origin / Solution

Perhaps this is due to me using async / await in the transformer function.

**Comment by MattShrider** [comment]
Follow up: After removing the `async` keyword from this file, everything runs fine. It seems like parcel isn't picking up to include the `async/await` polyfill from babel.

**Comment by FlorianRappl** [comment]
> It seems like parcel isn't picking up to include the async/await polyfill from babel.

Parcel does not do anything with polyfills - you will need to take care of that yourself.

We have some polyfills prepared in `piral/polyfills`, but since async / await is either covered by TS (depending on your target) or can be avoided we do not include regenerator runtime.

I guess we should add this to the docs.
