### ISSUE TITLE
piral upgrade command does not check for yarn.lock

### ISSUE THREAD

**Issue by lamson** [smapiot/piral#203]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

yarn@1.22.4
piral-cli@0.11.3
MacOS 10.14.4

## Description

`piral upgrade` command (and possibly other commands) have `--install` flag `true` by default. I noticed my upgrade patched "package.json", but didn't install the dependencies.
According to the logs, I believe the command only check for "package-lock.json", not "yarn.lock"

## Steps to Reproduce

(I probably can do a MWE if needed, but in short of time, sorry...)

1. Go to an existing piral target which needs an update. This target uses `yarn` client, not `npm`
2. Run `piral upgrade`

## Expected behavior

`piral-cli` uses current npmClient to run install dependencies

## Actual behavior

"package.json" was patched with new `piral-cli` version
Installation of dependencies didn't happen

See logs

```
 ✘  100%  ~/workspace/shell-backup/ui feature/piral-upgrade
 ❯ piral upgrade --log-level 5
[7:29:40 AM]: [0003] Checking directory "/Users/snguyen/workspace/shell-backup/ui" ...
[7:29:40 AM]: [0003] Target exists, but not yet clear if directory.
[7:29:40 AM]: Checking provided version ...
[7:29:40 AM]: [0003] Starting the NPM process ...
[7:29:40 AM]: [0003] Applying NPM cmd "npm show piral-cli version --tag latest" in directory "/Users/snguyen/workspace/shell-backup/ui".
[7:29:40 AM]: [0003] Running "npm show piral-cli version --tag latest" in "/Users/snguyen/workspace/shell-backup/ui" ("/Users/snguyen/workspace/shell-backup/ui/node_modules/.bin").
[7:29:41 AM]: [0003] NPM show result: 0.11.3
[7:29:41 AM]: [0003] Found real version: "latest".
[7:29:41 AM]: [0003] Updating all dependencies ...
[7:29:41 AM]: Reading installed packages ...
[7:29:41 AM]: [0003] Patching the package.json ...
[7:29:41 AM]: [0003] Checking if file "/Users/snguyen/workspace/shell-backup/ui/package.json" exists ...
[7:29:41 AM]: [0003] Updating file "/Users/snguyen/workspace/shell-backup/ui/package.json" ...
[7:29:41 AM]: Updating the NPM packages to latest ...
[7:29:41 AM]: [0003] Starting the NPM process ...
[7:29:41 AM]: [0003] Applying NPM cmd "npm install --no-package-lock" in directory "/Users/snguyen/workspace/shell-backup/ui".
[7:29:41 AM]: [0003] Running "npm install --no-package-lock" in "/Users/snguyen/workspace/shell-backup/ui" ("/Users/snguyen/workspace/shell-backup/ui/node_modules/.bin").
null
Codes Reference: https://docs.piral.io/code/search
```

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
That's true - we exclusively use `npm` under the hood.

What is the general approach to decide this (yarn vs npm)?

1. Check if there is `package-lock.json` -> [yes] use npm (done)
2. Check if there is `yarn.lock` -> [yes] use yarn (done)
3. Check the system's default manager (can this be done??) -> [found] use this one (done)
4. Fall back to npm (done)

No idea about (3) and if there is a general mode. Maybe someone has an idea here.

For scaffolding we would start our alg. at (3) since nothing would exist at this point.

**Comment by lamson** [comment]
It might be easier to explicitly define which `npmClient` to use. I have since devs unconsciously run `npm install` in a project which uses `yarn`, and the project ends up with both `package-lock.json` and `yarn.lock`.

lerna has `npmClient` config to specify `yarn` or `npm`. https://github.com/lerna/lerna/blob/master/commands/bootstrap/README.md#usage

**Comment by FlorianRappl** [comment]
I think this may work:

1. Check if there is `package-lock.json` -> [yes] use npm (done)
2. Check if there is `yarn.lock` -> [yes] use yarn (done)
3. Check the default `npmClient` in the `.piralrc` -> [yes] use found version (done)
4. Check if inside a lerna mono repo -> [yes] use found client (done)
5. Fall back to npm (done)

**Comment by lamson** [comment]
I think explicit declaration should be precedent. 

1. `.piralrc` - more specific to piral-cli 
2. lerna `npmClient` - when users setup lerna, they were asked to select `npmClient`
3. `package-lock.json`
4. `yarn.lock`
5. Fall back to `npm`

**Comment by FlorianRappl** [comment]
> I think explicit declaration should be precedent.

I would not do that. There are two main reasons for that:

1. If your current project contains already a file -> this is what you *should* definitely use
2. Your rc file may not be in the project directory, it may be in your home directory (so in this case you may use a global setting to override an explicit local one resulting exactly in the behavior you want to avoid)

The locations for the merging of rc files is outlined at https://www.npmjs.com/package/rc.

The lerna case should not appear often - and if it does and should be usually covered by having a package-lock.json or yarn.lock already. Thus checking for such files should be priority. Lerna is a special application and we should not treat it with prio.

The only thing left is what if there are both - package-lock.json and yarn.lock. According to the algorithm above first one wins, however, it could be that a project switched and just forgot to delete the old file.

Of course, the argumentation above regarding shifting down `.piralrc` also should be used compared to lerna. So my new proposal would be:

1. Check if there is `package-lock.json` -> [yes] check npm
2. Check if there is `yarn.lock` -> [yes] check yarn
3. If only npm or yarn (one of the both) -> [yes] return checked (done)
4. Check if inside a lerna mono repo -> [yes] use found client (done)
5. If npm and yarn checked (both) -> [yes] return more recent file (done)
6. Check the default `npmClient` in the `.piralrc` -> [yes] use found version (done)
7. Fall back to npm (done)
