### ISSUE TITLE
Ability to include "--cacert" arg in `pilet publish` command

### ISSUE THREAD

**Issue by lamson** [smapiot/piral#204]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

I deployed a [sample-feed-service] in our engineering kubernetes cluster for testing purpose. The services in cluster requires ca cert to make POST (and other types of 'mutation' requests). 
```
pilet publish --fresh --url $FEED_SERVICE_URL --api-key $FEED_SERVICE_API_KEY --env .env.prod
```
Running the command above works well locally, but not when the service is deployed due to missing cacert.

I have a very dirty workaround... manually modified `/node_modules/piral-cli/lib/common/http.js` to inject `agentOptions: { ca: fs.readFileSync('$PEM_PATH') }` to include my cacert in the publish request... 

```shell
export FILE_PATH=$(pwd)/node_modules/piral-cli/lib/common/http.js
export PEM_PATH=$(find $(pwd) | grep cacert.pem)
export FIND="method: 'POST',"
export REPLACE="method: 'POST', agentOptions: { ca: fs.readFileSync('$PEM_PATH') },"
sed -i '' -e "s#$FIND#$REPLACE#g" $FILE_PATH
export FIND='const request = require("request");'
export REPLACE='const request = require("request"); const fs = require("fs");'
sed -i '' -e "s#$FIND#$REPLACE#g" $FILE_PATH
cat $FILE_PATH
```

## Background

[Provide any additional background for the feature, e.g., why is the current solution insufficient, what problem will it solve, etc.]

I think it will be nice to accept `--cacert` in the command arguments, though I'm unsure if many have my use case.

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
Sure, we can add this flag to the command for `pilet publish`.

I think at this point in time its also important to specify the options for the RC file. Yes, the Piral CLI consumes an RC file (if available), which could be quite helpful to avoid having many (repeating) args.

**Comment by lamson** [comment]
Good point. I do have an `.npmrc` file that has the `ca` argument. That would be much easier to manage.

**Comment by lamson** [comment]
Another note, we also use private NPM registry so we do configure `registry` in `.npmrc` as well.

**Comment by lamson** [comment]
`pilet publish --ca-cert $CERT_PATH` works as expected. Thank you @FlorianRappl !

Verified with version `0.11.4-pre.1131`

**Comment by FlorianRappl** [comment]
Thanks @lamson !

Landed in `develop` and available in the preview `@next`.
