### ISSUE TITLE
Hi from the single-spa team

### ISSUE THREAD

**Issue by joeldenning** [smapiot/piral#205]
Hi there 👋 - I'm one of the maintainers of single-spa and came across this project today. I am excited to see more and more microfrontend frameworks pop up - it's nice to have alternatives to monolithic solutions. I applaud your efforts and impressive progress on piral.

One thing I'm excited to check out in more depth is your solution for SSR. Single-spa is lacking in that area and it's something we're working on right now. I'd love to chat sometime (twitter/slack?) to hear how you came to your solution and potentially even see if there's room for our two communities to collaborate on SSR or other things. The anti-microfrontends people are more numerous than the microfrontends people right now, and I'd love to see our communities cooperate to help change that 😄

Regarding the Alternatives section in your documentation (https://docs.piral.io/reference/documentation#alternative-solutions), I'm curious the reasoning behind so many X's on the single-spa column. Being honest, I found the representation of single-spa to be rather inaccurate. Specifically here are the things that single-spa does support that are misrepresented:

- Free Tooling Choice. Single-spa works with or without a bundler, and your bundler can be webpack, rollup, or anything else. You can use any test framework, any CI, any UI framework, etc. Really there are almost no limitations to which tooling can be used with single-spa, which is why it still continues despite having been authored in 2015.
- Translations. Single-spa supports translations in every way that React, Vue, and Angular support translations. We let those frameworks do it instead of us. For example, i18next completely works with single-spa.
- Standards Driven. Single-spa uses in-browser javascript modules and import maps, both of which are browser standards. "Standards driven" is perhaps a subjective term, but I'm curious what disqualified single-spa from this.
- Free development. I'm not sure if "free" refers to price or to something else. But single-spa is definitely 100% open source and free, with the MIT license. If "free" refers to "easy", we have local development very well documented and it is very easy to set up. [Link](https://single-spa.js.org/docs/recommended-setup#local-development)
- Typescript support. Single-spa exposes typescript definitions for its library. Additionally, our CLI create-single-spa lets you set up Typescript projects with a single command.

I hope that me raising these questions does not come off as argumentative, because that's not my intent. I understand how documentation for a project tries to make a case for why one project is better than the alternatives, and don't expect you to weaken that case. I just was genuinely surprised to see single-spa misrepresented on some important topics.

**Comment by FlorianRappl** [comment]
Hi @joeldenning - thanks for bringing this up.

> The anti-microfrontends people are more numerous than the microfrontends people right now, and I'd love to see our communities cooperate to help change that.

Fully agreed!

Regarding some of the points: Obviously you can do anything - and that applies to most of the solutions. So a checkmark means "out of the box". For instance, we have `piral-translate` which gives you an out of the box solution. You can - of course - swap that out for any solution; like you do with Single SPA where you need to use any solution. The whole thing is more a "framework" vs "library" discussion at this point.

Happy to discuss all the individual points and to correct them where we placed a wrong (maybe historically wrong?) qualification.

Just join our Gitter chat and message me there!

(Closed for the follow up on Gitter chat - but feel free to add things here if relevant.)

**Comment by joeldenning** [comment]
👍 thanks for the quick response. I'll join the gitter!
