### ISSUE TITLE
The Emulator should Not Be Minified

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#207]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Any environment (e.g., WSL), 0.11.3 of Piral CLI.

## Description

When building / using an emulator version of an app shell (e.g., via `piral build`) the resulting emulator code is minified and tuned for production except in areas such as dev tooling etc.

Consequently, some dependencies such as `react` will not show warning when developing a pilet using `pilet debug`.

## Steps to Reproduce

1. Create a new app shell (e.g., `npm init piral-instance`)
2. Create the emulator (`piral build`)
3. Create a new pilet (e.g., `npm init pilet`) using the emulator from step (2)
4. Register a page using

```tsx
<ul>
{[1,2,3].map(m => <li>{m}</li>}
</ul>
```

5. Go to the registered page

## Expected behavior

A warning from React should be shown - no keys provided for the array.

## Actual behavior

Nothing is shown.

## Possible Origin / Solution

Since the emulator uses the `process.env.NODE_ENV` set to `production` the React dev messages are stripped out.

**Comment by lamson** [comment]
I recently ran into this issue. Is there a workaround we can do? Possibly set NODE_ENV=development before piral build?

**Comment by FlorianRappl** [comment]
> I recently ran into this issue. Is there a workaround we can do?

There is no easy workaround for this. The NODE_ENV is set explicitly to `production` in the Piral CLI. You can hack this (`build-piral.js` in `piral-cli/lib/apps/`) by setting `production: true` to `production: !develop`, but I don't know yet the side-effects.

I'll tell you when I know a better workaround.

Shifting prio up.

**Comment by FlorianRappl** [comment]
In `develop` and the preview `@next`.

**Comment by lamson** [comment]
I can verify that the emulator includes `react-dom.development.js` module now. Though I wonder if the "Piral State Change" console log should print non-minified JS as well? Specifically the "Action" log.

No big deal, just curious. 

![Screen Shot 2020-04-30 at 7 02 19 PM](https://user-images.githubusercontent.com/1919336/80775943-e7ef1180-8b15-11ea-9c7d-5c0b6892809b.png)

**Comment by FlorianRappl** [comment]
I think its a fair point @lamson - we still minify, but changed `NODE_ENV` to production. So we did not really fulfill the title even though we fixed the bug.

I guess we should also minify -> false as you said. It would benefit the state change quite nicely.

Great observation and suggestion!

I'll reopen until done.

**Comment by FlorianRappl** [comment]
Landed in `develop` and the preview `@next`!
