### ISSUE TITLE
piral-oidc is missing a way to fetch user profile and is mis-documented

### ISSUE THREAD

**Issue by dustinchilson** [smapiot/piral#210]
# Bug Report

## Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version?
- [X] Did you perform a search in the issues?

## Environment Details and Version

- piral: 0.11.4-pre.1124
- piral-oidc: 0.11.4-pre.1124

## Description

The OIDC plugin & its documentation does not implement a `client.account()` function as described. This seems to have been copied from the adal plugin docs.

## Steps to Reproduce

1. Setup the OIDC Client as documented.
2. Check the `client.account()` on page load as described

## Expected behavior

account() to exist or another method to exist with similar functionality. Updated Documentation.

## Actual behavior

Not Implemented

## Possible Origin / Solution

OIDC-Client has a `getUser` function that returns a User Object. The `profile` property might work as an alternative.

https://github.com/IdentityModel/oidc-client-js/wiki#user

**Comment by FlorianRappl** [comment]
Thanks for the report!

We'll look into this!

cc @manuelroemer

**Comment by MattShrider** [comment]
I have work in progress on this.

**Comment by FlorianRappl** [comment]
Alright thanks for the note @MattShrider !

I've assigned it for the moment being to you to mark it appropriately. Much appreciated!
