### ISSUE TITLE
Provide route lifecycle management

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#214]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Provide route lifecycle management to do something when the route changes, such as switching layout or other actions. For example events such as `routeChangeStart` ... [Router.events](https://nextjs.org/docs/api-reference/next/router#routerevents)

## Background

[Provide any additional background for the feature, e.g., why is the current solution insufficient, what problem will it solve, etc.]

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
Thanks for the suggestion.

We cannot provide these events, as we do not know the `Router` for sure. The `BrowserRouter` (using an instance from the `history` package) is our default implementation, however, this may be changed by the end user (or be replaced with something that does not use `history` at all).

That being written - you can always provide these events yourself. For once, every component you write can use the `useHistory` hook to get the `history` instance and attach a listener. Likewise, you can obviously supply a `Router` instance with all the events being wired up in your app shell.

What are your thoughts?

**Comment by carvinlo** [comment]
Use HOC instead of a normal Route, like [react-router-hooks](https://github.com/sammorrow/react-router-hooks)?

**Comment by FlorianRappl** [comment]
You can do that, yes. Or you juse use `useHistory` :).

**Comment by carvinlo** [comment]
I try it, thanks
