### ISSUE TITLE
Add base interface for all modal options defined through PiralCustomModalsMap

### ISSUE THREAD

**Issue by nolanlocke** [smapiot/piral#217]
# New Feature Proposal

## Description

Adding a base interface for all. In the OpenModalDialog interface options passed to the modal are available but [typed as any](https://github.com/smapiot/piral/blob/develop/src/packages/piral-modals/src/types.ts#L104). 

Suggesting a `BaseModalOptions` interface that will be used to extend every interface defined in `PiralCustomModalsMap`, and be typed in the OpenModalDialog interface as well.

## Background

While implementing piral-modals I am wrapping my `ModalsDialog` component with material-ui Dialog. The aria properties and options like `disableEscapeKeyDown` were not easily passable to the ModalsDialog component without manual extension on each custom interface and handling of the `any` options in the component.

## Discussion

I don't see any cons to doing this, though the way this came about may have been a general misuse of how the ModalsDialog component was intended to be used.

**Comment by FlorianRappl** [comment]
Implemented in #218.

Available in the preview `@next` and in the `develop` branch.
