### ISSUE TITLE
piral-oidc - Handle page redirects and oidc-client events better

### ISSUE THREAD

**Issue by MattShrider** [smapiot/piral#219]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description
(This ticket is for historical purposes, i'm currently working on it)

The piral-oidc library should handle the entire authentication process itself, including redirecting to a user-configurable route after getting a session from the authentication redirect process.

What needs to happen:
* setupOidcClient() should only call oidc callbcks when on the correct route
* a new option should be added named "app_uri" which is an optional route for piral to redirect to after getting authenticated in the main viewport. (Redirect-based authentication)
* allow piral-api to respond to user manager events, such as userLoaded.

**Comment by FlorianRappl** [comment]
I guess by default `app_uri` would be `/`? Should it be called `appPath` or something similar or would you require an absolute URI?

Otherwise sounds great. Thanks for your contribution :rocket:!

**Comment by MattShrider** [comment]
I'm planning on having it be an absolute url named `app_uri`, because we already have settings for `redirect_uri` and `post_logout_uri` in oidc. We can definitely have it have a default of window.location.origin though, I think that is a good idea.

Now that i'm in the code though, it seems like the redirect to `app_uri` can be totally optional if left null, so that may also be a good option.

The footprint of the app-shell looks something like this:
```
//app-shell/index.tsx
oidcClient.handleAuthentication()
  .then((shouldRender) => {
    if (shouldRender) render();
  })
  .catch((e) => {
    logger.fatal(e);
    oidcClient.logout();
  });
```
