### ISSUE TITLE
When running in monorepo mode public url of piral instance is not "/"

### ISSUE THREAD

**Issue by nolanlocke** [smapiot/piral#220]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
https://github.com/nolanlocke/piral-mono-example
* Instructions on how to reproduce specifically with the monorepo is available in the readme
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, OS, Browser, ...]
piral-cli 0.11.4
yarn 1.22.4

## Description
When running the app in monorepo mode, the public url for the app shell is not defaulting to "/" and will attempt to load the piral source file from the current url.

## Steps to Reproduce

1. Run `pilet debug` against a pilet that is using a local piral instance (via symlink)
2. Navigate to http://localhost:1234/foo/bar/
3. It should fatally error. Inspecting the generated html file should have `<script src="src.f69400ca.js"></script>` without the leading `/` (which is there when running `piral build` 

## Expected behavior
The public url should be `/` for the generated html file

## Actual behavior
There is no public url and it causes loading in on deep routes to error

## Possible Origin / Solution
Going through the source I didn't see a particularly easy way to solve this when looking through the monorepo code.

My temporary workaround is to add  `<base href="/" />` to the index.html but it's not a very long term solution.

**Comment by FlorianRappl** [comment]
This landed in the preview / `develop`. You could try upgrading to `piral-cli@next`.

**Comment by nolanlocke** [comment]
Thanks again Florian! And sorry about the half-sentence of a title. just fixed that.
