### ISSUE TITLE
Support Lazy Loading with Dependencies

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#226]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Request to improve piral-lazy's support for react components, so that it can be extended to support other scene features, such as scenes that depend on common modules

## Background

[react component](https://github.com/FlorianRappl/piral-cli-webpack/issues/16#issuecomment-633411871)
[registerDependency api](https://github.com/smapiot/piral/issues/180)

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
There will be two features added to `piral-lazy`:

1. Allow also React components, even though its just as `React.lazy` under the hood
2. Allow a second (optional) argument, which is an array of dependencies to add

For (2) we need also another API to be added, `defineDependency`, which adds a name and a resolver.

So (1) can take full advantage of this.

Note, that this is not a competition with import maps. In fact, it will also work with import maps. But it will also work in other scenarios. So it could be quite handy.

**Comment by FlorianRappl** [comment]
This landed in `develop` and the preview (`piral-lazy@next`).

**Comment by carvinlo** [comment]
I use it in various scenarios:
Before the page is rendered, request the common data that the page depends on and set it in the redux store for the page to use.
```ts
const TranslatePage = () => import('./translatepage').then(m => m.default);
const common = () => import('./common');
const prerequest = () =>
  fetch('/somedata').then(res => {
    return import('./setstore').then(m => m.default(res));
  });
...
  app.defineDependency('common', common);
  app.defineDependency('prerequest', prerequest);
  app.registerPage('/translate', app.fromLazy(TranslatePage, ['common', 'prerequest']));
```
`./setstore.ts`
```ts
export default res => {
  console.log(res);
};
```
`piral-lazy` is great after improvement !

**Comment by FlorianRappl** [comment]
Cool - glad that you like it! :beers:

Can we use the examples you gave for the README / documentation of `piral-lazy`? Thanks!

**Comment by carvinlo** [comment]
Of course, it is an honor!
