### ISSUE TITLE
`includeProvider` discards props

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#227]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral-cli@0.11.5

## Description

In the scenario of multiple providers(such as redux's Provider and the ant-design's [LocaleProvider](https://github.com/ant-design/ant-design/blob/master/components/locale-provider/index.tsx)), cloneElement will cause the context of the previous provider to be lost.

## Steps to Reproduce

1. include redux's provider
```ts
import { Provider } from 'react-redux'; // version 7.2.0
...
const provider = createElement(Provider, { store });
context.includeProvider(provider);
```
2. include ant-design's LocaleProvider
```ts
import { LocaleProvider } from 'antd'; // version ^3.0.0
...
const localeProviderlocale = rerquire('antd/lib/locale-provider/en_US');
const provider = createElement(LocaleProvider, { locale:localeProviderlocale });
context.includeProvider(provider);
```
3. using plugins
```ts
import { createReduxHookApi } from 'piral-redux-hook';
import { createAntdApi } from 'piral-antd';
...
renderInstance({
  extendApi: [
    createReduxHookApi(),
    createAntdApi(),
  ]
});
```
4. show error: could not find store
View the rendering node through the react devtool plugin:
```
...
PiralProvider
  LocaleProvider
    Anonymous
...
```

## Expected behavior

redux's Provider and ant-design's LocaleProvider should be work

## Actual behavior

antd's locale works fine, but could not find the redux's store

## Possible Origin / Solution

Try swapping plugin order
```ts
import { createReduxHookApi } from 'piral-redux-hook';
import { createAntdApi } from 'piral-antd';
...
renderInstance({
  extendApi: [
    createAntdApi(),
    createReduxHookApi(),
  ]
});
```
then antd's locale is not working, and redux works fine

Try to adjust to recursive way
1. `piral-core/src/types/state.ts`
```ts
export interface GlobalState extends PiralCustomState {
...
provider?: any;
}
```
2. `piral-core/src/actions/app.ts`
```ts
export function includeProvider(ctx: GlobalStateContext, provider: any, props: any) {
 ctx.dispatch(state => {
  if(state.provider){
   state.provider.push(provider);
  }else{
   state.provider = [provider);
  }
  return { ...state };
 })
}
```
3. `piral-core/src/components/PiralView.tsx`
```ts
const PiralProvider: React.FC = ({ children }) => {
 const provider = useGlobalState(m => m.provider) || [];
 function forProvider(provider, children) {
  if(provider.length){
   const provider = providers.pop();
   return React.cloneElement(provider, undefined, forProvider(providers, children);
  }
  return <React.Fragment>{children}</React.Fragment>;
 }
 return forProvider(provider, children);
}
```
4. both redux's Provider and ant-design's LocaleProvider works fine
View the rendering node through the react devtool plugin:
```
...
PiralProvider
  LocaleProvider
    Provider
      ReactRedux.Provider
        Anonymous
...
```

**Comment by FlorianRappl** [comment]
Thanks for the detailed report :rocket:. I can confirm this issue and we might have a solution. :tada:

Unfortunately, the proposed solution does not work fully as it would be a breaking change to the `includeProvider` API.

Instead, we'll keep the API, but change the underlying implementation. In the state we'll now use a `ComponentType` instead of a `JSX.Element`. We'll get that `ComponentType` by building proper wrappers.

Fix incoming! :robot:

Thanks again for your awesome contribution 🚀 !

**Comment by FlorianRappl** [comment]
Fix landed in `develop` and should be in the preview in some minutes.

**Comment by FlorianRappl** [comment]
Looks good in our testing process. :tada:

If anything still fails for you @carvinlo please reply here. Thanks :beers!

**Comment by carvinlo** [comment]
It works fine ! :+1:

**Comment by carvinlo** [comment]
I implemented an updated provider props, but encountered another problem. [Use Pub / Sub to dispatch to update the state and get the old value
](https://github.com/smapiot/piral/issues/228)

**Comment by carvinlo** [comment]
Please ignore it, it has been solved.
