### ISSUE TITLE
Unable to set breakpoints in pilet

### ISSUE THREAD

**Issue by nolanlocke** [smapiot/piral#229]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
  - https://github.com/nolanlocke/piral-monorepo-sample/tree/feature/mono-debug-replication
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version
* Piral 0.11.5
* Running in a monorepo

## Description
When running pilet debug against a pilet, I am unable to set breakpoints in any of my pilet code.

Debugging and breakpointing in app shell works perfectly. Have only had issues with this in pilets

## Steps to Reproduce
* Running `pilet debug` in monorepo mode

## Expected behavior
Be able to set breakpoints inside of pilet code

## Actual behavior
Breakpoint / debugging don't appear to work

**Comment by FlorianRappl** [comment]
Can you give details on the browser (Chrome-based)? Thanks!

**Comment by nolanlocke** [comment]
Yes! Using Chrome Version 83.0.4103.61

**Comment by FlorianRappl** [comment]
Landed in the preview and in `develop`.

You can try it out in by installing the `piral-cli@next` together with `piral-cli-parcel@next` (or running `piral upgrade next`).

As a goody I also de-minified the source code of the pilets during debug. I think it greatly helps with exceptions and when debugging using source maps (Chrome then displays better stack traces etc.).

Feedback appreciated! :beers:

**Comment by nolanlocke** [comment]
This is working like a charm, thanks once again for the quick response Florian! 🍻
