### ISSUE TITLE
Example for integrating Ionic components in Piral

### ISSUE THREAD

**Issue by MovingBitsGroupRoth** [smapiot/piral#230]
## Description

Ionic is a cross-platform framewok that is built on the awesome Stencil toolchain for building WebComponent with a very small footprint.

[Ionic Framework](https://ionicframework.com/)

[Stencil](https://stenciljs.com/)

## Background

It would be very nice to see an example that shows the integration of Ionic in Piral.

**Comment by FlorianRappl** [comment]
Thanks for bringing this up :tada:. We'll try to get it out there by eo next week.

**Comment by FlorianRappl** [comment]
We started to provide a sample here.

Repository will be https://github.com/piral-samples/piral-ionic-sample.
