### ISSUE TITLE
Piral Pilet Dependencies Should Conserve Origin

### ISSUE THREAD

**Issue by vitaleone** [smapiot/piral#233]
## Description

On sharing from Piral to Pilet a primary pattern library package, that depends on git repository, get error on run npm install command on pilet

## Steps to Reproduce

1. In app shell package.json file did add:
-  dependencies field

"dependencies": {
    ...
    "my-lib-vue": "git+ssh://git@gitlab.com/my-lib-vue.git#branch"
  },

- pilets field
 "pilets": {
    ...
    "externals": [
      "my-lib-vue"
    ], 

2. piral build 

3. pilet new ...piral_main/dist/develop/lms_piral_main-1.0.0.tgz --target pilet-with-dependencies

## Expected behavior

Pilet creation without errors

## Actual behavior

Get error:
```
⠙ Installing dependencies ...npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/my-lib-vue- Not found
npm ERR! 404 
npm ERR! 404  'my-lib-vue@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'pilet-with-dependencies'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by FlorianRappl** [comment]
Can you test that fix @vitaleone ? Its available in the `next` version.

Easiest path to upgrade to it is using `piral upgrade next` in your Piral instance repository / directory. Thanks!

**Comment by vitaleone** [comment]
Did test a fix, everything is working

Thanks!
