### ISSUE TITLE
Add ability to debug multiple pilets at once (monorepo support)

### ISSUE THREAD

**Issue by nolanlocke** [smapiot/piral#234]
# New Feature Proposal

## Description
Requesting the feature to run pilet debug on multiple pilets at once (with one app shell emulator) for a nice development flow in a monorepo

## Background
We are currently using piral in a monorepo and it would be extremely nice to have one command that would run multiple pilets in debug at once.

Spoke to @FlorianRappl briefly in the community chat and he said this was actively being looked into with the following in mind:
> What we are after here is to allow something like `pilet debug packages/pilet-*`
> Essentially, it would start debug processes for all found pilets (but only a single app shell emulator) - accessing, e.g., `localhost:1234` would then load all found pilets + change them on the fly when you change them

## Discussion
This would be a great quality of life addition for monorepo development.

**Comment by FlorianRappl** [comment]
Looks good so far.

Already added to our mono repo template (https://github.com/piral-samples/piral-admin-template, see the `watch:all` command) - seems to be working great!
