### ISSUE TITLE
Pilet Debug Not Fetching Pilets in VS Code Server

### ISSUE THREAD

**Issue by edgarravenhorst** [smapiot/piral#235]
# Bug Report

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE]? : 
unsure
- [x] Are you running the latest version?: 
- [x] Did you perform a search in the issues?:

## Environment Details and Version

- Development on VS Code server
- Piral debug running on the code-server accessed by domain name instead of localhost.
- Same app works when running piral debug locally

## Description

When running "piral debug" on a dev server the application is unable to fetch the required js files because it's trying to fetch the files from http://localhost:1234/$pilet-api//index.js

## Steps to Reproduce

unsure how to reproduce without code-server

## Expected behavior

I would expect that the application to fetch the files from http://some.domain:1234/$pilet-api//index.js

## Actual behavior

it fetches the files from http://localhost:1234/$pilet-api//index.js

**Comment by FlorianRappl** [comment]
Should be doable. Thanks for bringing this up!

Once we have a fix out there, could you please verify / test it?

Much appreciated!

**Comment by FlorianRappl** [comment]
This is now in `develop` and available via the `@next` version.

Can you try upgrading to `piral-cli@next` on your VS Code Server? Feedback appreciated. Thanks @edgarravenhorst !

**Comment by edgarravenhorst** [comment]
@FlorianRappl Looks like it's working! Many thanks :)

**Comment by FlorianRappl** [comment]
Thanks for testing! :beers:
