### ISSUE TITLE
Make Webpack a First Class Option

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#237]
## Description

Integrating the `piral-cli-webpack` plugin as a standard Piral package (which fits into our release cycle) would simplify a lot of things - most notably it would make Webpack a first-class citizen.

## Background

Right now Webpack support is given via [piral-cli-webpack](https://github.com/FlorianRappl/piral-cli-webpack), however, this support (even though still working) was done pre 0.11.5 - where bundlers could not easily swapped.

Obviously, the swapping of bundlers should be part of that plugin. To go even one step further the plugin should be synced with the standard Piral release cycle.

## Discussion

We should also support an additional flag that is available on all commands that (may) use a bundler: `--bundler`.

By default, this flag would pick the first integrated bundler (or install / try to choose Parcel or the bundler from the `.piralrc` file), however, it could be also just picked `--bundler webpack`: If not installed a plugin with that name will be resolved (`piral-cli-webpack`).

**Comment by FlorianRappl** [comment]
Available in `develop` and the preview version.

**Comment by carvinlo** [comment]
Can I test with the latest version now? If it is now, I will reproduce the issue that appears to you. If this function is still being tested, please ignore this message, thanks!

**Comment by FlorianRappl** [comment]
Its the next version, not the latest.

**Comment by carvinlo** [comment]
In debug pilet mode, seems the shared dependencies did not work, and found that this [code](https://github.com/FlorianRappl/piral-cli-webpack/blob/25ac7d4d17d56dac6a7ecdb2ae9f08c7a28d4aa8/packages/pilet-webpack-plugin/src/index.ts#L34) always didn't execute.

**Comment by FlorianRappl** [comment]
I think you have the wrong version @carvinlo .

What you point to no longer exists. This is the new version: https://github.com/smapiot/piral/tree/develop/src/tooling/piral-cli-webpack

And again - its not `latest` it is `next`. https://www.npmjs.com/package/piral-cli-webpack/v/0.11.7-pre.1433

**Comment by FlorianRappl** [comment]
Also see:
https://github.com/FlorianRappl/piral-cli-webpack/tree/25ac7d4d17d56dac6a7ecdb2ae9f08c7a28d4aa8/packages

There is no longer `piral-cli-webpack` in that repository.

**Comment by carvinlo** [comment]
I updated to `piral-cli@0.11.7-pre.1433`, then used `pilet debug --bundler webpack`, and then showed ʻUnrecognized option: bundler`

**Comment by FlorianRappl** [comment]
There is no such option for `pilet debug` or any other build command. The `--bundler` option only applies to `piral new` or `pilet new` - to select what bundler to install.

You should just install the plugin and run `pilet debug` (or `piral debug` for your Piral instance).

This story is about making Webpack a first-class option, i.e., it just works with the usual commands.

Hope you now have a better picture of this.

(For all available options feel free to use, e.g., `pilet debug --help`).

**Comment by FlorianRappl** [comment]
Alternatively, use our documentation (e.g., https://github.com/smapiot/piral/blob/develop/docs/commands/debug-pilet.md). You'll see no option `--bundler` (not sure why you think there should be such an option).

Also consult the README of [piral-cli-webpack](https://github.com/smapiot/piral/tree/develop/src/tooling/piral-cli-webpack). It just tells you to use the standard commands, too.

**Comment by carvinlo** [comment]
I'm sorry I didn't re-view the new version of the document and only saw the discussion:
> By default, this flag would pick the first integrated bundler (or install / try to choose Parcel or the bundler from the `.piralrc` file), however, it could be also just picked `--bundler webpack`: If not installed a plugin with that name will be resolved (`piral-cli-webpack`).
Misunderstanding that all commands are compiled using webpack in the same way.
So, following your instructions, re-use the `0.11.7-pre.1433` version, and found that the third-party (e.g., redux) shared dependencies are not excluded, and are included in the bundle package of the shell application and the pilet application:
`app-shell package.json`
```json
{
  "name": "app-shell",
  "dependencies": {
    "redux": "latest"
  },
  "pilets": {
    "externals": [
      "redux"
    ]
  }
}
```
`pilet package.json`
```json
{
  "name": "sample-pilet",
  "dependencies": {
    "redux": "latest"
  },
  "piral": {
    "comment": "Keep this section to use the Piral CLI.",
    "name": "app-shell"
  }
}
```
Search for the redux code snippet in the browser, that still included in the bundle package of the shell application and the pilet application. Screenshot:
![image](https://user-images.githubusercontent.com/5674761/85202444-154b8500-b339-11ea-8103-2d1aabdddb7a.png)
Here is the [sample](https://github.com/carvinlo/piral-sample)

**Comment by FlorianRappl** [comment]
No, everything is fine there. Apparently, you did not upgrade your pilet. Externals from the shell end up as peer dependencies in the pilet.

I'm not sure how you created that pilet, but from the package.json it does not seem to be created by `pilet new` using a valid Piral instance. 

Compare [your pilet's package.json](https://github.com/carvinlo/piral-sample/blob/master/packages/sample-pilet/package.json) with any other, [for example this one](https://github.com/piral-samples/piral-admin-template/blob/master/packages/pilet-status/package.json).

**Comment by FlorianRappl** [comment]
I think there is a misconception what

```ts
  "pilets": {
    "externals": [
      "redux"
    ]
  }
```

does. These are instructions used for `pilet new` and `pilet upgrade`. They have no runtime impact. Otherwise we could not build a pilet without having the shell installed - which you totally can do. We don't need / have to look at the shell at all.

**Comment by carvinlo** [comment]
Got it, you are the most responsive developer I have ever seen, and thank you for your patience and precious time for such a detailed answer. Thanks again!

**Comment by FlorianRappl** [comment]
Always :beers:!

To confirm I've added `redux` to the peer dependencies (as if we've run `pilet upgrade` etc.).

The result:

```plain
flo@DESKTOP-NODE:/mnt/e/Code/exps/piral-sample/packages/sample-pilet$ yarn build
yarn run v1.9.2
warning package.json: No license field
$ pilet build
Bundle pilet ...
Hash: 5f6c5193f93fcc7c686c
Version: webpack 4.43.0
Time: 646ms
Built at: 06/20/2020 3:26:08 PM
   Asset     Size  Chunks             Chunk Names
index.js  1.9 KiB    main  [emitted]  main
Entrypoint main = index.js
[0] multi ./node_modules/piral-cli-webpack/lib/set-path ./src/index.tsx 40 bytes {main} [built]
[./node_modules/piral-cli-webpack/lib/set-path.js] 435 bytes {main} [built]
[./src/index.tsx] 98 bytes {main} [built]
[redux] external "redux" 42 bytes {main} [built]
✨  Pilet built successfully!
Done in 3.36s.
```

Most importantly, we now get this line:

```plain
[redux] external "redux" 42 bytes {main} [built]
```

So it should be all fine.

Changed *package.json*:

```json
{
  "name": "sample-pilet",
  "version": "1.0.0",
  "description": "",
  "keywords": [
    "pilet"
  ],
  "dependencies": {
    "app-shell": "*",
    "piral-core": "0.11.7-pre.1433",
    "redux": "latest",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "react-router": ">=5.0.0",
    "react-router-dom": ">=5.0.0"
  },
  "peerDependencies": {
    "redux": "latest"
  },
  "devDependencies": {
    "@types/react": "^16.8.2",
    "@types/react-dom": "^16.8.0",
    "@types/react-router": "^5.0.0",
    "@types/react-router-dom": "^5.0.0",
    "piral-cli": "0.11.7-pre.1433",
    "piral-cli-webpack": "0.11.7-pre.1433"
  },
  "scripts": {
    "start": "pilet debug",
    "build": "pilet build",
    "upgrade": "pilet upgrade"
  },
  "main": "dist/index.js",
  "files": [
    "dist"
  ],
  "piral": {
    "comment": "Keep this section to use the Piral CLI.",
    "name": "app-shell"
  }
}

```

Hope that helps!

By the way: Improved support for all this is coming with 0.11.7. We will continue investing in the mono repo use case and we will make it simpler / with more output (or checks) available. Stay tuned!

**Comment by carvinlo** [comment]
The information you provided is very helpful. I also verified that piral is working well as expected, and continue to pay attention to the new features of piral, thank you!
