### ISSUE TITLE
Support option to publish pilet from an NPM registry

### ISSUE THREAD

**Issue by lamson** [smapiot/piral#239]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Currently, `pilet publish` command allows us to publish a local `pilet.tgz` to a Feed.
Example: `pilet publish <path-to-the-tarball>`

I'd like to suggest supporting an option `--from` to allow publishing `pilet.tgz` from local OR from an NPM registry.

`pilet publish <path-to-pilet.tgz> --from local` (this is already supported)
`pilet publish --from https://registry.npmjs.org/<package-name>/v/<package-version>`

## Background

[Provide any additional background for the feature, e.g., why is the current solution insufficient, what problem will it solve, etc.]

We have many pilet packages in NPM, but not all of them are needed to publish to the Feed. Providing this option to allow us having a separate job to "publish a pilet to Feed" given any version as long as it's available in NPM registry.

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
Landed in `develop` and the preview (`@next`) version.

I'll need to exploratory test this, but looks fine so far.
