### ISSUE TITLE
`pilet upgrade` Sets Some Dependencies to Latest

### ISSUE THREAD

**Issue by nolanlocke** [smapiot/piral#247]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
This is reproducible in the [piral-admin-template monorepo example](https://github.com/piral-samples/piral-admin-template)
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version
* node 12.16.2
* yarn 1.22.4
* Reproduced in both piral-cli@latest and piral-cli@next

## Description
Calling `pilet upgrade` in a monorepo and pointing to a local folder will currently update a number of dependencies in the pilet to "latest" rather than using the app shell's versions
* Unsure if this is monorepo specific, but is how i came across the issue.

## Steps to Reproduce
* Run `pilet upgrade ../portal` from one of the pilet folders in the [piral-admin-template monorepo example](https://github.com/piral-samples/piral-admin-template)

## Expected behavior
For dependencies/devDependencies/peerDependencies to be updated to the app shell's versions.
From a discussion with Florian in the community chat:

> ...the dependencies coming from the app shell should be taken accurately (e.g., if the app shell states "foo": "^1.2.3", and foo is currently installed in version 1.2.8 in the app shell, then it should read "foo": "1.2.8" in the pilet)

## Actual behavior
* Dependencies including `@dbeining/react-atom`, `@libre/atom` are being updated to "latest" in devDependencies

**Comment by FlorianRappl** [comment]
Related #250.

**Comment by FlorianRappl** [comment]
Available in `develop` and the preview (`@next`) version.
