### ISSUE TITLE
Errors raised by WebSocket

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#249]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral-cli@0.11.5
IE11
piral-cli-webpack@0.5.3

## Description

The page refresh is always triggered by webpack-dev-server. Under IE11, [const ws = new WebSocket(updateTarget);](https://github.com/smapiot/piral/blob/f6cb7c22c8a663f0c6ebc8c6ab05f852a6748b9b/src/framework/piral-core/src/helpers.tsx#L136) will trigger a `read ECONNRESET` error after the page is automatically refreshed.

## Steps to Reproduce

1. Debug pilet in ie11
2. Manually refresh the ie browser or modify the code to trigger the page to automatically refresh
3. webpack-dev-server crashed and output an error in the console:
```
Unhandled 'error' event
Error: read ECONNRESET
```
4. Works well on chrome browser

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

If comment out this [socket](https://github.com/smapiot/piral/blob/f6cb7c22c8a663f0c6ebc8c6ab05f852a6748b9b/src/framework/piral-core/src/helpers.tsx#L136) code, it works well on ie11.
When I replace WebSocket with sockjs-client to be compatible with IE11([the code](https://github.com/smapiot/piral/compare/develop...carvinlo:patch-1)), it works fine on chrome and ie11. Is this feasible?

**Comment by FlorianRappl** [comment]
Hm this is not a piral issue, but rather a piral-cli-webpack.

Can you raise the issue there? I cannot move the issue between different organizations.

**Note**: The new piral-cli-webpack will have a different design and behave anyway different. This is, however, subject of #237.

**Comment by carvinlo** [comment]
I raised the issue here [#21](https://github.com/FlorianRappl/piral-cli-webpack/issues/21). :smile_cat:
