### ISSUE TITLE
Sanity Check for Multi-Pilet Debugging

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#250]
## Description

When starting a multi-pilet debugging session (e.g., in a monorepo) we only take the first pilet as role-model to determine the app (Piral instance) and have assumptions about the shared dependencies etc.. However, this may be false. We should check all pilets and print warnings if they are different regarding

- the used app shell
- the shared dependencies
- anything else that is may be changed with the app shell version

## Background

Discussed in #241 - I guess such issues would not appear if warnings would be printed under special conditions.

## Discussion

Are there any other conditions that should be checked?

**Comment by nolanlocke** [comment]
It would also be nice to define which mocks to use for kras, as it is also exclusively using the first pilet's mocks

**Comment by FlorianRappl** [comment]
Yeah this is a good point.

We thought about that a bit, but the last thing we wanted is extensive configuration. Nevertheless, I think we should just use *all* available mocks (all = from all found pilets).

Why? Because even if there are duplicates these should not matter (and we could use / improve kras to filter out duplicates). If there are mocks that should not be part then excluding them is also much simpler (via the mock server management website) than adding them - plus these scenarios should be less likely.

Do you agree @nolanlocke ?

**Comment by carvinlo** [comment]
> * the shared dependencies

Does this include scanning for dependencies that are not explicitly shared between the app shell and the pilet (including third-party dependencies)? The current idea is to use webpack-bundle-analyzer to scan the app-shell to get the results, visually check the relatively large dependencies and then summarize them in pilets.externals.

**Comment by FlorianRappl** [comment]
> Does this include scanning for dependencies that are not explicitly shared between the app shell and the pilet (including third-party dependencies)?

No, it pretty much just makes sure that latest app shell settings are picked up.

**Comment by nolanlocke** [comment]
> Yeah this is a good point.
> 
> We thought about that a bit, but the last thing we wanted is extensive configuration. Nevertheless, I think we should just use _all_ available mocks (all = from all found pilets).
> 
> Why? Because even if there are duplicates these should not matter (and we could use / improve kras to filter out duplicates). If there are mocks that should not be part then excluding them is also much simpler (via the mock server management website) than adding them - plus these scenarios should be less likely.
> 
> Do you agree @nolanlocke ?

I agree! This lines up with my expectations

**Comment by FlorianRappl** [comment]
Landed in `develop` and in the preview. All mocks are picked up.
