### ISSUE TITLE
Add pilet lifecycle listeners in piral instance

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#252]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

As a shell application, I'd like to be informed when a pilet gets unloaded, so I can perform cleanup actions.

## Background

In the current situation, I am only informed when a pilet is about to be loaded (via the api extender).

## Discussion

Using the api extender is not a very intuitive place to listen for load events, so it might be a good idea to have listeners added via `createInstance`

**Comment by FlorianRappl** [comment]
Hi @SantoJambit did you have a look at the preview version of 0.11.7. In the changelog we have added:

> Added the unload-pilet event when injectPilet is used

Is this what you need? Your plugins and/or shell can use this to perform the cleanup. The typings are here: https://github.com/smapiot/piral/blob/develop/src/framework/piral-core/src/types/utils.ts#L54

```ts
export interface PiralUnloadPiletEvent {
  /**
   * The name of the pilet.
   */
  name: string;
  /**
   * The version of the pilet.
   */
  version: string;
}
```

Hope that helps!

**Comment by SantoJambit** [comment]
Yes, that seems to work. Thanks.

Though I wonder if the version is correct. You pass in pilet.version from the newly injected pilet, so would that not be the new version rather than the old version?

I don't know any use-case for version right now, but I would imagine that it causes some confusion if this is not named "nextVersion"

**Comment by FlorianRappl** [comment]
> I don't know any use-case for version right now, but I would imagine that it causes some confusion if this is not named "nextVersion"

Well I think it should be removed.

**Comment by SantoJambit** [comment]
That's alright with me.

Tested it successfully in our sample project: https://github.com/piral-samples/piral-core-redux-saga-demo/commit/fa4a2e0902d3eff3affe5bb6da2da3e750d27d57
