### ISSUE TITLE
Support scoped piral-cli plugins

### ISSUE THREAD

**Issue by kingb12** [smapiot/piral#254]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Currently, only piral-cli plugins with empty/no scope are supported by the piral-cli. Requesting that the piral-cli additionally support scoped plugins following the  `@<any-scope>/piral-cli-<name>` naming convention. 

## Discussion

Pros: Makes support for publishing custom, internal plugins easier without interfering with the standard approach. 

Cons: this flexibility might discourage sharing of otherwise useful plugins and proliferation of custom approaches. In our case, we deviated from the normal feed API when building our own feed service and are building this plugin to support some of our custom features.

**Comment by FlorianRappl** [comment]
Landed in `develop` and the preview version `@next`.
