### ISSUE TITLE
`pilet-debug` with webpack uses first emitted chunk

### ISSUE THREAD

**Issue by rtruong** [smapiot/piral#258]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral@0.11.7
WSL-Ubuntu 18.04

## Description

When running in debug mode (i.e., `pilet debug`), if the Webpack build emits more than one chunk, it tries to load the wrong chunk as the pilet. More specificially, it tries to load the first chunk emitted by the Pilet's webpack build.

For example, if we use Font Awesome 4, the chunks emitted include font files. So, when running `pilet debug`, it ends up trying to load an `.eot` file as the pilet.

Another example, if we do code splitting with `React.lazy()` and `import()`, the chunks emitted are `0.index.js` and `index.js`. In that case, it tires to load `0.index.js` as the pilet, which is incorrect.

## Steps to Reproduce

1. Clone git@github.com:rtruong/pilet-issue-20200626-1.git
2. Run `yarn start`
3. Open browser to http://localhost:1234
4. Observe that Pilet did not load due the following error in the console:
```
Uncaught SyntaxError: Invalid or unexpected token
Invalid module found. pilet-issue-20200626-1
```
5. Observe that the call to http://localhost:1234/$pilet-api responded with:
```
{
  "name": "pilet-issue-20200626-1",
  "version": "1.0.0",
  "link": "/$pilet-api/0/674f50d287a8c48dc19ba404d20fe713.eot",
  "hash": "68372effb8d733c5608b",
  "requireRef": "pr_piletissue202006261",
  "noCache": true
}
```

1. Clone git@github.com:rtruong/pilet-issue-20200626-2.git
2. Run `yarn start`
3. Open browser to http://localhost:1234
4. Observe that Pilet did not load due the following error in the console:
```
Invalid module found. pilet-issue-20200626-2
```
5. Observe that the call to http://localhost:1234/$pilet-api responded with:
```
{
  "name": "pilet-issue-20200626-2",
  "version": "1.0.0",
  "link": "/$pilet-api/0/0.index.js",
  "hash": "c4745f2a56893babc6c4",
  "requireRef": "pr_piletissue202006262",
  "noCache": true
}
```

## Expected behavior

That the Pilet loads, and that the `link` returned by `/$pilet-api` is `index.js` instead of the first chunk emitted by Webpack.

## Actual behavior

The Pilet does not load, and the `link` returned by `/$pilet-api` is the first chunk emitted by Webpack.

**Comment by FlorianRappl** [comment]
Thanks for the report - we'll fix this asap!

**Comment by FlorianRappl** [comment]
Patch available in `develop` and the preview package `@next`.
