### ISSUE TITLE
[Contribution Wanted] Logo

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#27]
The current logo is just a placeholder. Before going really "public" (i.e., declaring this thing - API - stable and doing more blog posts etc.) we want to come up with something really good.

Does anyone have some good idea? Is someone interested in "sponsoring" / "contributing" a cool logo design? Any kind of concepts or sketches would be much appreciated.

**Comment by mirzazulfan** [comment]
Hi @FlorianRappl what about this logo? give me your feedback.
![PIRAL](https://user-images.githubusercontent.com/36124339/61766947-da7d5c00-ae0c-11e9-9f3f-b26dae8e519e.png)

**Comment by FlorianRappl** [comment]
Hi @mirzazulfan that looks promising. Great work! Could you also make one in green?

What are your thoughts @lschoett @iotcloudarchitect ?

**Comment by mirzazulfan** [comment]
What do you think? If you like it, i'll send all files. Regard!
![piral 2](https://user-images.githubusercontent.com/36124339/61774945-2090ea80-ae22-11e9-8298-f972dd013a17.png)

**Comment by lschoett** [comment]
Hi @mirzazulfan, good work, thanks. Do the individual parts of the logo carry a specific meaning?

**Comment by mirzazulfan** [comment]
Sure. I combine the initials p with "O" in the middle as a portal. Thanks.

**Comment by FlorianRappl** [comment]
Available in the preview.
