### ISSUE TITLE
Add and Update Missing Documentation Pieces

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#275]
## Description

* New guidelines
  - Extending Pilet loading, e.g., for using SystemJS with top-level importmaps
  - Using a different bundler,e.g., Parcel

* New content
  - Piral Inspector (in Tools)
  - VS Code Extension (in Tools)
  - Available usage / development paths (in Reference)
  - Scaffolding techniques (in Reference)

* Update Content
  - Set default bundler -> Webpack
  - How to configure / extend Webpack
  - Describe the options of the `.piralrc` file

## Background

Follow up on #206.

## Discussion

Anything else missing?

**Comment by iotcloudarchitect** [comment]
I'm taking care for the documentation of the Piral Inspector.

**Comment by int0x81** [comment]
I will write a reference for the scaffolding techniques

**Comment by FlorianRappl** [comment]
I will write the ref on the `.piralrc` file. I will also mention the file in the Piral CLI guideline.
