### ISSUE TITLE
Integrate Improved Full Text Search in the Documentation

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#277]
## Description

Right now we use a quite simple heuristic for creating a keymap of the existing content. This should be improved and essentially created in a maintenance-free way (right now some routes need to be specified manually...).

Ideally, instead of using simple keywords sensitive to language tokens we should support a proper full text search using context information, too.

## Background

This is a follow-up on #206.

## Discussion

Which solution should we use? Our requirements are:

- The indexing can be done statically (i.e., at compile-time) and then re-used at runtime (loaded asynchronously)
- It should be able to be context-aware

Our tendency right now goes to using [FlexSearch.js](https://github.com/nextapps-de/flexsearch). Any other suggestions?

**Comment by lamson** [comment]
Some options to consider:
- https://lunrjs.com/
- http://elasticlunr.com/
- https://www.algolia.com/

**Comment by FlorianRappl** [comment]
Available in the documentation branch. So far went with flexsearch.

Pro: Just works in CSR
Con: Requires the docs (around 10 MB) to load ...

Algolia would have been nice, but its paid only. The free plan is not good enough for our purposes. With the other two I have some (bad) experiences; they work in simple scenarios, but for what we want they are not good enough.

I'll see if I can optimize the index (maybe even lazy load by section) in the future.
