### ISSUE TITLE
piral-cli-webpack Module parse failed

### ISSUE THREAD

**Issue by burakakca** [smapiot/piral#292]
# Bug Report
## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

OS Name:     Windows
 OS Version:  10.0.18363

[Package Version, OS, Browser, ...]

piral --version : 0.11.8
chrome version : 84.0.4147.89

## Description

I added the piral-vue plugin to piral and created a new pilet, and I created a component named sample.vue in this pilet when I try to debug it, the piral-cli-webpack gives an error but the piral-cli-parcel doesn't give an error

[Description of the bug]

![webpack error](https://user-images.githubusercontent.com/56919004/88183903-bd0aea00-cc3a-11ea-96b3-9d3e2da26aa1.png)

MWE : https://github.com/burakakca/piral-webpack-error

**Comment by FlorianRappl** [comment]
Well, this is hardly a bug. So far it seems like you did not add anything to webpack for allowing vue.

Remember that when you choose webpack you need to deal with the ecosystem. Parcel is different in that regard.

Can you add more infos why you think this is a bug (e.g., did you configure webpack properly)?

**Comment by FlorianRappl** [comment]
Also the error is quite explicit that you may need an appropriate loader.

The [Vue loader documentation](https://vue-loader.vuejs.org) may be helpful for you!

**Comment by burakakca** [comment]
I think I had a missing configuration , thanks
