### ISSUE TITLE
Extend Piral CLI to update a pilet with local App Shell

### ISSUE THREAD

**Issue by iotcloudarchitect** [smapiot/piral#293]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Extend Piral CLI for "pilet" command with parameter "--source" which points to a locally available tarball of a specific Piral version in order to update a locally available pilet in development or testing phase.

Example:
pilet upgrade --source ../myPiral/dist/develop/myPiral-0.2.7.tgz

## Background

As a Pilet Developer, I would appreciate the possibility to update a pilet with a custom Piral package (App Shell) for testing purpose.
Currently, it is only possible to update to the latest or a specific Piral version which must be already published to npm.

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
This is already possible. The `target-version` can also be used with a local file path.
