### ISSUE TITLE
Uploading a file that is bigger than axios's default max content length results in a silent 0065 error from `pilet publish`.

### ISSUE THREAD

**Issue by kingb12** [smapiot/piral#294]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Using `yarn 1.22.4`, with `piral-cli@0.11.8` 

## Description

Uploading a file that is bigger than axios's default max content length results in a silent 0065 error from `pilet publish`.

## Steps to Reproduce

1. In a sample pilet, add a random file of significant size (this adds a 30mb file to `stuff/`, which will need to be included in `files` in package.json: `head -c 30000000 /dev/urandom | gzip -1 > stuff/30m.gz`
2. Attempt publishing: will fail with an error message like so:

```bash
yarn pilet publish --fresh --url $FEED_URL --log-level 4 --api-key 1234123412341234 --ca-cert ops/certs/cacert.pem
yarn run v1.22.4
$ /Users/bking/workspace/my-cool-app/node_modules/.bin/pilet publish --fresh --url https://feed-eng.apps.dapt.to/api/v1/pilet/dev --log-level 4 --api-key 1234123412341234 --ca-cert ops/certs/cacert.pem
[1:29:55 PM]: Reading configuration ...
[1:29:55 PM]: [0003] Checking if certificate exists.
[1:29:55 PM]: [0003] Reading certificate file "cacert.pem" from "ops/certs".
[1:29:55 PM]: [0003] Getting the tgz files ...
[1:29:55 PM]: [0003] Detected "--fresh". Trying to resolve the package.json.
[1:29:55 PM]: Triggering pilet build ...
Bundle pilet ...
✨  Built in 7.77s.

dist/App.bba56d04.js.map                   688.67 KB     94ms
dist/App.bba56d04.js                       221.65 KB    6.65s
dist/index.js.map                            6.96 KB      2ms
dist/index.js                                4.07 KB    7.62s
dist/react.4980d444.external                     0 B      3ms
dist/react-dom.29a0c252.external                 0 B    148ms
dist/react-router-dom.c92199c3.external          0 B     42ms
Bundle breakdown saved in report: /Users/bking/workspace/my-cool-app/dist/report.html
✨  Pilet built successfully!
[0000] Using feed service "https://feed-eng.apps.dapt.to/api/v1/pilet/dev".
🚨  [0065] Failed to upload via HTTP: [object Object].
⚠️  [0062] Could not upload "bktest2-0.1.6-236.tgz" to feed service.
🚨  [0064] Failed to upload some pilet(s)!
Codes Reference: https://docs.piral.io/code/search
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior

Either successful publishing of the large pilet, or rejection with a message about packaged size. 

## Actual behavior

Axios never makes the request as the pilet exceeds its default `maxContentLength`, which gets logged out with the same error as un-reachable host (0065)

## Possible Origin / Solution

I fixed this in my own version by adding a `maxContentLength: Infinity` to the AxiosRequestConfig in `postFile` in `http.ts`. Wanted to open an issue as this might have ramifications for the response to that call, and not sure if Piral wants to support arbitrarily large pilets.

Would also be nice if the logging here: `Failed to upload via HTTP: [object Object].` could be improved, would probably help diagnose similar issues (or even just clarify known `0065` issues to the end-user. Looks like there is something to log but it gets stringified into "Object"

Let me know if I'm missing anything, thanks all!

**Comment by FlorianRappl** [comment]
Yeah good points.

1. In general an arbitrary large pilet is not wanted. Our limit recommendation is set to 16 MB (see https://docs.piral.io/reference/specifications/pilet-specification).
2. Nevertheless, since custom implementations may be more relaxed about this we shouldn't put any constraints in the CLI.
3. Indeed, the error message should be improved. Maybe a simple `log('failedHttpPost_0065', JSON.stringify(error.request, undefined, 2));` could help here.

Do you want to contribute your fix via a PR? Much appreciated!

**Comment by kingb12** [comment]
Sounds good! I can try to have one ready by the end of today

**Comment by FlorianRappl** [comment]
Sounds superb - thanks @kingb12 !

**Comment by kingb12** [comment]
Created one here! https://github.com/smapiot/piral/pull/296

**Comment by FlorianRappl** [comment]
Awesome job @kingb12 ! Thanks a lot for the contribution, much appreciated :rocket:

Landed in `develop` and should be available in the next preview `@next`.
