### ISSUE TITLE
Does Piral support Nextjs Framework?

### ISSUE THREAD

**Issue by xmkan** [smapiot/piral#302]
# Issue Templates

Please use one of the following templates to create your issue:

Hi, I just wish to check if Piral support Nextjs Framework and is there any example codes for it?

**Comment by FlorianRappl** [comment]
Hi sorry the issue tracker is not really meant for questions (see also the pinned issue #123).

Please use [StackOverflow](https://stackoverflow.com/questions/tagged/piral) or [our chat on Gitter](https://gitter.im/piral-io/community).

Next.js is a mix of server-side w. client-side. The React components you can just re-use (and that is answered on the [docs](https://docs.piral.io/guidelines/tutorials/20-migrate-app#what-about-next.js), too), but the concept is different. Surely, you can do a mix.

Hope that helps.
