### ISSUE TITLE
The style file I added from pilet does not affect piral

### ISSUE THREAD

**Issue by damon3465** [smapiot/piral#304]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, OS, Browser, ...]
browser : latest
1.0.0-pre.1721

## Description

[Description of the bug]
I add the style files I created in the pilet as "import" ./mystyles.scss "in the index.tsx file and I want this pilet to work in more than one piral. it works when I debug pilet, but when I publish my pilet, my style file is not visible in piral. Also i'm using piral-cli-webpack

MWE Repo : https://gitlab.com/damon3465/mwe-piral

**Comment by burakakca** [comment]
I did the sample with piral-cli-parcel worked. Is there a need to configure for webpack?

**Comment by FlorianRappl** [comment]
> Is there a need to configure for webpack?

In general yes, but for this particular task there should not be any need. We'll look into this.

**Comment by FlorianRappl** [comment]
A fix is available in `develop` and the preview `@next`.
