### ISSUE TITLE
HMR caches the react lazy component

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#305]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral-cli@latest
piral-core@latest
chrome browser
macos

## Description

In the pilet debug mode, HMR caches the React lazy component, modifying the component will not update it, and will enter the not_found error component.
This is the [demo](https://github.com/carvinlo/hmr-demo) repository.

## Steps to Reproduce

1. [First Step]
2. [next step...]

## Expected behavior

[What you expected to happen]

## Actual behavior

modifying the component will not update it.

## Possible Origin / Solution

The page components can be updated in real time by enabling the forced page refresh mode through `sessionStorage.setItem('dbg:hard-refresh', 'on');`.

**Comment by FlorianRappl** [comment]
That sounds rather like a Webpack issue.

Since we did not configure anything here I assume that this is general and nothing specific to Piral or the Piral CLI. Any idea why this should be related to Piral?

**Comment by carvinlo** [comment]
Oh my bad. and thank you for the reply! :)
The entry of pilet has been updated。This problem has not been solved yet, I don't know if it is caused by React.lazy and Suspense or webpack cache.
![image](https://user-images.githubusercontent.com/5674761/89732876-2a64aa80-da84-11ea-80e0-d28b507e7d53.png)

There is a question about piral, When hmr triggers [injectPilet](https://github.com/smapiot/piral/blob/be0f6d54a50d8093aa25997ef800c1dbccd12562/src/framework/piral-core/src/helpers.tsx#L160), it will immediately render the not_found error component. In some scenarios, you need to redirect to the 404 page in the not_found error component.
![image](https://user-images.githubusercontent.com/5674761/89733113-d8bd1f80-da85-11ea-9e81-1160dacf66e1.png)
> Because the layout of the not_found error component is different from the 404 page.

The result of this is that when the page is modified, it will immediately jump to the 404 page. Is there any way to stop this behavior?

**Comment by FlorianRappl** [comment]
> The result of this is that when the page is modified, it will immediately jump to the 404 page. Is there any way to stop this behavior?

Unfortunately not really. You could choose to use a [full refresh](https://docs.piral.io/tooling/piral-inspector#full-refresh-on-change) instead of the injection.

**Comment by carvinlo** [comment]
It's really helpful, thanks!

**Comment by carvinlo** [comment]
Just updated the latest code and found that this problem has been fixed. May be affected by [#304](https://github.com/smapiot/piral/commit/eae91bb9dc5e9b3b45e615cad7ce56e2ad390468).

**Comment by FlorianRappl** [comment]
It has not been directly affected by #304 @carvinlo . Rather webpack not removing chunks, which is why chunks are reset now in the main bundle - this is a responsibility of `pilet-webpack-plugin` (which has been improved in that area).
