### ISSUE TITLE
Use Webpack 5

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#313]
## Description

Webpack 5 brings some really nice enhancements to Webpack (e.g., revealing the hashes at runtime). Together with some state of the art decisions it would be nice to move to Webpack 5 once shipped.

Right now its still in beta and not done yet.

## Background

Especially things like the `import-maps-webpack-plugin` suffer from Webpack's choices regarding bundle reflection. Together with other PoCs / integrations we want to provide Webpack 5 makes sense as a whole - but not before its "done".

## Discussion

Should there be also a `piral-cli-webpack` for Webpack 4 specifically? Does it make sense to upgrade? We'd love to know.

**Comment by carvinlo** [comment]
> Should there be also a piral-cli-webpack for Webpack 4 specifically?
The plugin ecology of webpack needs time to upgrade. In a period of time, support for the 4.x version of webpack is still needed.
Thanks!

**Comment by usman087** [comment]
How piral 's loading strategy can be improved with webpack 5 module federation? Any thoughts?

**Comment by FlorianRappl** [comment]
Potentially not much. Piral is all about dynamically loading microfrontends (i.e., you actually don't know the host or the remotes), whereas module federation is mostly about static loading (you actually import from modules that you mark up front and share the build manifest to reuse previously given chunks).

We definitely want to include the ability to use WP5 MF - just not sure if its just an opt-in (most likely) or can give any benefits to change the strategy to pin the tooling (right now you can actually do whatever, any kind of bundler works, even without a bundler / predefined tooling you can make it work).

That all being written we don't know for sure until we experiment with it more heavily.

**Comment by usman087** [comment]
Thank you,  I saw you changed webpack5 upgrade to milestone 0.12.4 which is scheduiled for  October 28, 2020 if i understand correctly. Can you confirm if it is on track.

**Comment by FlorianRappl** [comment]
Right now we are confident that 0.12.4 will be released eo October.
