### ISSUE TITLE
Could the 'piral declaration' command support script files as the 'entry' parameter

### ISSUE THREAD

**Issue by M4sterShake** [smapiot/piral#316]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Firstly, thanks a lot for creating this package! Its the mosts fully featured while unobtrusive microfrontend framework I've seen.

One issue I've had though, is that I'm unable to pass a script file to the ```piral declaration``` command. It would be great if running ```piral declaration ./path/to/index.tsx``` would generate pilet API typings based on that script file. 

## Background

Currently the entry parameter of ```piral declaration``` expects a path to a directory that contains a package.json, which in turn has an app field that points to an index.html, which in turn points to the script file that is the entry point of the Piral instance. 

In some circumstances (such as when using create-react-app for your Piral instance) the index.html file doesn't have a reference to the the entry point script. At least not until the app is built, at which point the index.html points to the a .js file with no type information. In this case there isn't a simple way to generate type information for the pilet API.

There is a workaround whereby you can create a dummy package.json, which points to a dummy html file which points to the index.tsx but it would be much nicer if you could just pass the index.tsx file to ```piral declaration``` directly.

**Comment by FlorianRappl** [comment]
Landed in `develop` and the preview.
