### ISSUE TITLE
Add ability to set and retrieve "state" during the sign in redirect and callback

### ISSUE THREAD

**Issue by nolanlocke** [smapiot/piral#318]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Currently unable to retain original. This is typically solved using the [state](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) param on the authorize call, but this is currently hidden behind the setupOidcClient function.
Have spoken to Florian about this briefly and it would be useful to expose this in some way.

## Background

When signing into our auth, we lose reference to the location we came from, so we will only ever be able to go to the hardcoded appUri specified in the setupOidcClient call

**Comment by FlorianRappl** [comment]
Thanks for bringing this up and for providing a fix!
