### ISSUE TITLE
Pilet Validate Bundle Size

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#323]
## Description

For the `pilet validate` command we should add a validator named `pilet-stays-small`. It will be configured with a numeric value, which indicates the maximum size of the pilet's main bundle in kB.

By default, this will be set to `50`. Setting `0` will disable the rule. All other non-positive numbers (i.e., any string that is not a positive number) will result in a warning (+ treat it as the default value).

For identification of the pilet's main bundle size the pilet will be build using `pilet build`. The main bundle is identified by the same algorithm that is used by a feed service (`main` field of the *package.json*).

## Background

Pilets can grow quite large (depending on bundled dependencies even in the MB range). We actively advice to use bundle splitting to keep the main bundle really small and focused (it should only care about the setup, i.e., the connection between the (lazy loaded) components and the app shell). However, with a proper validation this advice would be cemented even further.

## Discussion

Are these defaults okay? Should we add / change / remove something from this feature? Would it be better in form of a plugin - or is it okay to be directly part of the `piral-cli` package?

**Comment by FlorianRappl** [comment]
Landed in `develop` and the preview `@next`.

**Comment by carvinlo** [comment]
Hi, this is a very useful detection function, but I have a question, the `[main](https://github.com/smapiot/piral/blob/fe5379d49d1992767f3edacf4098e3613386a71e/src/tooling/piral-cli/src/rules/pilet-stays-small.ts#L60)` value here is the package.json from the [shell application](https://github.com/smapiot/piral/blob/fe5379d49d1992767f3edacf4098e3613386a71e/src/tooling/piral-cli/src/common/package.ts#L485), shouldn’t it be the main field from the pilet’s package.json?

**Comment by FlorianRappl** [comment]
How is this question related to the given validator @carvinlo ? The code snippet you linked there is about retrieving the full info for the validator. Part of that info is the relevant app shell, as it sets the validator settings.

The app shell is not at all related to the `main` field of the pilet's package.json. Its given via `piral.name`, or alternatively, via the CLI override.

**Comment by carvinlo** [comment]
If the main field of the shell application is not configured, the `pilet validate` command will throw an error, which means that the path context of the bundle to be detected is from the main field of the shell application.

**Comment by FlorianRappl** [comment]
Sorry I cannot follow. The main field is not at all used in the given code / in what you are looking for.

Maybe I have a misunderstanding. Why again did you highlight that line?

**Comment by FlorianRappl** [comment]
Yeah I think I get you now. What you wanted to highlight is presumably https://github.com/smapiot/piral/blob/develop/src/tooling/piral-cli/src/rules/pilet-stays-small.ts#L60 such that we use `main` from `appPackage` rather than the pilet's package.json. So if `main` is either `undefined` or pointing to a path that would be valid from the pilet's perspective, the verification will not work.

Indeed, this is a bug. We should fix this with 0.12.3. Do you want to create the issue @carvinlo or should I?

**Comment by carvinlo** [comment]
This is exactly what I want to express, and I apologize for not being able to express the problem clearly.
I hope you can fix this defect, because it involves some common code, so you will be more aware！

**Comment by FlorianRappl** [comment]
> This is exactly what I want to express, and I apologize for not being able to express the problem clearly.

No problem was on my side. I did not see immediately what this was about. Now its clear.

Do you want to create the issue for tracking it or should I?

**Comment by carvinlo** [comment]
[#329](https://github.com/smapiot/piral/issues/329)
