### ISSUE TITLE
Support package.json template in `pilet new` command

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#330]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Using `app-shell/package.json/pilets/files` to customize the pilet scaffolding is already very flexible, but I cannot do more customization when initializing the pilet package.json, such as: `browserslist` or [cz-customizable](https://github.com/leoforfree/cz-customizable) config and [ghooks](https://github.com/ghooks-org/ghooks) config.
Is there something I missed, it is now supported?

## Background

Customize the default configuration of specifications and formats for the pilet project.

## Discussion

If it supports the package.json template, you can also migrate some lengthy dependencies from the package.json of the shell application to simplify the size of the package.json of the shell application.
Extract the package.json template from `app-shell/package.json/pilets/files` before initializing pilet's [package.json](https://github.com/smapiot/piral/blob/fe5379d49d1992767f3edacf4098e3613386a71e/src/tooling/piral-cli/src/apps/new-pilet.ts#L127).

**Comment by FlorianRappl** [comment]
Yes I think this would be a good addition.

So your proposal would be to include a package.json (fragment) as a scaffolding template in files, which would then be placed

- *after* the initial package.json was written (more or less empty, contains name, version, ...)
- *before* we apply the final patch using the infos we have (e.g., adding a `piral` section, necessary `devDependencies` etc.)

But like the final patch we do not overwrite, but use it via a JSON merge.

Is that what you have in mind?

**Comment by carvinlo** [comment]
Right!

**Comment by FlorianRappl** [comment]
Right now we support the `packageOverrides` field in the `package.json/pilets` section.

Support for package.json template files (fragments) will be added, too.

**Comment by FlorianRappl** [comment]
Available in `develop` and in the preview.

Files that target the `package.json` of the pilet are merged into the package's definition.
