### ISSUE TITLE
Allow Overriding `PiletApi`

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#332]
## Description

Right now we can extend the `PiletApi` by using interface merging of TypeScript. The (or one) drawback of this method is that we can only "add" properties, we cannot remove existing ones from the `PiletApi`. As such if we would want to remove `Extension` or `registerPage` from the `PiletApi` we cannot do that (even though functionally, i.e., at runtime, we can).

We want to allow overriding the `PiletApi` as a full. This, of course, should be fully optional.

We want to utilize `dets` for using a different base type as `PiletApi`. By specifying a new root module and interface / type name we could construct the full `PiletApi` from this other type.

Additionally, we'd like to be able to remove certain properties. Not yet sure how to accomplish this, as we'd need to come up with some convention or configuration that would allow doing that.

## Background

Customizing the provided `PiletApi` is one of the strengths of Piral, however, the base API cannot be reduced further, even though this may be desired.

## Discussion

The other way is to extract `registerPage` etc. into `piral-router`, `registerExtension` etc. into `piral-extensions` and the event system into `piral-events`. These would all be part of `piral-ext`, but not be in `piral-core`. While more modular at first, it would also bring some additional challenges.

Additionally, one problem remains: What if I want to use, e.g., `piral-pages`, but I don't want to expose this to the (normal) pilets? Just wrapping would not be so easy as the interface merging would leak.

**Comment by Robbson** [comment]
That's an interesting topic. The easiness of this interface merging supported by TypeScript has been one of my Aha-Moments when I started to write API extensions. All of a sudden the new methods are available everywhere, so yes downsides are to be expected.

> What if I want to use, e.g., piral-pages, but I don't want to expose this to the (normal) pilets?

I don't know exactly what do you mean by that. If you don't expose the piral-pages API to the pilets, how is it going to be used then? Except you register pages in the Piral Instance itself, of course.

**Comment by FlorianRappl** [comment]
> I don't know exactly what do you mean by that.

Sorry - I meant exactly what you wrote then: "Except you register pages in the Piral Instance itself, of course." --> so in this use case you use the plugin, but either you don't extend the API with it (for some reason) or don't want pilets to know about (maybe you strip it out for certain pilets, which you can do).

**Comment by Robbson** [comment]
I wonder if this scenario of having pre-configured pages and routing in the Piral Instance is so useful for the Micro-Frontend pattern. But I get your point: Maybe we only want to use a specific plugin in the Piral Instance and don't want to have Pilets have access to it... e.g. for security reasons.

**Comment by FlorianRappl** [comment]
> I wonder if this scenario of having pre-configured pages and routing in the Piral Instance is so useful for the Micro-Frontend pattern.

The usage makes more sense for wrapping existing APIs, e.g., you want users to register some kind of component which will be used for a page, but you don't want them directly to register pages. You want to wrap it. Now you can wrap the API (`registerPage`) in e.g., `registerMyPage`, but the `registerPage` is actually either not there or should at least not be displayed.

I know its a bit of a stretch goal - which is also why its not yet there, but only a nice addition.

**Comment by FlorianRappl** [comment]
Landed in `develop`.

Documentation on this will follow. It uses special dets tagged comments like `@dets_removeprop` or `@dets_removeclause` to just remove what you want to have unselected.

```ts
declare module 'piral-core/lib/types/custom' {
  /**
   * @dets_removeclause PiletLocaleApi
   */
  interface PiletCustomApi {}
}

declare module 'piral-core/lib/types/api' {
  /**
   * @dets_removeprop getData
   */
  interface PiletCoreApi {}
}
```

The first one removes the `PiletLocaleApi` (if it was added) from the `PiletCustomApi`. The second one removes the `getData` property from the `PiletCoreApi `.
