### ISSUE TITLE
Support for overriding <script> for loading pilet

### ISSUE THREAD

**Issue by lamson** [smapiot/piral#335]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Feature request to support for overriding `<script>` for loading pilet

## Background

We have a pilet that uses the window.onerror() handler, but because our pilets are served from a different origin, the handler only gets invoked with "Script error.". Is it possible for the <script /> tags that get added to the body to load the pilets to set the crossorigin="anonymous" attribute?

https://sentry.io/answers/javascript-script-error/

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
Just because I see it right now.

You can enable `crossOrigin="anonymous"` already if your feed service is providing an integrity (e.g., SHA512) for the microfrontends.

**Comment by lamson** [comment]
Thanks @FlorianRappl 

I tried out the `next` version but couldn't get it to work. 

I found that `getDefaultLoader` caller in `piral-core` didn't provide the `config` in the params. Was it a miss or intended? 

https://github.com/smapiot/piral/blob/develop/src/framework/piral-core/src/helpers.tsx#L68

**Comment by FlorianRappl** [comment]
Have you read the comment that you don't need to wait for this? It's already there - your feed service needs to provide the integrity.

**Comment by lamson** [comment]
Yes, I read it and understood. Our feed service release schedule lagging behind a bit so we're testing this option.

**Comment by FlorianRappl** [comment]
This now landed in `develop` and the preview version. Using the `loaderConfig` property in the configuration you can set the `crossOrigin` value.

Hope that helps (and let me know if you still face some issues with it!) :beers:!

**Comment by lamson** [comment]
Thanks Florian. Specifying `loaderConfig` with `crossOrigin` now set the attribute in include `<script>`
