### ISSUE TITLE
Add custom field to the pilet package.json file for specifying pilet related meta data

### ISSUE THREAD

**Issue by lschoett** [smapiot/piral#34]
# New Feature Proposal

## Description
A custom field should be added to the package.json file. The new field should be optional and transport meta data related to the given pilet. There should not be any content restriction applied to this field.

## Background
Via the feed service, clients can be informed about custom attributes of the available pilets.

**Comment by FlorianRappl** [comment]
How should we name this field? Should we use this from the `piral` section that is already specified in the `package.json`?

My proposal:

```json
{
  // ...
  "piral": {
    // ...
    "data": "Any Value of Any Type Here"
  }
}
```

If placing the field in the section `piral` is okay, but the name (`data`) is not, here are some suggestions:

- `info`
- `custom`
- `apiData`
- `meta`
- `rel`

**Comment by FlorianRappl** [comment]
Ok so current design proposal:

The key will always (to avoid confusions) be called `custom`. It will be appended in the Metadata from a feed service (by spec). It needs to be retrieved from the `package.json` of the pilet, which also refers to it (top-level) via `custom`. Hence `piral` will be left to the Piral CLI alone (which has no impact for the feed service).

**Comment by FlorianRappl** [comment]
Landed in `develop`.

**Comment by FlorianRappl** [comment]
Leaving it open for feedback.

Feedback is possible until 0.6.1 is merged.
