### ISSUE TITLE
Example with Pilet displayed in a modal

### ISSUE THREAD

**Issue by szai0103** [smapiot/piral#355]
Hi all,
piral looks like a very promising and flexible micro apps solution but I still can't get how to display pilets as modal dialogs without routing to another page, so like after clicking on a tile to show the modal dialog. Can you, please provide an example of how exactly should be done?

thx in advance ;)

**Comment by FlorianRappl** [comment]
A pilet is just a package (or microfrontend). It may (and usually will) contain components such as pages or other fragments (navigation items, modal dialogs, ...).

As such I am a bit confused by your question. Why are you routing to a page? How do you want to display a modal dialog? Are you using `piral-modals` for this? How are you using it in a pilet? How is it integrated in your app shell?

Would be great to know where exactly you are stuck.

**Comment by szai0103** [comment]
Thank You so much for the immediate response. I try to use pilets which will be extensions of the data rendered into the app shell. For example in the shell app I have a project list, then after selecting one should become available the extentions belonging to it and then I just don't prefer after clicking on an extension to show data at the same view like it is in the example [here](https://demo-full.piral.io/) for the weather cast.

**Comment by FlorianRappl** [comment]
Hm I'm not sure I get it fully. Have you tried working with `registerModal` and `showModal`?

You'll find more infos on [the documentation page](https://docs.piral.io/plugins/piral-modals).

**Comment by FlorianRappl** [comment]
The relevant parts of the weather app:

```ts
export function setup(app: PiletApi) {
  // ...
  app.registerModal(weatherDialog, WeatherSetupDialog);
}
```

where `WeatherSetupDialog` comes from

```ts
import * as React from 'react';
import { ModalComponentProps } from 'sample-piral';
import { WeatherForm } from './WeatherForm';
import { setupData } from './actions';
import { getLocation } from './utils';

export const WeatherSetupDialog: React.FC<ModalComponentProps<any>> = ({ onClose }) => {
  const info = getLocation();
  return (
    <div className="weather-setup-dialog">
      <h2>
        Setup Weather Location
        <a className="close-modal" onClick={onClose}>
          X
        </a>
      </h2>
      <WeatherForm
        defaultCity={info && info.city}
        defaultCountry={info && info.country}
        getWeather={(country, city) => {
          setupData(country, city);
          onClose();
        }}
      />
    </div>
  );
};
```

Hope that helps!

**Comment by szai0103** [comment]
> ```ts
> import * as React from 'react';
> import { ModalComponentProps } from 'sample-piral';
> import { WeatherForm } from './WeatherForm';
> import { setupData } from './actions';
> import { getLocation } from './utils';
> 
> export const WeatherSetupDialog: React.FC<ModalComponentProps<any>> = ({ onClose }) => {
>   const info = getLocation();
>   return (
>     <div className="weather-setup-dialog">
>       <h2>
>         Setup Weather Location
>         <a className="close-modal" onClick={onClose}>
>           X
>         </a>
>       </h2>
>       <WeatherForm
>         defaultCity={info && info.city}
>         defaultCountry={info && info.country}
>         getWeather={(country, city) => {
>           setupData(country, city);
>           onClose();
>         }}
>       />
>     </div>
>   );
> };
> ```

Thank You, It really helped me. Now I managed to do what I needed.
