### ISSUE TITLE
Invalid response_type parameter in authorization redirect // piral-oauth2 plugin

### ISSUE THREAD

**Issue by HGButtenT** [smapiot/piral#357]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ x] Are you running the latest version?
- [ x] Did you perform a search in the issues?

## Environment Details and Version

piral/core 1.0.0-pre.2093 
piral/oauth2 1.0.0-pre.2093

## Description

After upgrading from 1.0.0-pre.2091 (where the account() function did not work) to the current version, the response_type parameter in the authorization URL (code flow) changed from 'code' (which would work) to 'token'. Due to this change our authorization redirect isn't working anymore. 

## Steps to Reproduce

1. Add piral-oauth2 plugin
2. Add example authorization flow code

```javascript

// index.tsx

import 'piral/polyfills';
import {getUserLocale, renderInstance, setupLocalizer} from 'piral';
import {layout, errors} from './layout';
import {languageDefault, languagesAvailable, loadTranslations} from "./language";
import {createOAuth2Api, setupOAuth2Client} from 'piral-oauth2';

// change to your feed URL here (either using feed.piral.cloud or your own service)
const feedUrl = 'https://feed.piral.cloud/api/v1/pilet/empty';

export const client = setupOAuth2Client({
    clientId: 'clientID',
    clientSecret: 'clientSecret',
    authorizationUri: 'https://oauth2.dev/oauth2/authorize',
    accessTokenUri: 'https://oauth2.dev/oauth2/token',
    redirectUri: ' http://localhost:1234/oauth2/callback',
    scopes: ['openid', 'userid', 'sso'],
    flow: 'code',
    restrict: false
});

export function render() {
    loadTranslations()
        .then((languageData) => {

            renderInstance({
                settings: {
                    locale: setupLocalizer({
                        language: () => getUserLocale(languagesAvailable, languageDefault),
                        messages: languageData
                    })
                },
                layout,
                errors,
                plugins: [
                    createOAuth2Api(client)
                ],
                requestPilets() {
                    return fetch(feedUrl)
                        .then(res => res.json())
                        .then(res => res.items);
                },
            });
        });
}

if (location.pathname !== '/oauth2/callback') {
    if (client.account()) {
        // import('./app').then(({ render }) => render());
        render();
    } else {
        client.login();
    }
}
```
3. Open app shell in the browser: http://localhost:1234/

## Expected behavior

Redirect to the OAuth2 server with the response_type parameter set to 'code'

https://https://oauth2.dev/oauth2/authorize?client_id=clientID&redirect_uri=%20http%3A%2F%2Flocalhost%3A1234%2Foauth2%2Fcallback&response_type=**code**&state=&scope=openid%20userid%20sso

## Actual behavior

Redirect to the OAuth2 server with the response_type parameter set to 'token'

https://https://oauth2.dev/oauth2/authorize?client_id=clientID&redirect_uri=%20http%3A%2F%2Flocalhost%3A1234%2Foauth2%2Fcallback&response_type=**token**&state=&scope=openid%20userid%20sso

**Comment by FlorianRappl** [comment]
Hi @HGButtenT are you sure that `piral-oauth2` is responsible for this behavior here? Keep in mind that `piral-oauth2` is a wrapper around `client-oauth2` (https://www.npmjs.com/package/client-oauth2), so if its something from deep inside the bug should actually be filed in their repository (https://github.com/mulesoft-labs/js-client-oauth2).

The parameter in the redirect URL is determined by the service implementing OAuth 2. As such we need to make sure that the parameters have been correctly transported and that the service is working correctly, too.

**Comment by HGButtenT** [comment]
Hi @FlorianRappl , 

after some further debugging, I believe the problem is located in the function 

```javascript
setupOAuth2Client(config);
```

In version 1.0.0-pre.2091 there was a return statement located directly in the login function of the flow === 'code' part. The login function did return a client.**code**.getUri().

```javascript
    if (flow === 'code') {
        client.code.getToken(location.href).then(function (token) { return (currentToken = token); }, function () { });
        var retrieveToken_1 = function () {
            if (!currentToken) {
                return Promise.reject('Not logged in. Please call `login()` to retrieve a token.');
            }
            if (!currentToken.expired()) {
                return Promise.resolve(currentToken.accessToken);
            }
            return currentToken.refresh().then(function (refreshedToken) {
                currentToken = refreshedToken;
                return currentToken.accessToken;
            });
        };
        return {
            login: function () {
                window.location.href = client.code.getUri();
            },
        [ ... ]
        };
    }
```

In version 1.0.0-pre.2093, the return statement is below of the if / else part and does always return a client.**token**.getUri(), no matter what flow has been chosen. 

```javascript
    if (flow === 'code') {
        client.code.getToken(location.href).then(function (token) { return (currentToken = token); }, function () { });
        retrieveToken = function () {
            if (!currentToken) {
                return Promise.reject('Not logged in. Please call `login()` to retrieve a token.');
            }
            if (!currentToken.expired()) {
                return Promise.resolve(currentToken.accessToken);
            }
            return currentToken.refresh().then(function (refreshedToken) {
                currentToken = refreshedToken;
                return currentToken.accessToken;
            });
        };
    }
    else {
       [...]
    }
    return {
        login: function () {
            window.location.href = client.token.getUri();
        },
        [ ... ]
    };
}
```

**Comment by FlorianRappl** [comment]
A fix has been deployed and is available in the `@next` version ([1.0.0-pre.2094](https://www.npmjs.com/package/piral-oauth2/v/1.0.0-pre.2094)).

It would be superb if @HGButtenT could test this version. Let us know if this fixes the issue. Thanks! 🍻

**Comment by HGButtenT** [comment]
Hey @FlorianRappl , 

thanks again for the fix. This part is working for us now. 

Cheers

**Comment by FlorianRappl** [comment]
Great! Thanks for checking!
