### ISSUE TITLE
Tips for installing piral cli kras@0.11.1 This edition does not exist

### ISSUE THREAD

**Issue by yanduhantan1991** [smapiot/piral#358]
An error occurred while running the command NPM install piral-cli - g:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for kras@^0.11.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'piral-cli'
npm ERR! notarget

**Comment by FlorianRappl** [comment]
Well, it exists: https://www.npmjs.com/package/kras/v/0.11.1

Something is wrong with your setup. Check your NPM proxy or NPM configuration in general.
