### ISSUE TITLE
Provide public feed for Pilets

### ISSUE THREAD

**Issue by lschoett** [smapiot/piral#36]
# New Feature Proposal

## Description

A public feed for Pilets should be available, so that developers who are starting to evaluate and use Piral, have a possibility to host their Pilets for development and testing purposes.

## Background

The standard approach for Piral is that Pilets are loaded from a so-called feed service. When starting with Piral such a feed service is usually not available. To ease the process of evaluating Piral and get started with the first Pilets, a publicly accessible feed service should be available, where developers can perform a simple registration and publish their Pilets into their own dedicated feed.

## Discussion

Some restrictions to the number of Pilets or number of Requests should apply, to keep the efforts of hosting and operating the public feed in a certain limit.

**Comment by FlorianRappl** [comment]
Should be there with the version `0.7`.
