### ISSUE TITLE
Parcel + Lazy loading + css does not clean up css import correctly

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#360]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral 0.12.4

## Description

When building a pilet, where a shared component loads css files and two lazy-loaded components use it (but not the not-lazy ones), parcel moves the css content to be bundled with the index.js, but piral still adds a link to the dynamically loaded js files.

This only seems to happen for pilets, not for the shell. And only if the lazy-loaded component does not import any other css files.

## Steps to Reproduce

1. In a pilet create a component `Shared` that imports an (s)css file.
2. Create a component `A`, which uses `Shared`.
2. Lazy load A in your application
3. Observe:
A file `A.hash.css` is created
The file `A.hash.js` adds this file using `d.createElement("link")`
4. Create a component `B` in the same way as `A` and also lazy-load it
5. Observe:
index.css now contains the css from the shared component
`B.hash.css` is not created
`A.hash.css` will not be created anymore (check by deleting it and rebuild)
The files `A/B.hash.js` still add this their imaginary css files using `d.createElement("link")`, even though they don't exist.

## Expected behavior

The js files should no longer reference the css files, which don't exist.

## Actual behavior

css code has been moved to index, but the components still try to load their own css

## Possible Origin / Solution

As a temporary solution, I imported the `Shared` component in the index file, but that is a hacky solution.

**Comment by FlorianRappl** [comment]
Yeah I'm not sure if this is a Piral issue or rather a Parcel issue. Parcel has some problems with lazy loading w.r.t. common / shared code. This has partially some debugging problems (chunks not updated properly), partially some production problems (triangle issue where common chunks are not derived and end up being just assumed to be loaded, which in some / most cases is not true).

If we can do something about it then I'm all in favor of doing it.

Let's keep it open for investigation.

**Comment by SantoJambit** [comment]
I've tried reproducing this with pure parcel, but it didn't happen there.

**Comment by FlorianRappl** [comment]
How? What is pure Parcel? I don't think you tried the same, because out of the box there are no shared dependencies (and some other things) in Parcel.

Note: When I refer to a bug in Parcel I mean a bug in Parcel's internal handling of files and the system as a whole. I am not referring to the CLI or a specific flow that end-users may or may not experience.

**Comment by SantoJambit** [comment]
I meant, that I set up a normal react app with parcel without piral and did not get that problem. If a pilet is a library in parcel terms, that might explain why it doesn't happen for the shell.

**Comment by FlorianRappl** [comment]
Hi @SantoJambit can you check with the latest preview version if this is fixed for you? For me it seems to work fine now.

**Comment by SantoJambit** [comment]
Yep, that fixed it. Thanks.
