### ISSUE TITLE
Allow configuration of browser history object for piral-core

### ISSUE THREAD

**Issue by robert-gruner** [smapiot/piral#37]
# New Feature Proposal
## Description

Enhance the current piral-core `createInstance` method to allow input of a preexisting history object.

## Background

When piralizing an existing app it comes in handy to configure which history object the piral instance uses. This allows "programmatical" routing - meaning the ability to push changes to the history object.

The preexisting history object is probably created with 
`import { createBrowserHistory } from 'history';`
method.

## Discussion

It seems we have 2 options to achieve this

1. either via direct config options for the `createInstance` call
1. or via using the state (?)

Under the hood piral needs to take care that the history object gets forwarded to the router instance which is really used at runtime. This means probably also switching from using `BrowserRouter` to `Router` component of `react-router` lib.

Regarding the 2nd solution we could adjust the options for `setupState` to be able to input the history object there. Piral should then look inside the state if a history object exists.

Give a sign if you have further questions.

**Comment by FlorianRappl** [comment]
Thanks for raising this; much appreciated 🍻. I think as a side-effect of this we could actually also forward `history` explicitly to the API leaving pilets direct access (as such that the could forward it to components during registration).

From the two options I would prefer 1). Indeed, we already have some functional stuff in history, but I would prefer to keep it at a minimum. Though, the advantage with state is that we could make the history also accessible via the context (omitting router specific `withRouter` et al calls in such cases if desired).

I'll code a bit and see which option makes more sense from a piral-core internal view. I'll come back to this issue then.

Sounds good?

**Comment by robert-gruner** [comment]
Sounds good. Looking forward to your feedback.

**Comment by FlorianRappl** [comment]
Okay I think going via the state would be great.

My proposal:

- `setupState` contains another parameter in the passed in object to override the `history`
- At the end, when "nothing" is given this will default to `createBrowserHistory`
- In the state container at `ctx.app.components` we will add one new component called `Router`
- The `Router` will be created (if not given) by the `history`

Advantages:

- Default way is as-is
- If `history` is available, but everything else is "I don't care" (i.e., like default way) just use `setupState` and provide the `history`
- If - for some reason - a very special (wrapper) for the React Router should be used (or maybe with some special props) supply a `Router` directly

Do you think this is a sound design or would you like to be exclusive on either `history` or `Router` @robert-gruner ?

**Comment by robert-gruner** [comment]
Sounds good regarding the history object!

From our point of view it is currently **not** necessary to have the Router component also configurable. 
There are also further questions connected to this like:
* What happens if you provide both history and the Router component?
* What happens if the Router is not a proper React router?

Since there is then more to discuss just leave it out for this iteration. ;)

**Comment by FlorianRappl** [comment]
Agreed. Only the history will be considered.

**Comment by FlorianRappl** [comment]
Landed in `develop`.
