### ISSUE TITLE
process.env.DEBUG_PILET is changed from undefined to an empty string

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#371]
[`process.env.DEBUG_PILET `](https://github.com/smapiot/piral/blob/99be9d2f30f91c846906657f3ea3143d73b3f05f/src/tooling/piral-cli-webpack/src/configs/common.ts#L28) is changed from undefined to an empty string, which causes `process.env.DEBUG_PILET !== undefined` to not work, and some documents also need to be corrected, such as [piral-debug-utils](https://github.com/smapiot/piral/blob/develop/src/utilities/piral-debug-utils/README.md)

**Comment by FlorianRappl** [comment]
This change is desired.
