### ISSUE TITLE
Attach Actions on the PiralInstance Component

### ISSUE THREAD

**Issue by iotcloudarchitect** [smapiot/piral#38]
# New Feature Proposal

## Description

We should attach the actions somehow to the created PiralInstance. Thus the actions can be accessed like PiralInstance.foo or similar for the different actions. Potentially, the actions should all be contained in PiralInstance.actions

## Background

Right now its not so easy to fire the actions without the useAction/s hook/s. Its also not directly possible to create an API. Thus using the actions (from non-rendering code) is more difficult than it should be.

**Comment by FlorianRappl** [comment]
We should also expose the `createApi` action. This would allow the app shell to more easily (and directly) create an API that can be used without having to wait for pilets to be evaluated.

**Comment by FlorianRappl** [comment]
My proposal would be to return an object from `createInstance`. Something like:

```ts
interface PiralInstance<TApi> extends EventEmitter, GlobalStateContext {
  App: React.ComponentType;
  createApi(): TApi;
}
```

**Comment by FlorianRappl** [comment]
Landed in `develop`.

Right now it is located on the instance (e.g., `const { createApi } = createInstance() `, but the proposal above may be still valid and could be the implementation for the 0.7 release.
