### ISSUE TITLE
Video tutorial 5 is out of date

### ISSUE THREAD

**Issue by steve-taylor** [smapiot/piral#384]
I'm using Piral 0.13.2 and going through the video tutorials. Video tutorial 5 imports the named export `Extend` from `piral`, but it doesn't exist.

The video is embedded here: https://docs.piral.io/guidelines/tutorials/05-customizing-the-api

**Comment by FlorianRappl** [comment]
Yes its a good point. Thanks for bringing this up.

Unfortunately you cannot replace videos on YouTube. We'll add an overlay for now.

**Comment by steve-taylor** [comment]
How about replacing it with an edited version of the video?

**Comment by FlorianRappl** [comment]
> How about replacing it with an edited version of the video?

On YouTube you cannot replace videos. You can only delete and re-upload.

**Comment by steve-taylor** [comment]
Sorry if I wasn’t clear. That’s what I meant by “replace”. Delete the old one and upload the new one, which is an edited version of the old one. It doesn’t have to be created from scratch.

**Comment by FlorianRappl** [comment]
> Delete the old one and upload the new one, which is an edited version of the old one. It doesn’t have to be created from scratch.

That's clear. But I was maybe also not very specific: Since the video is part of a playlist and may be linked by people we don't want to delete the video. A new video would get a new link.

**Comment by FlorianRappl** [comment]
Thanks for reminding me stale bot : ) - always a pleasure working with you ;)

**Comment by FlorianRappl** [comment]
Added a pinned comment.
