### ISSUE TITLE
Using Piral with Curiefense - https://github.com/curiefense/curiefense/discussions/424

### ISSUE THREAD

**Issue by nathanawmk** [smapiot/piral#390]
Is it possible to use Piral with Curiefense to secure micro frontends? 

SOURCE: https://github.com/curiefense/curiefense/discussions/424

**Comment by FlorianRappl** [comment]
Yes, why not. In general a frontend will not require so much guarding. The backend (and the transport layer) is what should be guarded. Piral allows you to use all measures that are possible there (e.g., like SRI for delivering the pilets).

Hope that helps!
