### ISSUE TITLE
after pilet build main.css is imported not main.[hash].css

### ISSUE THREAD

**Issue by nlukjanov** [smapiot/piral#403]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, OS, Browser, ...]
piral - 0.13.2
piral-cli - 0.13.2

OS: macOS Catalina 10.15.7

Browser: Chrome 92

## Description

Building a pilet creates `main.[hash].css` files, but in the index.js `main.css` is being imported.
Styles are not being applied, browser throws error `main.css` is not found.

## Steps to Reproduce

1. create new shell (`piral new --target piral-shell`)
2. create new pilet (`pilet new ./piral-shell/dist/emulator/piral-shell-1.0.0.tgz --language ts --npm-client yarn --bundler webpack5 --target ./pilet`)
3. import any component with css styling to the pilet or add a css files in the src directory and import in pilet's index.tsx
4. build pilet (`pilet build`)
5. in the created `dist` folder there will be `main.[hash].css` file
6. `index.js` in the dist folder imports `main.css` file on lines 

unminify index.js, lines 73-77
```
      (n = document),
      ((i = n.createElement('link')).type = 'text/css'),
      (i.rel = 'stylesheet'),
      (i.href = o.p + 'main.css'),
      n.head.appendChild(i),
```

## Expected behavior

index.js should import main.[hash].css

## Actual behavior

index.js imports main.css

## Possible Origin / Solution

This is potentially the issue of the SheetPlugin
https://github.com/smapiot/piral/blob/develop/src/tooling/piral-cli-webpack5/src/configs/SheetPlugin.ts#L10

Probably the file name should include the hash

**Comment by FlorianRappl** [comment]
Thanks for the report!

On it!
