### ISSUE TITLE
Logging of View State Changes can't be disabled in debug mode

### ISSUE THREAD

**Issue by marsmichelmann** [smapiot/piral#404]
## Description

Logging of view state changes is enabled per default in debug mode. 

According to the piral documentation https://docs.piral.io/reference/documentation/debug#session-variables it should be able to disable this config by setting the session variable dbg:view-state

## Steps to Reproduce

1. Open Piral instance in debug mode
2. Disable logging of view state changes via dev console of browser: sessionStorage.setItem('dbg:view-state', 'off');
2. Every view state change still leads to a log entry
![logging](https://user-images.githubusercontent.com/37302918/131352979-8d59d886-b8ec-4ddb-aa52-97ff935fd76c.jpg)

## Possible Origin / Solution

Currently a log entry is created, when settings.viewState is true (see debug.js line 236). But settings.viewState is always true. It should be checked, if settings.viewState.value is true

**Comment by FlorianRappl** [comment]
Great catch! Indeed, you are totally right. Do you want to submit a PR on this one? Would be much appreciated!

**Comment by marsmichelmann** [comment]
Sure. But it seems like it's not possible to create a bugfix branch for me 
![push](https://user-images.githubusercontent.com/37302918/131365651-5a4d4a20-ec38-4c8a-a30d-2dc11649fa66.jpg)

**Comment by marsmichelmann** [comment]
ahhh, sorry. Of course I have to work on a fork for https://github.com/smapiot/piral ;-)
