### ISSUE TITLE
Routes loaded through `registerPage` in pilet will not load when refreshing on route.

### ISSUE THREAD

**Issue by Rody-Kirwan** [smapiot/piral#408]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version
piral v0.13.6
osx v10.15.7
browser: chrome v92.0.4515.131

## Description

Routes loaded through `registerPage` in pilet will not load when refreshing on route.
You can navigate using the link injected with `registerMenu` and the page loads correctly, however when you refresh the page is not found.

This only happens when I serve the piral `dist/release` folder (as you would expect to do in production).

### Steps To Reproduce
1. clone repo https://github.com/Rody-Kirwan/piral-sandbox
2. From inside my-app directory run `yarn`
3. run `yarn server` to serve release folder
4. go to `localhost:5000` in browser
5. Click Test Route in menu to see page registered by pilet
6. Refresh page

### Expected Result 
Test Route page should be displayed

### Actual Result
404 is shown

Note: No network requests are made for js bundles or pilets

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by Rody-Kirwan** [comment]
Closing this - rubberduck situation :D
Issue is obviously with `serve` Apologies

**Comment by FlorianRappl** [comment]
Hi @Rody-Kirwan thanks for reporting this; how do you start the server? The SPA mode is something that you will need to set up. In development this is done by our server, which automatically serves the index.html as a fallback (as any SPA solution would do).
