### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#409]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [ ] Did you perform a search in the issues?

## Environment Details and Version

piral-core@0.13.7

## Description

Throw an error in the vue sample of [sample-cross-fx-pilets](https://github.com/smapiot/sample-cross-fx-pilets):
![image](https://user-images.githubusercontent.com/5674761/132164158-77e0d741-0ff3-46f8-ab43-5cf72ec902f5.png)

## Steps to Reproduce

1. `git clone https://github.com/smapiot/sample-cross-fx-pilets`
2. `npm i` in the vue folder
3. `yarn start`

## Expected behavior

Everything works fine.

## Actual behavior

[What actually happened]

## Possible Origin / Solution

Fix in [debug.ts](https://github.com/smapiot/piral/blob/d7407a1d9509725cef023d9b0b6af3dee21a619d/src/utilities/piral-debug-utils/src/debug.ts#L59) [debug.ts](https://github.com/smapiot/piral/blob/d7407a1d9509725cef023d9b0b6af3dee21a619d/src/utilities/piral-debug-utils/src/debug.ts#L191) with [json-cycle](https://github.com/valery-barysok/json-cycle) or [JSON-js](https://github.com/douglascrockford/JSON-js).

**Comment by FlorianRappl** [comment]
While this is an issue I don't think it will have any impact on your code. It may be just cosmetics (i.e., no error shown in debug mode).

I think the best solution here would be to not serialize the state as a whole, but only transport the changed part (i.e., staying flat therefore avoiding any cycles at all). That way it would keep the performance (actually even improving on it).

**Comment by carvinlo** [comment]
Internet Explorer fire the window “storage” event on the window that stored the sessionStorage data, so the [`setItem`](https://github.com/smapiot/piral/blob/d7407a1d9509725cef023d9b0b6af3dee21a619d/src/utilities/piral-debug-utils/src/debug.ts#L74) and the [`storage event`](https://github.com/smapiot/piral/blob/d7407a1d9509725cef023d9b0b6af3dee21a619d/src/utilities/piral-debug-utils/src/debug.ts#L256) fall into an infinite loop in IE11.
Is there a way to avoid it, such as ignoring the `stroage` event when `new Error().stack == false` in legacy browser?

**Comment by FlorianRappl** [comment]
> Is there a way to avoid it, such as ignoring the stroage event when new Error().stack == false in legacy browser?

Yeah I think we can do that! Thanks for the suggestion / pointing out the issue!

**Comment by carvinlo** [comment]
> > Is there a way to avoid it, such as ignoring the stroage event when new Error().stack == false in legacy browser?
> 
> Yeah I think we can do that! Thanks for the suggestion / pointing out the issue!

As [discussed](https://github.com/smapiot/piral/issues/409#issuecomment-914160530)
Add `ignore` to the [`setSetting`](https://github.com/smapiot/piral/blob/07213874400e65c50045fcfec1c0f9b8958afedf/src/utilities/piral-debug-utils/src/debug.ts#L73) function to break out of the loop when running in legacy browsers: 
```
    const legacy: boolean = !new Error().stack;
    let ignore: boolean = false;
    const setSetting = (setting: { value: any }, key: string, value: any) => {
      setting.value = value;

      if(legacy){
        if(ignore) return;
        setTimeout(() => {
          ignore = true;
          sessionStorage.setItem(key, value ? 'on' : 'off');
          setTimeout(() => {
            ignore = false;
          }, 0);
        }, 0);
        return;
      }

      sessionStorage.setItem(key, value ? 'on' : 'off');
    };
```
It works fine in ie11.
What do you think?

**Comment by FlorianRappl** [comment]
This is already part of the upcoming 0.14:

https://github.com/smapiot/piral/blob/experimental/src/utilities/piral-debug-utils/src/debug.ts#L223
