### ISSUE TITLE
Optimize documentation with big picture and component-specific starting points

### ISSUE THREAD

**Issue by iotcloudarchitect** [smapiot/piral#41]
# New Feature Proposal

## Description

When using the documentation shown at https://docs.piral.io/documentation#your-first-piral-application the reader expects a step-by-step instruction on how to start creating a own Piral Instance. Instead, the reader needs to follow a link at the top which will be not recognized, because the headline is telling about a "Pilet Guideline".
For starters, it must be intuitive to start with Piral, by showing the big picture with real-life samples. 

## Background

The onboarding of developers must be very easy by offering well-structured step-by-step guides with real-life samples in order to have fun starting with Piral and all of its components.

**Comment by FlorianRappl** [comment]
So what's your preferred outline? Can you please be specific? Thanks!

**Comment by FlorianRappl** [comment]
The following proposal may work:

- In the documentation we distinguish between guidelines and references. The FTU should see primarily the guidelines.
- References include "API documentation", "Type reference", "CLI reference", "Specifications"; they go into detail
- In between the sample material and FAQ is advertised; these sections are also referenced in all other parts (e.g., see our FAQ, see this sample, ...)

For the guidelines we will make sure to fully communicate:

- Who's the audience
- What's the expected level of familiarity with Piral
- An abstract - what to expect

Each guideline starts with the assumptions and prerequisites to fully communicate whats inside. The guidelines are ordered in such a way that it will fit for *most* people, but we'll try to communicate the right path for anyone else, too.

A potential order / list of topics for guidelines:

1. Introduction (what is a microfrontend? what is Piral? why is Piral good / what can it bring to the table? what do I need to get started?)
2. Creating a pilet (simple guide to get familiar with the CLI and publish something to a feed that lives temporarily in conjunction with the available demo instance)
3. Creating your own Piral instance (using the available sample feed)
4. ...
5. Development workflow
6. Dependency Management
7. Plugins
8. ...

The list of topics (and order) is still open. Any contribution wanted!

**Comment by FlorianRappl** [comment]
Landed in `develop`.

The tutorials will now continuously be improved.
