### ISSUE TITLE
Allow an Angular Pilet to run without zone.js.

### ISSUE THREAD

**Issue by mremolt** [smapiot/piral#412]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Allow an Angular Pilet to optionally run without zone.js by adding the 'noop' Zone option to `piral-ng`.

## Background

Running several Angular instances in the same global Zone can lead to all sorts of problems. Providing developers with the existing feature to run Angular with the 'noop' Zone can mitigate these problems.

**Comment by FlorianRappl** [comment]
Landed in preview.
