### ISSUE TITLE
Implement postLogoutRedirectUri provided by MSAL

### ISSUE THREAD

**Issue by nvonbenken** [smapiot/piral#418]
# New Feature Proposal

MSAL provides a `postLogoutRedirectUri` that should be implemented to allow users to be logged out and redirected to another location.

## Description

MSAL implementation can be seen here https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release#configuration-options

## Background

Right now there is no way to log a user out and direct them to a page that does no require auth using `piral-adal`

**Comment by FlorianRappl** [comment]
Available in 0.14 preview.
