### ISSUE TITLE
piral-cli-webpack5 extend-config.js has bad references causing null pointer errors

### ISSUE THREAD

**Issue by kyle-nicholls** [smapiot/piral#422]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral-cli-webpack5 v0.14.0
piral-cli-webpack v0.14.0

## Description

The webpack `extend-config.js` helper does not work for adding plugins.

## Steps to Reproduce

1. add a webpack plugin using the `extend-config.js` helper
2. run `pilet debug`

```
const extendConfig = require('piral-cli-webpack5/extend-config');
const { DefinePlugin } = require('webpack');

module.exports = extendConfig({
	plugins: [
		new DefinePlugin({
			SOME_PROPERTY: JSON.stringify(''),
		}),
	],
});
```

## Expected behavior

An error should not be thrown when adding a plugin using `extend-config.js`.

## Actual behavior

`[0174] The bundling process failed: plugins is not defined` is thrown

## Possible Origin / Solution

https://github.com/smapiot/piral/blob/develop/src/tooling/piral-cli-webpack5/extend-config.js#L109
This appears to be the broken line. I think it should be `config.plugins.push(...override.plugins);`

**Comment by FlorianRappl** [comment]
Thanks for reporting the issue. This should be fixed now in the preview version (tag: `next`).
