### ISSUE TITLE
Example with using Blazor Wasm as an app shell

### ISSUE THREAD

**Issue by XanderSelorm** [smapiot/piral#428]
Hi there,

I chanced on the use of the Piral Framework for implementing micro-frontends and I find it to be very useful. However, my application comes in as a Blazor wasm project and my aim is to use this current project as my app shell.

Is there any example on how I could implement that? I can't really find my way around the documentation too. 
Kindly note that I am a beginner. Thanks in advance.

**Comment by FlorianRappl** [comment]
There is now an example using distributed layout: https://github.com/piral-samples/piral-distributed-layout

Keep in mind that for making this Blazor specific we'd need an incentive. Otherwise, we'll stay generic as it serves the broadest audience.
