### ISSUE TITLE
Adapt documentation about static Piral instance

### ISSUE THREAD

**Issue by iotcloudarchitect** [smapiot/piral#43]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

**Easy Way**

- It would be helpful to add the link to the Piral-CLI and a guide for installation
- "npm start" will not work, because the package.json does not contain the "start" script definition

**Detailed Way**

- There is no prerequisite mentioned which is necessary to  perform "touch ..." at command line
- There should be all necessary code snippets that are necessary to let the React sample run

**Next Steps**

It is not clear, what the reader needs to do in order to run the Piral instance.
Here, a big picture and step-by-step guide will help a lot.

## Background

The start with creating an own Piral instance must be as simple as possible.
A detailed step-by-step guide must be provided and every step needs to be decribed also for NodeJS and/or React beginners.

**Comment by FlorianRappl** [comment]
`touch` is a standard tool that comes with every machine (excluding Windows). Usually, developers should know what it is.

Regarding the other aspects - since `piral new` already creates everything and `piral debug` will run - what else is needed?

> There should be all necessary code snippets that are necessary to let the React sample run

What is missing here?

**Comment by FlorianRappl** [comment]
Landed in `devel`.
