### ISSUE TITLE
Use pilets in multiple Piral instances

### ISSUE THREAD

**Issue by luckyluggi** [smapiot/piral#431]
Hello.

_This is rather a question than a feature request. i hope it is posted in the right place here._

I just ran threw the piral docs and i saw that you have to install the app shell as a dev dependency into every parcel.
I'm currently thinking of switching my project into a microfronend project using piral. But my original thought was that i could use one pilet in multiple piral instances. 

A concrete example would be a Hotel Online-Checki-In vue application that i'd like to use inside an app on the guests phone (which would be one piral instance) as well as inside an app that is running on a tablet at the reception (which would be a second piral parcel.)
In my opinion those have to be seperate piral instances since they have a different layout and the also do house different other pilets. The also need differend Authentication and so on.

What would be the best way to acomplish such a scenario? can i install 2 pilet instances in a piral?

**Comment by FlorianRappl** [comment]
> What would be the best way to acomplish such a scenario? can i install 2 pilet instances in a piral?

You can already do that. Your pilet does not depend on the chosen app shell. It's true that you install / select an app shell for development purposes, but the pilets are as universal as you choose them to be.

Example 1: You develop app shell 1 and that brings two shared dependencies "react" and "react-router-dom". In your pilet API you decide for `piral-core` and use no plugins / other APIs. Now pilets developed for this can truly be used *almost* everywhere. Only app shells built upon `piral-base` or those that do not share "react" or "react-router-dom" may be problematic.

Example 2: You develop app shell 2 which comes with a ton of shared dependencies, among them your own component library. Pilets developed for that app shell also use that component library heavily. Furthermore, you have some custom APIs such as "registerFooBar" in there - these are usually also used. In that case the pilets may indeed only be usable by app shell 2. An exception would be app shell 3, which uses / shares the same component lib, and exposes / reimplements the same pilet API.

The `pilet` commands support `--app` argument that overrides the given / placed `piral.name` field in *package.json*. The other app shell, however, needs to be available too (usually in the `devDependencies`).

Hope that answers your question!

Further reading:

- https://docs.piral.io/reference/faq/pilets#how-strong-is-the-coupling-from-piral-to-my-pilets%3F
- https://docs.piral.io/reference/faq/pilets#do-i-need-to-create-my-own-app-shell%3F
- https://docs.piral.io/guidelines/tutorials/09-pilet-best-practices#reducing-the-app-shell-dependency

**Comment by luckyluggi** [comment]
Thanks Flo thats very helpful. I'll try it as soon as i can get to it.
