### ISSUE TITLE
Highlight Selected Menu Item in the Piral Menu Container

### ISSUE THREAD

**Issue by satishjs2297** [smapiot/piral#432]
# Highlight Selected Menu Item in the Piral Menu Container

For more information, see the `CONTRIBUTING` guide.

## Description

we need a way to highlighting selected menu item from menu list.  Problem we noticed is, piral menu not giving any hook/event to highlight on the selected menu item. Because of this limitation we can't dynamically show and hide the css rules on the respective menu item div...

## Background

we don't find option to show / hide the class on the selected menu div. For instance, we enable css to show bold line under tools menu,  but we click on Search menu , css  to highlight menu is not applying on selected Search menu.

![image](https://user-images.githubusercontent.com/6884130/145331196-ad23270c-7a2b-4d47-88c7-db7957585bb5.png)

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
Hm can you describe what you mean with *selected*? If you refer to the menu item corresponding to the current URL -> there is nothing `piral-menu` can do for you (it does not care about links and allows you to insert anything - also external links, buttons, or whatever). You can solve that yourself, e.g., by using `NavLink` or any hook (such as `useLocation`) from `react-router-dom` in the component you register.

Does that help?

**Comment by FlorianRappl** [comment]
Can we close this @satishjs2297 ?
