### ISSUE TITLE
React Default Import Statements Break in Pilet Schema v2

### ISSUE THREAD

**Issue by shoerner** [smapiot/piral#433]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x]  Are you running the latest version?
- [x]  Did you perform a search in the issues?

## Environment Details and Version

[Package Version, OS, Browser, ...]
### Versions
piral-cli@0.14.4
piral-cli-webpack5@0.14.4
webpack@5.63.0
@babel/core@7.14.5

OS: Windows 10, Chrome

## Description

When users upgrade a Pilet from the v1 to v2 spec, Webpack changes how it compiles default import statements. 

In the v1 spec, Webpack calls to React would reference a Webpack require statement which would then return React as expected. (eg: `webpackRequire('react').Component`)

Changing the build to v2, calls for React are referencing the Webpack require and then calling `.default` on it, despite the initial Webpack require returning the React module. (eg: `webpackRequire('react')['default'].Component`). The result is that the property called is undefined as `.default` is undefined. 

In this particular case, we're seeing it using [`react-transition-group`](https://github.com/reactjs/react-transition-group/blob/master/src/TransitionGroupContext.js#L1) along with some internal packages. 

Sample:
![image](https://user-images.githubusercontent.com/4111032/145442732-8edff3cd-eab8-4124-8f70-11f12ec325c6.png)

## Steps to Reproduce

1. Using a Pilet running Piral 0.14.x and building against v1 spec, upgrade to v2

## Expected behavior

Pilet loads normally

## Actual behavior

Undefined property `.Component` on runtime

**Comment by FlorianRappl** [comment]
Right now we get for the described example.

With `v1` as schema:

```js
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ "react");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (react__WEBPACK_IMPORTED_MODULE_0___default().createContext(null));

module.exports = __WEBPACK_EXTERNAL_MODULE_react__;
```

With `v2` as schema:

```js
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ "react");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (react__WEBPACK_IMPORTED_MODULE_0__["default"].createContext(null));

via setters:

module.exports = __WEBPACK_EXTERNAL_MODULE_react__;
function(module) {
    Object.keys(module).forEach(function(key) {
        __WEBPACK_EXTERNAL_MODULE_react__[key] = module[key];
    });
},
```

The potential issue is that with SystemJS alone Webpack "relies" on SystemJS handling the import. The potential fix makes use of the `use-default` extra in SystemJS.

**Comment by FlorianRappl** [comment]
Is available in the preview `@next`.
