### ISSUE TITLE
Piral-ng should respect --public-url

### ISSUE THREAD

**Issue by mremolt** [smapiot/piral#434]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

All Piral packages are at latest Version, Angular is at 13.0.2

## Description

Currently piral-ng hardcodes Angulars APP_BASE_HREF to "/", which causes routing inconsistencies when --public-url is used during build. React based pilets use the prefixed path, ng-piral Pilets don't.

## Steps to Reproduce

1. Create a piral-ng based Pilet
2. Add some Angular routing
3. Verify lcally everything works
4. Do a release build using a --public-url != "/"
5. React Pilets will use it a prefix, piral-ng Pilets don't

## Expected behavior

Angular Pilets should respect the set --public-url

## Actual behavior

Angular Pilets always use "/" as base href

## Possible Origin / Solution

The relevant code is here https://github.com/smapiot/piral/blob/4553e585d9cbb9ebd71d032a8fde55c305aaa268/src/converters/piral-ng/src/startup.ts#L31

**Comment by FlorianRappl** [comment]
We will solve it with 2 enhancements. First, we will introduce a new env variable called: `PIRAL_PUBLIC_PATH`, which will be available at build-time (and set to the configured public path). This variable is used to populate the context also with a value `publicPath`.

Now `piral-ng` can just access the public path via `context.publicPath` (or similar) - falling back to "/" if its not there.

**Comment by FlorianRappl** [comment]
This is available in the preview `@next`.
