### ISSUE TITLE
Access Pilet API in App Shell

### ISSUE THREAD

**Issue by lschoett** [smapiot/piral#44]
# New Feature Proposal

## Description

The Pilet API should be accessible also in App Shell.

## Background

At the moment accessing the API from the App Shell is not that easy and some features of the API might useful/required in the App Shell.

## Discussion

This could be already covered by #38, if `createApi` is available. Alternatively (or additionally), the core (i.e., app-shell) could already create an API or itself and pass it back.

**Comment by FlorianRappl** [comment]
The API is now available via the Piral instance object.

You can either create a new API with `createApi` or use a default API called `root`.

```ts
const Piral = createInstance(/* ... options */);
const myApi = Piral.createApi({
  name: 'Pseudo Module',
  version: '1.0.0',
});
const rootApi = Piral.root;
// e.g., rootApi.registerPage('/some-page', ...);
```

Landed in `develop`.
