### ISSUE TITLE
Support for updating the extension component in vue page

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#440]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

When the count in the react component increases, the react extension will be updated. But in the vue component increases, the extension will not be updated. 

## Background

See the [Repo](https://github.com/carvinlo/piral/tree/amu/cross-framework-extension-update-prop).
1. Setup: `yarn && cd src/samples/sample-piral-core && yarn start`
2. Go to: `http://localhost:1234/react` and `http://localhost:1234/vue`

## Discussion

[piral-vue/src/extension.ts](https://github.com/carvinlo/piral/blob/b562533a48e09e68cb1a77cb0f65d7a1c9510395/src/converters/piral-vue/src/extension.ts#L13)
```ts
    ...
    render(createElement) {
      return createElement(rootName);
    },
    watch: {
      params(oldValue, value){
        // Compare logic and update
      }
    },
    mounted() {
      this.piral.renderHtmlExtension(this.$el, {
        empty: this.empty,
        params: this.params,
        render: this.render,
        name: this.name,
      });
    },
    ...
```
Update extension by watching `params` property changes here?

**Comment by FlorianRappl** [comment]
Yeah sounds good to me. Mind doing a PR?

**Comment by carvinlo** [comment]
I'm happy to, but I encountered two problems:
1. I haven't thought about the logic of comparing the params property;
2. Don't understand the converters of other frameworks, such as piral-ng.

**Comment by FlorianRappl** [comment]
Well, for (1) shouldn't that be done by vue? Yes, if vue actually compares it "literally" (i.e., objects that change even though their content remains the same are considered changed) that may be inefficient, but for a first PR not a problem.

Regarding (2) there is no need. Just implement vue - other converters solve that issue (or don't solve that issue) already. The PR should be for vue alone to make that happen.

I think you've already suggested a way forward in the issue. Is there more needed for a first / simple solution?

**Comment by carvinlo** [comment]
> Regarding (2) there is no need. Just implement vue - other converters solve that issue (or don't solve that issue) already. The PR should be for vue alone to make that happen.
Okey~

> Well, for (1) shouldn't that be done by vue? Yes, if vue actually compares it "literally" (i.e., objects that change even though their content remains the same are considered changed) that may be inefficient, but for a first PR not a problem.
> I think you've already suggested a way forward in the issue. Is there more needed for a first / simple solution?
Currently, data can only be transferred through the params attribute, so when multiple data needs to be transferred, it is necessary to compare the second-level properties of the params object. For example:
```ts
...
watch: {
  params: (oldValue, value) => {
    if(Object.keys(oldValue).length !== Object.keys(value).length){
        console.log('has changed');
        return;
    }
    for (let property in value) {
      if (value[property] !== oldValue[property]) {
        console.log('has changed');
        return;
      }
    }
    console.log('not changed');
    return;
  }
}
...
```
> `<extension-component name="ext-component-example" :params="counter" />` (`counter = { count }`) Changing the `counter` property does not trigger the `watch`.
