### ISSUE TITLE
Initialize hooks

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#449]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the proposed feature]

## Background

[Provide any additional background for the feature, e.g., why is the current solution insufficient, what problem will it solve, etc.]

## Discussion

To be able to set hooks via [`beforeCommand`](https://github.com/FlorianRappl/piral-cli-local-feed/blob/8eead0208be2a27524e14bc2c2923828fc589629/src/index.ts#L50), the [hooks argument](https://github.com/carvinlo/piral/commit/84a2ce57a9759480788b84c8212c354ac834fa1f) needs to be passed.

**Comment by FlorianRappl** [comment]
Sounds good to me!

Remark: It's also fine not to expose it directly via the CLI commands (i.e., enumerate it in the flags). This was done on purpose as `hooks` would require JS-code anyway; nothing that can be passed from the CLI.

**Comment by carvinlo** [comment]
> i.e., enumerate it in the flags
Could you please provide an example?

**Comment by FlorianRappl** [comment]
> It's there other way to set the hooks?

Yeah directly via the API. For instance, we do that in `pidoc`, see: https://github.com/smapiot/pidoc/blob/main/packages/core/bin/pilet-cli.js#L57

**Comment by carvinlo** [comment]
I see, Thank you very much!
