### ISSUE TITLE
Split Piral-Ext in multiple libraries

### ISSUE THREAD

**Issue by lschoett** [smapiot/piral#45]
# New Feature Proposal

## Description

Currently the Piral Ext library serves several functions like translations or backend connectivity. It might be useful to split the library into smaller libraries, so that developers have some flexibility to chose and tailor to the required features. 

## Background

When somebody wants to use `piral-core` due to a migration of an existing application the full `piral-ext` may be too much to consume. Nevertheless, a part of it (e.g., `fetch`) may still be interesting.

## Discussion

We could go for the following parts:

- `piral-fetch`
- `piral-translate`
- `piral-urql`

**Comment by FlorianRappl** [comment]
Landed in `develop`.
