### ISSUE TITLE
Wraps all webpack loader rules into a single oneOf rule

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#451]
https://github.com/smapiot/piral/blob/a6f52016d1e8720feeed91d2fa5234ca72d3fbba/src/tooling/piral-cli-webpack/src/webpack/common.ts#L98
Would you agree to wraps all webpack loader rules into a single oneOf rule?
> "oneOf" will traverse all following loaders until one will match the requirements. When no loader matches it will fall back to the "file" loader at the end of the loader list. [create-react-app](https://github.com/facebook/create-react-app/blob/5614c87bfbaae0ce52ac15aedd2cd0f91ffd420d/packages/react-scripts/config/webpack.config.js#L361)

This eliminates the need to enumerate other unknown file types, such as `xslx`.

**Comment by FlorianRappl** [comment]
Sounds good to me. I'm just not sure if / how it will affect "changing" that default config. Will definitely be more complicated, but should be doable (see https://github.com/smapiot/piral/blob/develop/src/tooling/piral-cli-webpack5/extend-config.js).

**Comment by carvinlo** [comment]
`extend-config.js` is under control.
But it's a break change for users who modify the `rules` of `config` in `webpack.config.js`.

**Comment by FlorianRappl** [comment]
> But it's a break change for users who modify the rules of config in webpack.config.js.

Yeah that's true. My feeling is that this item would be something for 0.15 - and would be part of the breaking changes. As long as we can keep the API of extend-config.js stable I feel good about this.
