### ISSUE TITLE
Add Piral CLI extension for local pilet feed service

### ISSUE THREAD

**Issue by lschoett** [smapiot/piral#46]
# New Feature Proposal

## Description

Enhance the Piral CLI to also integrate with the local Pilet Feed service.

## Background

Sometimes during development of a Piral instance it makes sense to have a local feed service running. The sample feed service is great and useful for this purpose, but it needs to be started separately (despite it being published now as an NPM package that allows execution, e.g., via `npx`).

If `piral-cli-feed` would exist it could allow:

- `piral feed` to run the server standalone (same as `sample-pilet-service` does today)
- e.g., `piral debug --feed` to run the feed in kras as a middleware; essentially not needing to mock the feed

## Discussion

Might be a useful extension, but it should have a lower priority, since the public feed service is available by now and offers more features than the local feed service.

**Comment by SantoJambit** [comment]
I'd say, that it should still be highlighted, that it's a sample-feed. So maybe name it piral-cli-sample-feed and call it via piral sample-feed or piral debug --sample-feed.

**Comment by FlorianRappl** [comment]
Available:

- https://github.com/FlorianRappl/piral-cli-local-feed
- https://www.npmjs.com/package/piral-cli-local-feed
