### ISSUE TITLE
Missing `debugPilet` env variable

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#461]
https://github.com/smapiot/piral/blob/89a719e1827869c9953f9c3c76a338be59e31b7d/src/tooling/piral-cli/src/build/run-debug-pilet.ts#L26
Missing `debugPilet: true` env variable?

**Comment by FlorianRappl** [comment]
This is only relevant for a Piral instance. No relevance for pilet debugging itself.

**Comment by carvinlo** [comment]
Got it, thanks!
