### ISSUE TITLE
Provide a means to inject metadata.config when debugging a Pilet.

### ISSUE THREAD

**Issue by EclipseZA** [smapiot/piral#462]
# Pilet debug config

## Background

Pilet metadata includes a config property, which allows for Pilet's runtime configs to be controlled by a custom feed service. This is a powerful tool, however, there is currently no equivalent when debugging a Pilet against an AppShell emulator.
When the Pilet debugged, it is injected, rather than provided by a feed service. There is currently, no means to specify values for metadata.config.

## Proposal

Extend the Piral CLI to allow for the inclusion of json config in the debugged Pilet's metadata. This will allow Pilets to retrieve their configs the same way they would in a production environment.

## Discussion

My initial thought was to add a pilet debug flag to allow the specification of a .json file whose contents will be added to meta.config when the Pilet is injected. This solution could prove difficult to use when debugging multiple Pilets.

An alternative could be to include a file in the Pilet's root of a specific name (e.g. debug-config.json). The file and path could be overridden by a package.json property. If the specified file is present, the CLI will include its content in the debugged Pilet's meta.config.

This could potentially be taken a step further to not only provide meta.config when debugging, but other metadata properties a custom Pilet feed service might provide. This implementation would have to take care to not overwrite core metadata props, unless safe to do so.

**Comment by FlorianRappl** [comment]
This landed in `experimental`. It right now works as follows:

1. The *package.json* can contain an additional entry `piletConfig`. If this one is present its used to fill the `config` field of a pilet. Great thing about this one is that our feed service supports this, too. So you could use it for some (default) config values that you want to publish / use initially (and have the same set for development).
2. If a `debug-meta.json` is adjacent to the *package.json* of a pilet its content is used to further populate the pilet's metadata. It can override some things such as `custom` and `config`, but it cannot override intrinsics such as the name, version, link.
3. You can change the resolution of the `debug-meta.json` by supplying a custom `.krasrc` file. You can now set the options for the "pilet" injector. Changing the option `meta` (default: "debug-meta.json") changes how the file should be called. The file is always resolved relative to the *package.json* of a pilet.
