### ISSUE TITLE
Remove support for IE11

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#467]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Right now the polyfills supplied by `piral` are mostly to enable support for IE 11 (and to some degree even older versions). Since IE 11 is no longer supported we can now finally make this move, too.

## Background

The `piral/polyfills` module is a standard module that is already present in the default template. Do we really need it? Partially, maybe (e.g., regenerator-runtime is still used very often). But for the most part - certainly not.

## Discussion

Some of the polyfills should still remain in maybe a dedicated utils package or (if possible) in `piral`, but with a new name (like `polyfills-ie11.js`). This way, if there is really some interest in supporting IE 11 this could be quickly done.

**Comment by carvinlo** [comment]
Maybe we can use `nomodule` to reduce the size, like [next.js/supported-browsers-features](https://nextjs.org/docs/basic-features/supported-browsers-features)?

**Comment by FlorianRappl** [comment]
I mean the `nomodule` trick is something you can "practically" always do; it's more or less a question of the required effort (you'd need to run the build twice - once for es5 output and once with esm output).
