### ISSUE TITLE
Make Webpack5 the Default Bundler

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#469]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Right now the default bundler is Webpack v4 (`piral-cli-webpack`). Default means that if nothing is installed then `piral-cli-webpack` will be resolved in case of a `build` command being requested. We now want to change that default to a faster / modern / mature alternative.

## Background

We started with `piral-cli-parcel` (actually back then integrated into the `piral-cli`) as a bundler and then we made the bundler system fully flexible - even switching to `piral-cli-webpack` as default. Since then Webpack v5 has matured and we are now ready to take it to the next level.

## Discussion

Is there anything to improve in general on `piral-cli-webpack5`? Anything that would make it better / easier to use?

**Comment by mingfang** [comment]
new project created using `npm init piral-instance` with webpack5 bundler does not build correctly.
This is the error
```
ERROR in ./src/index.jsx 3:0-42
Module not found: Error: Can't resolve './layout' in '/home/projector-user/IdeaProjects/piral-shell/src'
resolve './layout' in '/home/projector-user/IdeaProjects/piral-shell/src'
  using description file: /home/projector-user/IdeaProjects/piral-shell/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/projector-user/IdeaProjects/piral-shell/package.json (relative path: ./src/layout)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/projector-user/IdeaProjects/piral-shell/src/layout doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/projector-user/IdeaProjects/piral-shell/src/layout.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/projector-user/IdeaProjects/piral-shell/src/layout.tsx doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/projector-user/IdeaProjects/piral-shell/src/layout.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/projector-user/IdeaProjects/piral-shell/src/layout.json doesn't exist
      as directory
        /home/projector-user/IdeaProjects/piral-shell/src/layout doesn't exist

webpack 5.73.0 compiled with 1 error in 3249 ms
```

**Comment by FlorianRappl** [comment]
I think you must be doing something wrong / different.

> ERROR in ./src/index.jsx 3:0-42

The standard options / template has an index.tsx. There is no index.jsx. Please specify the full options used / what exactly you did if you want to report a bug. Otherwise, we'll not invest any time.

**Comment by mingfang** [comment]
This is coming straight from your scaffolding.
It had a choice of js or ts and I picked js.
Maybe you didn't anticipate people choosing js over ts

**Comment by mingfang** [comment]
here you go
https://github.com/smapiot/piral/blob/develop/src/templates/piral-template-default/templates/piral-layout.jsx.ejs

**Comment by FlorianRappl** [comment]
> This is coming straight from your scaffolding.

Not directly. As mentioned you are not using the default options. You clarified that you actually used the JS option.

The problem is that the webpack configuration is missing the jsx extension. You can just teach Webpack about it:

```js
//webpack.config.js

module.exports = (config) => {
  config.resolve.extensions = [...config.resolve.extensions, '.jsx'];
  return config;
};
```

**Comment by mingfang** [comment]
First, thank you for the webpack configuration above. That fixed the problem.
But second, I disagree that this didn't come from your scaffolding. In fact I sent the link to the template file above.(You're the author too I think).

Yes I picked an option that's non-default.
But as a user that's presented with options, shouldn't I expect all the available options to work?

Anyway, Piral looks amazing and I will invest in learning it.
Thank you for your help.
I hope this helps others as well.

**Comment by FlorianRappl** [comment]
> But as a user that's presented with options, shouldn't I expect all the available options to work?

Sure - that was not my point. My point was that I don't know which options you selected - you should mention them. Otherwise, this is not really efficient to trace.
