### ISSUE TITLE
Support plugins to extend the Piral CLI

### ISSUE THREAD

**Issue by lschoett** [smapiot/piral#47]
# New Feature Proposal

## Description

The Piral CLI should support the integration of custom plugins, which enhance the functionality of the CLI.

## Background

Right now adding some commands, e.g., for (E2E) testing, are missing (on purpose). Nevertheless, with a simple extension mechanism new commands (e.g., `pilet test`) could be made available.

## Discussion

Plugins could have the following opportunities:

- Create a new command
- Wrap an existing command
- Listen to events from existing commands

Maybe there are more (or should be less) possibilities?

**Comment by FlorianRappl** [comment]
Landed in `develop`.
