### ISSUE TITLE
support for extendSharedDependencies()

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#48]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

As discussed, we need a way to extend shared dependencies (keeping the ones that the piral-cli adds via the `externals` field in the package.json)

## Background

We usually want to keep use the `externals` dependency mechanism rather than explicitly exporting them. But in some cases, an explicit export is the only way (for example when exporting from the shell).

**Comment by FlorianRappl** [comment]
Landed in `develop`.
