### ISSUE TITLE
Define output directory for piral debug cli command

### ISSUE THREAD

**Issue by nupis-ChristophS** [smapiot/piral#482]
# New Feature Proposal

Define output directory for `piral debug` cli command via a `target` option.

## Description

It is possible to specify the output directory for the cli command piral build per target option. This should also be possible for the debug command.

## Background

This is especially useful for monorepos (e.g. via Nx), because in this case the output directory is not below the special application project, but on the monorepo project level.

**Comment by FlorianRappl** [comment]
Sounds good to me. We can add this via the same flags as the `piral build` / `pilet build` commands. I think the bundler plugins should pick that up automatically - otherwise we just add it there.

**Comment by FlorianRappl** [comment]
Landed in 0.15 (`canary` tag, `experimental` branch).
