### ISSUE TITLE
TypeError: Cannot add property basePath, object is not extensible

### ISSUE THREAD

**Issue by Alellujah** [smapiot/piral#486]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Piral 0.14.15
Windows 10
Chrome

## Description

After bumping Piral version from 0.13.0 I got this error which then prevents piral from loading the pilets: 

``
Uncaught (in promise) TypeError: Cannot add property basePath, object is not extensible
    at setBasePath (utils.js:15:1)
    at loadUmdPilet (umd.js:10:1)
    at loader.js:37:1
    at strategies.js:38:1
    at Array.map (<anonymous>)
    at strategies.js:38:1
setBasePath @ utils.js:15
loadUmdPilet @ umd.js:10
`` 

## Steps to Reproduce

1. Upgrade from 0.13.0 to 0.14.15 

## Expected behavior

To work normally

## Actual behavior

Doesn't load pilets anymore

## Possible Origin / Solution

The initial problem and reason to update piral was because we're having a problem loading the pilets with CSR which I though it could be related to this [ISSUE](https://github.com/piral-samples/piral-microfrontend-demo/issues/11) (at least the behaviour was the same, even thought it seemed to have been fixed in a previous version than 0.13.0.)

**Comment by FlorianRappl** [comment]
Hm not sure - this seems to working fine in all tests. Something here seems fishy. Are you sure you upgraded using `piral upgrade`?

**Comment by Alellujah** [comment]
Well I did upgraded the shell only, didn't upgrade any of the pilets. Running a pilet solely in localhost does seem to work without issues. 

Might be a noob question, but do I need to upgrade all the pilets after upgrading piral?

**Comment by Alellujah** [comment]
Using Webpack, we have a monorepo if it matters. I double checked and our piral-base, piral-core are in the same version. 

I tried to upgrade manually from 0.13.0 to [0.13.1](https://github.com/smapiot/piral/releases/tag/v0.13.1) to see what would happen and it complained about some tslib missing operators (I checked and it had a bump from ^1 to ^2). 

Then I tried to upgrade piral straight to 0.14.15 it just complained about the above error. 

Our shell package.json looks like this:
``
"dependencies": {
    "@apollo/client": "^3.3.6",
    "@aws-amplify/analytics": "^4.0.17",
    "@ourApp/common": "^2.0.0-alpha.9",
    "@ourApp/graphql": "^1.10.0-alpha.9",
    "@ourApp/icons": "^1.10.0-alpha.9",
    "@ourApp/ui": "^1.10.0-alpha.9",
    "@material-ui/core": "4.12.1",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.60",
    "aws-amplify": "^3.3.3",
    "aws-appsync-auth-link": "^3.0.3",
    "aws-appsync-subscription-link": "^3.0.5",
    "aws-sdk": "^2.1039.0",
    "clsx": "1.1.1",
    "graphiql": "^1.4.0",
    "graphql": "15.4.0",
    "graphql-tag": "2.11.0",
    "lodash": "^4.17.21",
    "loglevel": "^1.7.1",
    "luxon": "1.25.0",
    "moment": "2.29.1",
    "piral-configs": "0.14.15",
    "piral-containers": "0.14.15",
    "piral-core": "0.14.15",
    "piral-lazy": "0.14.15",
    "piral-redux": "0.14.15",
    "polished": "3.6.7",
    "query-string": "^6.14.1",
    "react": "16.14.0",
    "react-apollo": "^2.1.9",
    "react-dom": "16.14.0",
    "react-ga4": "^1.4.1",
    "react-helmet": "6.1.0",
    "react-router": "5.2.0",
    "react-router-dom": "5.2.0",
    "react-toastify": "6.1.0",
    "uuid": "8.3.1"
  },
  "devDependencies": {
    "@ourApp/git-commit": "^1.0.1-alpha.9",
    "@ourApp/release-config": "^1.1.0-alpha.9",
    "@types/lodash": "^4.14.167",
    "@types/node": "^16.9.0",
    "@types/react": "^16.8.0",
    "@types/react-dom": "^16.8.0",
    "@types/react-router": "^5.1.8",
    "@types/react-router-dom": "^5.1.5",
    "piral-cli": "0.14.15",
    "piral-cli-webpack": "0.14.15",
    "rimraf": "^3.0.2",
    "semantic-release": "^17.4.1",
    "typescript": "4.2.4"
  }
  ``

**Comment by FlorianRappl** [comment]
I think we are getting closer here. What's your target (ES x?) and what is your version of TypeScript and tslib?

How are pilets loaded in your case? It seems that the pilets meta data is not extensible. If standard `fetch` would be used that should still be the case - so I'm wondering if we have some customization here.

The line in question is https://github.com/smapiot/piral/blob/e47522b04552ba56fbdddcf8b53434d3329da1c1/src/framework/piral-base/src/utils.ts#L24 where it should be used (in your case) from https://github.com/smapiot/piral/blob/e47522b04552ba56fbdddcf8b53434d3329da1c1/src/framework/piral-base/src/umd.ts#L16 ultimately originating at https://github.com/smapiot/piral/blob/e47522b04552ba56fbdddcf8b53434d3329da1c1/src/framework/piral-base/src/load.ts#L50.

**Comment by Alellujah** [comment]
My target is es6, typescript version 4.2.4 and tslib I haven't specified in my package.json for the shell but I'm using ^2.3.0 in all the pilets, probably it would be a good idea to specify it also in the app shell? 

We are requesting the pilets via GraphQL, which queries a DinamoDB table and returns a list of plugins.

**Comment by FlorianRappl** [comment]
> We are requesting the pilets via GraphQL, which queries a DinamoDB table and returns a list of plugins.

Yeah I think this is it. I guess you use then something like apollo or similar, which seems to return an immutable object.

A quick fix would be to copy that to an ordinary object, e.g., use something like `piletResponse.map(r => ({ ...r }))` where `piletResponse` is the array of pilet meta data that you return right now from the `requestPilets` function.

**Comment by Alellujah** [comment]
Exactly, that fixed this issue. Thank you so much for your help!

**Comment by FlorianRappl** [comment]
Thanks for confirming!

In 0.15 we don't have this issue as new meta is produced anyway (and not mutated as right now). Still, I'd this to be fixed in 0.14, too - so we patch this in a hotfix and then you don't need to do the workaround.
