### ISSUE TITLE
Lazy load angular/importmaps from pilet

### ISSUE THREAD

**Issue by whilke** [smapiot/piral#498]
Is it possible to lazyload angular through importmaps once landing on a pilet router (/sample) ?

I'm able to get angular into importmaps and loaded as shared dependencies between pilets, without being referenced directly in the shell (easy with just setting up the correct importmap)

Now I'm trying to see if I can delay the loading of angular completely until a pilet is loaded via a route. I've tried using piral-lazy, but can't get it working around the fact that defineNgModule has to get loaded in the pilet setup(), and I can't get fromLazy() working with a angular app component that has to get wrapped with fromNg().

Any general advice, or is it not possible?

**Comment by FlorianRappl** [comment]
From Gitter:

> Yes, it's possible but a bit tricky as the pilet's root module ("index.tsx", i.e. where the `setup` is located) should then not contain any direct or indirect import of `@angular/*`, which includes not using `piral-ng/convert`.

I can make a quick sample - I just don't know if I manage to do it today. Will update this one here once its ready.

**Comment by FlorianRappl** [comment]
I've finished the sample at [piral-samples/angular-lazy-loading](https://github.com/piral-samples/angular-lazy-loading).

With the given instructions you can make the shared dependency lazy loading also work with Webpack. I'm not sure if there is something here that we can do / improve automatically with Webpack, but I'm sure we can maybe add something like a `piral-ng/lazy-convert` (and similar for other converters) convenience module, which would pretty much give you the right experience without much trouble.
