### ISSUE TITLE
Dependency type not correctly copied when generating AppShell index.d.ts

### ISSUE THREAD

**Issue by EclipseZA** [smapiot/piral#519]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x ] Are you running the latest version?
- [x ] Did you perform a search in the issues?

## Environment Details and Version
Windows 10.
piral-cli 0.14.25
piral-cli-webpack 0.14.25 (This also occurs using piral-cli-webpack5)

## Description

I've encountered an issue when building my Shell's emulator package. I received warnings during the generation of the declaration file stating that it could not resolve a type on a dependency package I use.

Comparing the type in the shell's index.d.ts against the original types.d.ts file in the package's node_modules folder shows that properties are removed from the type when the Shell's index.d.ts file is generated.

The dependency package in question is @rematch/core, but I suspect the issue lies with the dets package, which is used to generate the index.d.ts

Below is an example of a comparison between the original types.d.ts against the generated Shell index.d.ts:
Note: I've formatted this for readability.

Original types.d.ts:
```typescript
declare type ExtractParameterFromEffect<
    P extends unknown[], 
    V extends 'payload' | 'meta'
> = P extends [] 
    ? never 
    : P extends [p?: infer TPayload, s?: unknown] 
    ? V extends 'payload' 
        ? P extends [infer TPayloadMayUndefined, ...unknown[]] 
            ? [p: TPayloadMayUndefined] 
            : [p?: TPayload] 
        : never 
    : P extends [
        p?: infer TPayload,
        s?: unknown,
        m?: infer TMeta,
        ...args: unknown[]
    ] 
    ? V extends 'payload' 
        ? P extends [infer TPayloadMayUndefined, ...unknown[]] 
            ? [p: TPayloadMayUndefined] 
            : [p?: TPayload] 
        : P extends [unknown, unknown, infer TMetaMayUndefined, ...unknown[]] 
        ? [m: TMetaMayUndefined] 
        : [m?: TMeta] 
    : never;
```

Generated index.d.ts:
```typescript
export type ExtractParameterFromEffect<
    P extends Array<unknown>, 
    V extends "payload" | "meta"
> = P extends [] 
    ? never 
    : P extends [, ] 
    ? V extends "payload" 
        ? P extends [infer TPayloadMayUndefined, ...Array<unknown>] 
            ? [] 
            : [] 
        : never 
    : P extends [
        , 
        , 
        , 

    ] 
    ? V extends "payload" 
        ? P extends [infer TPayloadMayUndefined, ...Array<unknown>] 
            ? [] 
            : [] 
        : P extends [unknown, unknown, infer TMetaMayUndefined, ...Array<unknown>] 
        ? [] 
        : [] 
    : never;
```

Notice how properties are missing in the generated file resulting in invalid syntax

## Steps to Reproduce

I have created a minimum reproducible example here: https://github.com/EclipseZA/Piral-Rematch-MRE.
Its readme provides steps to reproduce, as well as comparisons between the @rematch/core types and those generated in the Shell's index.d.ts

## Expected behavior

The type should not be missing properties after index.d.ts file generation.

## Actual behavior

Type is not resolved correctly, resulting in warnings.
Type is missing properties in the generated index.d.ts resulting in invalid syntax.

## Possible Origin / Solution

I'm not sure on how to go about fixing this, but I suspect the issue lies with the dets package used to build the index.d.ts

**Comment by FlorianRappl** [comment]
If there is such an issue then its in dets as you mentioned.

Unfortunately, I cannot transfer the issue as dets is in a different organization.

**Comment by EclipseZA** [comment]
Hi Florian. 
Thanks for the update.
I'll add it to the dets issues board when I get a chance.

**Comment by FlorianRappl** [comment]
Well we can leave it open as a reminder to update dets once fixed there.

**Comment by FlorianRappl** [comment]
`dets` is updated explicitly in 0.15 and implicitly in previous versions.
