### ISSUE TITLE
Make HMR port configurable

### ISSUE THREAD

**Issue by mingfang** [smapiot/piral#523]
Currently the HRM port is hardcoded to 62123 here https://github.com/smapiot/piral/blob/036cb83c1f1797a833edbcc9a7fd698a926aedd2/src/tooling/piral-cli-webpack5/src/webpack/piral.ts#L87

Due to our network's configuration we can not use this port.
The problem can be resolved by making the HRM port configurable.

**Comment by FlorianRappl** [comment]
Yes, we can do that.
