### ISSUE TITLE
Compare and contrast Piral with other frameworks

### ISSUE THREAD

**Issue by L1lith** [smapiot/piral#529]
# New Feature Proposal

A page that details why to use Piral vs x (see [here for inspiration](https://docs.astro.build/en/comparing-astro-vs-other-tools/))

## Description

I thought this would be useful to me (and other people) because I have experience with a lot of frameworks (like Next, Gatsby, and now primarily Astro). To me it's not clear exactly what advantage Piral provides over these solutions, and was wondering what specifically qualifies as a "micro-frontend". Astro creates extremely small bundles with isolated components, would this also be a microfront-end like Piral, and are they functionally different?

**Comment by FlorianRappl** [comment]
> Astro creates extremely small bundles with isolated components, would this also be a microfront-end like Piral, and are they functionally different?

The question is if you can develop those bundles independently. Piral is a framework for micro frontends, i.e., the development of an UI with different teams (completely separated, not sharing a codebase).

I think you may have missed the comparison page: https://docs.piral.io/reference/documentation/features

Hope that helps!
