### ISSUE TITLE
children prop missing in piral-core PortalProps interface

### ISSUE THREAD

**Issue by AgilityHarman** [smapiot/piral#530]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version
Piral-core: 0.14.29
React: 18.2.0
OS: Windows 10
Browser: MicroSoft Edge Version 103.0.1264.71 (64-bit)

## Description
This is related to children prop missing in piral-dashboard, piral-core PortalProps interface 
link (related to updates-to-typescript-definitions React v.18): https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions

[Description of the bug]
  Property 'children' does not exist on type 'IntrinsicAttributes & PiralProps'.

## Steps to Reproduce

1. TypeScript project with React v.18 
2. Create PiralInstance with required props to render
3. Issue will start appearing for Piral  as mentioned in Description of the bug.

## Expected behavior

piral-core interface PortalProps should support children props

## Actual behavior
children props is missing in piral-core's interface PortalProps 

## Possible Origin / Solution

children prop can be added for ReactElement in piral-core's interface PortalProps.

**Comment by FlorianRappl** [comment]
Yeah it's not really a bug - as the TS definitions of React have changed (like you noted). Actually anyone can select the version of typings and even in case of v18 of the typings you may want to just add that prop.

Additionally, the v0.15 (pre-release) already has updated definitions (I'd recommend using 0.15 preview if you want to use React 18). So I'll close this one.
