### ISSUE TITLE
kras configuration broken

### ISSUE THREAD

**Issue by cloeffl** [smapiot/piral#532]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Piral 0.14.29

## Description

After upgrading from Piral 0.14.23 to 0.14.29 the mock server is no longer working as expected. Scripts in the mocks directory are not getting loaded. Spinning up a new instance with the default template also does not allow to use the provided mock at /api/posts

## Steps to Reproduce

1. npx -p piral-cli piral new --template default
2. npm start
3. open http://localhost:1234/api/posts in a browser

## Expected behavior

Mock data is returned

## Actual behavior

The Piral Instance is loaded.

## Possible Origin / Solution

Accessing kras frontend shows that no scripts are loaded.

**Comment by FlorianRappl** [comment]
Alright, thanks for the info.

We stopped generating a default directory, I guess we should include that again.

In the meantime you can create a `.krasrc` file next to the package.json and put, e.g.,

```json
{
    "injectors": {
        "script": {
            "directory": "src/mocks"       
        }
    }
}
```

in there. This will tell kras to use the `src/mocks` directory as a source for the script injector.
