### ISSUE TITLE
Navigation with the Angular Router to the base url

### ISSUE THREAD

**Issue by kevinkasper** [smapiot/piral#535]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral / piral-ng 0.14.29

## Description

When navigating to the base url ("/") with the Angular Router, the url in the address bar is changed, but the same content is displayed as before.

## Steps to Reproduce

1. Create a Pilet
2. Integrate Angular (piral-ng)
3. Reigster two pages ("/" and "/foo") with registerPages()
4. Navigate within the "/foo" page to the "/" page with the Angular Router

## Expected behavior

The url of the address bar is changed to "/" and the content of the corresponding registered page is displayed.

## Actual behavior

The url of the address bar is changed to "/" and the content of previous page is displayed.

Caution - If a url is used that is not equal to the base url, navigation will work as desired.

**Comment by kevinkasper** [comment]
The problem still exists in Version 0.1.31

**Comment by FlorianRappl** [comment]
Please have a MWE. Keep in mind that your Angular Router setup needs to be well-defined. If you go to the homepage without having the currently routed page in there then you'll have an issue.
