### ISSUE TITLE
docs: fix typo in extensions register example

### ISSUE THREAD

**Issue by sanketphansekar** [smapiot/piral#536]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

N/A

## Description
Change the implementation for reading params in register method in documentation.
https://docs.piral.io/guidelines/tutorials/12-sharing-between-pilets#components

## Steps to Reproduce

1. Check the documentation here https://docs.piral.io/guidelines/tutorials/12-sharing-between-pilets#components

## Expected behavior

[What you expected to happen]

## Actual behavior
It is not able to read the props passed to the component

## Possible Origin / Solution

Read params property from the object
```js
export function setup(piral: PiletApi) {
  piral.registerExtension('sample-ext-name', ({ params })=> {
    if (typeof params.value !== 'number') {
      console.warn('You need to provide a param "value" with a <number>.');
      return null;
    }

    return <div>All good!</div>;
  });
}
```

**Comment by FlorianRappl** [comment]
For such small things it would be better to immediately create a PR instead of opening a bug report.

Potentially less work for you and even less work for us. Hence, please create a PR! Thanks!

**Comment by sanketphansekar** [comment]
I'll raise a PR. Thanks, please assign it to me.
