### ISSUE TITLE
krasrc and pnpm

### ISSUE THREAD

**Issue by turnerguo** [smapiot/piral#564]
# Bug Report

I'm using `pnpm` monorepo to manage Piral Shell under `packages/my-app`, and also I use `vite` as the bundler, the structure looks like:

```js
// project root
root
  - packages
    - my-app
      - src
    - .krasrc
    - vite.config.js

// .krasrc
{
  "name": "kras",
  "port": 6600,
  "host": "dev.mydomain.com",
  "ssl": {
    "cert": "../../.cert/wildcard.mydomain.com.crt",
    "key": "../../.cert/wildcard.mydomain.com.key"
  },
  "injectors": {
    "script": {
      "active": true,
      "directory": "public"
    }
  }
}

// vite.config.js
module.exports = function (config) {
  // ...
  config.server = {
    host: 'dev.mydomain.com',
    port: 6600
  };

  return config;
}

```

with the configurations I always get response like:

```bash
ℹ 🚀  Running at https://localhost:1234/
ℹ 🔧  Manage via https://localhost:1234/manage-mock-server
vite v2.9.15 building for production...

watching for file changes...

build started...
Bunding ...
✓ 0 modules transformed.
```

I either tried modify `host`/`port` in `.krasrc` and `vite.config.js` file and restart `piral debug`, but no one brings any changes, I think the `kras` server may hijack the configurations?

**Comment by FlorianRappl** [comment]
Well, the `port` is anyway a Piral CLI config so nothing to be done here by kras. I see that the dev server runs on HTTPs, i.e., your krasrc is applied.

I miss a [MWE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) and a specific bug report (actual behavior / expected behavior). From what I see the outcome may be the expected behavior, but I am not sure.

I tried to make the title more appropriate.

**Comment by turnerguo** [comment]
OK, let me try to describe this more detailly:
1. when we use the `bundler` like `vite` in a common way like this:
```js
// vite.config.js
module.exports = function (config) {
  // ...
  config.server = {
    host: 'dev.mydomain.com',
    port: 6600
  };

  return config;
}
```
the dev server will started with expected `host` and `port`:
```bash
ℹ 🚀  Running at https://dev.mydomain.com:6600/
vite v2.9.15 building for production...

watching for file changes...
```

2. when I try to custom the `host` and `port` in `piral debug`, I'm trying to modify `.krasrc` like this:
```js
// .krasrc
{
  "name": "kras",
  "port": 6600,
  "host": "dev.mydomain.com",
  "ssl": {
    "cert": "../../.cert/wildcard.mydomain.com.crt",
    "key": "../../.cert/wildcard.mydomain.com.key"
  },
  "injectors": {
    "script": {
      "active": true,
      "directory": "public"
    }
  }
}
```
the dev server will be started with unexpected `host` and `port`:
```bash
ℹ 🚀  Running at https://localhost:1234/
ℹ 🔧  Manage via https://localhost:1234/manage-mock-server
vite v2.9.15 building for production...

watching for file changes...
```
  
So, the expectation is to have a way to use my customized dev server config like `webpack` `vite` does, it provided a way to let developer to custom their `dev server` configurations, but I didn't found anywhere to do this.

**Comment by FlorianRappl** [comment]
As mentioned your expectation is wrong here. Piral runs its own dev server (I mean you run `piral debug` or `pilet debug` not a respective `kras` or `vite` command). Also, your expectation *cannot* be the right one - as the mentioned scenario would be a conflict (let's say you configured it in both, `kras` and `vite` - which port should be taken?).

So I think the issue is rather the misconception that all settings still apply - they don't.

**Comment by turnerguo** [comment]
> As mentioned your expectation is wrong here. Piral runs its own dev server (I mean you run `piral debug` or `pilet debug` not a respective `kras` or `vite` command). Also, your expectation _cannot_ be the right one - as the mentioned scenario would be a conflict (let's say you configured it in both, `kras` and `vite` - which port should be taken?).
> 
> So I think the issue is rather the misconception that all settings still apply - they don't.

I think you has some misunderstanding, I mean I have tried both way but no configuration was taken.
And I saw the `port` `host` configuration options in `.krasrc` documentation, but actually not worked, so it might a bug.
Anyway, hopes it would help.

**Comment by FlorianRappl** [comment]
No I understood fine - as mentioned you want to use settings in these files which are not supported as these are overridden by the Piral CLI. This is not a bug - but the intended way.
