### ISSUE TITLE
How can custom plugin generated d.ts be included in the PiletApi interface api ？

### ISSUE THREAD

**Issue by jiechud** [smapiot/piral#565]
## Description
I made a custom Piral plugin 【Piral-page】

The generated dist file
![image](https://user-images.githubusercontent.com/9709396/206461480-566033f4-eddd-41ff-847f-affc7c77ac9c.png)

`create.d.ts` content is

```

interface PiletTestApi {
     addXXX(): void;
      removeXXX(): void;
}

import { PiralPlugin } from 'piral-core';
import type { PiletTestApi } from './types';
/**
 * 
 */
export declare function createPageApi(): PiralPlugin<PiletTestApi>;

```

 In the shell 。I use this plugin

```

import { createPageApi } from 'piral-page';

const instance = createInstance({
  state: {
    components: layout,
    errorComponents: errors,
  },
  plugins: [createPageApi()],
  requestPilets() {
     return fetch(feedUrl)
       .then((res) => res.json())
       .then((res) => res.items);

  },
});
```

I execute `piral declaration` cmd

Generate `index.d.ts` ,  There is no PiletTestApi interface  in piletApi interface

## Discussion

What do I do to generate it into the piletApi interface ？

**Comment by FlorianRappl** [comment]
This is explained in the docs (https://docs.piral.io/guidelines/tutorials/05-customizing-the-api), in particular:

```ts
declare module 'piral-core/lib/types/custom' {
  interface PiletCustomApi extends PiletTrackingApi {}
}
```

Does that help you?

Also see sources (every plugin uses this pattern), e.g., from https://github.com/smapiot/piral/blob/develop/src/plugins/piral-adal/src/types.ts:

```ts
declare module 'piral-core/lib/types/custom' {
  interface PiletCustomApi extends PiletAdalApi {}
}

export interface PiletAdalApi {
  /**
   * Gets the currently valid access token, if any.
   */
  getAccessToken(): Promise<string | undefined>;
}
```
