### ISSUE TITLE
Pilet Scaffolding: configurable destination path for copying files from Piral instance

### ISSUE THREAD

**Issue by lschoett** [smapiot/piral#58]
## Description

For the Pilet scaffolding files can be added to the Piral instance and referenced in the package.json file. The files will be copied as part of the scaffolding process to the same destination path as the are located in the Piral instance.

The scaffolding process should support that the destination for the files in the new Pilet can be configured.

## Background

This enhancement would add further flexibility in customising the scaffolding of Pilets based on the Piral instance.

**Comment by FlorianRappl** [comment]
The approach that was discussed earlier would be to allow either

- Simple strings (relative path from source in Piral instance root, will be relative path to target in Pilet root), or
- Objects using `{ from: string, to: string }` format, where both parts can be specified independently

in the `files` part of the `pilets` section in the *package.json* of the respective Piral instance.

Any other ideas or comments?

**Comment by lschoett** [comment]
My suggestion would be to use the second approach with the object. This will give more flexibility for the scaffolding and the files for the Pilets can be separated into a dedicated "scaffolding" folder within the Piral instance.

**Comment by FlorianRappl** [comment]
> My suggestion would be to use the second approach with the object. This will give more flexibility for the scaffolding and the files for the Pilets can be separated into a dedicated "scaffolding" folder within the Piral instance.

Sorry my bad. In the sentence above *either* mean that *both* approaches can be used (the plain string is the current one, so the object would be an *added* alternative).

If you would opt in for exclusively the object I have my doubts due to

- breaking change in a config file (very bad)
- too verbose for direct copies (currently supported scenario)

**Comment by FlorianRappl** [comment]
Landed in `devel`.
