### ISSUE TITLE
Enable HMR when not running on localhost?

### ISSUE THREAD

**Issue by Altneuj** [smapiot/piral#583]
We are proxying the bundles/emulator served by `pilet debug` command onto our webapp (shell) that is not running on localhost. Not running on localhost is needed for many reasons, one being to avoid CORS issues with our APIs. This works well except for HMR breaking due to the assumption that this will be the same origin as our pilet https://github.com/smapiot/piral/blob/d1a8b8ff89b879002aaf5ec91e0aa5772393162c/src/tooling/piral-cli/src/injectors/pilet-injector.ts#L93

`headers.origin` will resolve to our webapp url instead of `localhost:4321` (for example)

it is possible to instead derive this baseUrl from the 'dbg:pilet-api' to make sure we hit the correct pilet get route or is there something I am potentially missing?

Thank you!

**Comment by FlorianRappl** [comment]
Yeah we thought about the URL restriction, however, not restricting it would mean that the extension essentially starts for every website. This is something that I find personally, as a user, too obtrusive. It's unfortunate that this setting cannot be changed / handed over into the hands of the end-user (i.e., make the URL restriction just a starting value, but leave the exact behavior / URLs up to the end-user). Maybe this is possible, but I do not know enough of the extension manifest here.

Regarding the name of the config ... naming is hard, so I'd guess something like `assetBaseUrl` could be a good name (open for discussion / change here).

This would be a config for the pilet injector, e.g., it would look like

```
{
  "injectors": {
    "pilet": {
      "assetBaseUrl": "http://custom-domain.com/pilet"
    }
  }
}
```

**Comment by Altneuj** [comment]
yeah I was looking into the same with the manifest and there doesn't seem to be a _great option_ currently for defaulting to a URL and then allowing others. Maybe I will poke around at it eventually. 

I am going to go ahead and write up a PR for the config change. Thanks very much!

**Comment by FlorianRappl** [comment]
This is now in and called `assetUrl`:

```json
{
  "injectors": {
    "pilet": {
      "assetUrl": "http://custom-domain.com/pilet"
    }
  }
}
```

It also goes beyond the WebSocket and transforms the meta response, too.
