### ISSUE TITLE
The schemaVersion in pilet.json doesn't work

### ISSUE THREAD

**Issue by BenjaminSchwendner** [smapiot/piral#585]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

`0.15.7`

## Description

According to the documentation (https://docs.piral.io/reference/documentation/C31-pilet-metadata) it should be possible to define the `schemaVersion` in the `pilet.json` file. But when I do so it doesn't seem to be considered during the build, and the build is still using v2, no matter what I configure in the `pilet.json`. Am I missing something?
It works, when I use the `--schema` parameter on the build command, but I would rather like to use the `pilet.json`, so I don't need to make sure I'll add (and maintain) it to all the different build commands that I have. Also I was hoping that the `pilet.json` schema definition would also be respected for each pilet individually also when running a `pilet debug` with a wildcard like `pilet debug packages/*-pilet`.

## Steps to Reproduce

1. Create a `pilet.json` and define a `schemaVersion` different than `v2`
2. Run `pilet build`

## Expected behavior

The built bundle should be using the specified schema version.

It should also consider the `schemaVersion` of each package when running a `pilet debug` using a wildcard like `pilet debug packages/*-pilet`.

## Actual behavior

The bundle is always using the `v2` schema.

## Possible Origin/Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Landed in preview.

**Comment by BenjaminSchwendner** [comment]
I gave it a test and it works as expected. 👍 
Thanks so much for the quick fix! 🍻
