### ISSUE TITLE
Typo in Code Gen

### ISSUE THREAD

**Issue by dbauswel** [smapiot/piral#599]
https://github.com/smapiot/piral/blob/6d97a2baca7ae3e5fb19a754ba55d44b40ed137e/src/framework/piral-core/app.codegen.d.ts#L1

This has got to be at typo.
`import type { LoadPiletsOptions } from 'prial-base';`

**Comment by FlorianRappl** [comment]
Thanks - indeed. Want to make a PR?

**Comment by dbauswel** [comment]
https://github.com/smapiot/piral/pull/600
