### ISSUE TITLE
Piral.Blazor Extension Duplication

### ISSUE THREAD

**Issue by MarioBolivar** [smapiot/piral#602]
- [Piral.Blazor-Extensions-Issue](#piralblazor-extensions-issue)
- [Bug Report](#bug-report)
  - [Environment Details and Version](#environment-details-and-version)
- [Description](#description)
- [Steps to Reproduce](#steps-to-reproduce)
  - [Expected behavior](#expected-behavior)
  - [Actual behavior](#actual-behavior)
  - [Supporting Repo](#supporting-repo)

# Piral.Blazor-Extensions-Issue
This repo reproduces a Piral.Blazor `<Extension/>` duplication issue

# Bug Report
## Environment Details and Version
OS: Windows 10 version 22H2 (Build 19045.2728)
.NET 6
Piral.Blazor versions
- Piral.Blazor.DevServer 6.0.7
- Piral.Blazor.Utils 6.0.7
- Piral.Blazor.Tools 6.0.7
Browser: Chrome Version 111.0.5563.147

# Description
There currently exists an issue with Piral Blazor Extensions `<Extension/>` where nested extension components are duplicating exponentially as the number of nested layers grows. This is causing runtime issues where pages and components are incorrectly rendering.

# Steps to Reproduce
- Open sample Blazor pilet repo (https://github.com/MarioBolivar/Piral.Blazor-Extensions-Issue) with reproduction setup and run with debugging (F5) through the default IIS Express profile
- Navigate to `/extensionsissue`
- By default, only one nested extension component is enabled. You can uncomment Nested Extensions C-D to see the problem exacerbate.

## Expected behavior
When registering nested piral blazor extensions `<Extension/>`, these extensions should render correctly within one another.

## Actual behavior
When registering nested piral blazor extensions `<Extension/>`, these extensions render incorrectly and are duplicated. This issue is exacerbated as the number of nested extensions/layers grows.

## Supporting Repo:
Please go to [this](https://github.com/MarioBolivar/Piral.Blazor-Extensions-Issue/tree/master#environment-details-and-version) (https://github.com/MarioBolivar/Piral.Blazor-Extensions-Issue/tree/master#environment-details-and-version) repo that is setup to easily reproduce this issue.
**Note: The README in the repo also provides some additional helpful information**

**Comment by FlorianRappl** [comment]
This issue occurs with nested extensions by not cancelling the rendering event (i.e., propagation is not stopped and every boundary also renders...). We'll fix this with the 0.15.13 release (to be released by Monday). Thanks for reporting!

**Comment by MarioBolivar** [comment]
Thank you for your help and blazing fast remediation, @FlorianRappl! Kudos to you! 😄 🎉
