### ISSUE TITLE
Dynamic title for breadcrumbs

### ISSUE THREAD

**Issue by kevinkasper** [smapiot/piral#610]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

I currently have the requirement that the title of the breadcrumbs should be built dynamically using an url with named parameters.

Unfortunately, this is not currently possible, as only static titles are possible:

```ts
api.registerBreadcrumb({
    path: '/customers/:customerId',
    title: 'Customer'
});
```

I would like to define the breadcrumbs as follows:

```ts
api.registerBreadcrumb({
    path: '/customers/:customerId',
    title: ({ params }) => <span>Customer - { params.customerId }</span>
});
```

Is there already such an implementation or a workaround?

## Background

A similar behaviour has already been implemented for registering pages and works great:

```ts
api.registerPage(
    '/customer/:customerId',
    ({ match }) => <h1>Customer - { match.params.customerId }</h1>
);
```

**Comment by FlorianRappl** [comment]
Yeah we can introduce that - sounds fair. Do you want to make a PR or should we keep it in the backlog?

**Comment by kevinkasper** [comment]
Feel free to add it to your backlog. Unfortunately, I'm not enough of a React expert for this.

Many thanks in advance! 😊

**Comment by Flouwrian** [comment]
I´ll start working on this issue
