### ISSUE TITLE
Extend documentation for ErrorInfoProps

### ISSUE THREAD

**Issue by robert-gruner** [smapiot/piral#65]
# New Feature Proposal

No new feature - just more detailed documentation.

## Description

It would be great if you could extend the documentation regarding PageError, FeedError etc. so that it explains exactly when this type of error occurs. 

## Background

We as shell application developers want to provide a dedicated component which takes care of error presentation. To be able to test all the error cases which are handled by piral we have to know why and when they occur.

## Discussion

For NotFoundError it is pretty clear - so it would for example just say: “This error is shown if the user navigates to a route/page which is not registered.” But for the other cases it is not obvious when they occur. At the end it would be enough if you could at least extend the explanations in the components.ts file.

**Comment by FlorianRappl** [comment]
Landed in `develop`.
