### ISSUE TITLE
How do I configure this with Nuxt 3? Unable to setup

### ISSUE THREAD

**Issue by ashish141199** [smapiot/piral#669]
There is no index.html or main.ts or index.ts. The entrypoint is app.vue directly (as mentioned in the Nuxt 3 docs). 

I love the Piral.io project and idea. Would want to implement this in nuxt 3. Kindly help.

**Comment by FlorianRappl** [comment]
Hi this is not (directly) compatible with Nuxt. You can either wait for Piral v2 which should be rather easy / if not directly to integrate or try an integration based on `piral-base`. Anything else (e.g., using `piral-core` or any template that is usually based on `piral` / `piral-core`) will not work as the assumptions don't match.

Hope that helps!

**Comment by FlorianRappl** [comment]
I've added Nuxt to the v2 presets #628.

**Comment by ashish141199** [comment]
Okay! Thank you for the quick response. Any timeline on the v2?

**Comment by FlorianRappl** [comment]
Part of it (regarding the islands-composition / based on our [demo with SSR and islands](https://github.com/piral-samples/netflix-islands-demo)) is already in private preview, but its unclear when we'll have a public preview - especially with all of the presets.

I'd say in Q2 / 2024 we'll enter that stage.
