### ISSUE TITLE
In the app-shell example debugging mode, saving package.json will prompt that the port is used

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#671]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://github.com/smapiot/piral)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

- macos
- vscode
- node@18

## Description

In the app-shell example debugging mode, saving package.json will prompt that the port is used. Continue to save component files, webpack will perform multiple compilations

## Steps to Reproduce

1. `yarn && yarn build && cd src/samples/minimal-piral && npx -y piral debug`
2. Press the `command + s` shortcut key to save the `src/samples/minimal-piral/package.json` file
<img width="935" alt="image" src="https://github.com/smapiot/piral/assets/5674761/2333bffb-c6ee-4b4b-b0d2-fde5959c0822">
3. Press the `command + s` shortcut key to save the `src/samples/minimal-piral/src/index.tsx` file
<img width="952" alt="image" src="https://github.com/smapiot/piral/assets/5674761/b1f2ed67-e5f1-46af-9281-fe2ece312863">

## Expected behavior

1. Always use the specified port number
2. webpack always builds only once

## Actual behavior

1. prompt that the port is used
2. webpack performs multiple builds

## Possible Origin/Solution

Is the piral-cli watcher did not reset the hmr watcher when restarting the pilet build? Some vscode plug-ins will modify package.json, thereby triggering the execution of the piral-cli watcher callback function?

![2024-02-04_23-11-08 (2)](https://github.com/smapiot/piral/assets/5674761/5a8aa807-a8e2-40af-9fd1-ccff61f535d6)

**Comment by FlorianRappl** [comment]
Thanks for the report. A fix for this is out with the latest preview (`next`).

**Comment by carvinlo** [comment]
I tested and it was fixed, thank you!

**Comment by carvinlo** [comment]
There are the same problem with using `pilet debug` command in a monorepo. See the [mwe](https://github.com/carvinlo/piral/tree/pilet-debug-mwe)

Environment Details and Version
piral-cli@1.5.0-beta.6684

Expected behavior
webpack always builds only once

Actual behavior
webpack performs multiple builds

1. `yarn && yarn build && cd src/samples/sample-pilet && yarn start`
2. Press the command + s shortcut key to save the src/samples/sample-pilet/package.json file
3. Press the `command + s` shortcut key to save the `src/samples/sample-pilet/src/index.tsx` file
<img width="1249" alt="image" src="https://github.com/smapiot/piral/assets/5674761/004471c7-eca2-43f0-bdf8-e332cf5f030a">

**Comment by FlorianRappl** [comment]
We restart the process independent of what the bundler does. So in case of Webpack it might be sensitive to the package.json, however, this is nothing we control or will change.

If this edge case really impacts you (how?) then configure webpack to ignore the package.json. I think this is rather a cosmetic issue and for reliability it makes more sense that we restart the process than having just a single build here.

**Comment by carvinlo** [comment]
> We restart the process independent of what the bundler does. So in case of Webpack it might be sensitive to the package.json, however, this is nothing we control or will change.
> 
> If this edge case really impacts you (how?) then configure webpack to ignore the package.json. I think this is rather a cosmetic issue and for reliability it makes more sense that we restart the process than having just a single build here.

I completely agree with your idea, but the repeated build may be related to not restarting webpack when restarting the pilet process. After testing, [pr](https://github.com/smapiot/piral/pull/675) fixed this problem. But since I don’t fully understand the logic of piral, I don’t know if [pr](https://github.com/smapiot/piral/pull/675) is reasonable.

**Comment by FlorianRappl** [comment]
Actually it is very reasonable. Thanks for spotting - with my answer I thought we already spot it and what you see is the triggering beforehand, but actually the bundler process keeps on running.

Perfect PR - wonderful!
