### ISSUE TITLE
Navigation storm in angular pilets

### ISSUE THREAD

**Issue by LBraeschke** [smapiot/piral#672]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)? yes https://github.com/LBraeschke/piral-angular-nav-loop-bug/tree/master
- [x] Are you running the latest version? yes
- [x] Did you perform a search in the issues? yes

## Environment Details and Version
Piral 1.4.3
Framework: Angular
OS: Windows 10
Browser Chrome

## Description

[Description of the bug]

## Steps to Reproduce

1. checkout https://github.com/LBraeschke/piral-angular-nav-loop-bug/tree/master
1. go to piral-debug-webpack5 and run npm install
2. build emulator by running piral build --type emulator
3. go to pilet-angular-webpack5 and run npm install
4. run npm run start
5. open browser at http://localhost:1234
6. press the 'To Sharing' link

## Expected behavior

Navigation is only executed 15 times

## Actual behavior

Navigation is executed way more often. It seems it is realted to the computing power of the machine. On faster machine it is way more unlikely to occur and also it resolve faster, after fewer navigations.

![navigation_storm](https://github.com/smapiot/piral/assets/70937123/7aea15bc-584f-4b04-b127-e81d5da1e9a9)

[Optionally, share your idea to fix the issue]
My guess is the [Prial-Ng RoutingService.ts](https://github.com/smapiot/piral/blob/develop/src/converters/piral-ng/src/RoutingService.ts )
```
 const queueNavigation = (url: string) => {
        // I guess this is the problem
        // the navigation frame is not yet available therefore the next router event is also queued and the setup of the navigation storm is completed
        window.requestAnimationFrame(() => nav.push(url));
      };

....
      
      this.subscription = this.router.events.subscribe((e: NavigationError | NavigationStart | Scroll) => {
       const locationUrl = nav.url;
....
       } else if (e.type === 15) {
          const index = skipIds.indexOf(e.routerEvent.id);

          if (index === -1) {
            // consistency check to avoid #535 and other Angular-specific issues
            const locationUrl = nav.url;
            const routerUrl = e.routerEvent.url;

            if (routerUrl !== locationUrl) {
              queueNavigation(routerUrl);
            }
```
My idea would be:
```
let targetUrl: string;
 const queueNavigation = () => {
        window.requestAnimationFrame(() => nav.push(targetUrl));
      };

....
      
      this.subscription = this.router.events.subscribe((e: NavigationError | NavigationStart | Scroll) => {
       const locationUrl = nav.url;
....
       } else if (e.type === 15) {
          const index = skipIds.indexOf(e.routerEvent.id);

          if (index === -1) {
            // consistency check to avoid #535 and other Angular-specific issues
            const locationUrl = nav.url;
            const routerUrl = e.routerEvent.url;

            if (routerUrl !== locationUrl) {
              targetUrl = routerUrl;
              queueNavigation();
            }
```

**Comment by FlorianRappl** [comment]
The preview 1.6.0 contains a suggestion to cancel the animation frame if another request pops in.

Let me know if this works for you @LBraeschke !

**Comment by FlorianRappl** [comment]
Any news here? Otherwise I'll close this one @LBraeschke .
