### ISSUE TITLE
piral-ng: Cannot read properties of null (reading 'bindingStartIndex')

### ISSUE THREAD

**Issue by cmaart** [smapiot/piral#674]
So whatever I seem to do I get this error here:
zone.js:1046 TypeError: Cannot read properties of null (reading 'bindingStartIndex')

![image](https://github.com/smapiot/piral/assets/4008452/6b39ef92-4a3d-4af2-b472-023e849a04c6)

That's how i currently have set up my index.ts for loading into the pilet (import name changed for screenshot only):
![image](https://github.com/smapiot/piral/assets/4008452/17b6386b-42fe-4e6c-952b-520d17bbbda5)

Anyone got an idea what I can do for this? I read online that for this error `preserveSymlink` should be set to true in `angular.json` but seems like this file is not even used by piral?

Massively thankful for any support 🙏

**Comment by FlorianRappl** [comment]
Any update on this one @cmaart ? Otherwise I'll close it.

**Comment by cmaart** [comment]
> Any update on this one @cmaart ? Otherwise I'll close it.

Unfortunately no, tbh for now I gave up on it. Maybe I'll come back to it but for sure closing it is best for now. Maybe someone else also stumbles through here
