### ISSUE TITLE
exports via getDependencies don't work in pilet debug

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#68]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral-core/cli: 0.7.0-pre.637

## Description
I have the following section in the createInstance() call:

```typescript
        getDependencies: extendSharedDependencies({
            'my-piral-instance': require('./exports'),
        }),
```

If a pilet is published normally to the feed service, this dependency is correctly provided from the shell to the pilet. But when using `pilet debug`, it will give the pilet a different instance of this dependency (the referenced by the `main` attribute in the package.json of the shell.

## Steps to Reproduce

1. create a shell, make it export a unique object using the getDependencies as seen above.
2. create a pilet, make it import this object.
3. In the shell and the pilet, store these objects in the window object (say window.piralTest = myExport and window.piletTest = myExport respectively).
4. compare these in the browser console using window.piralTest === window.piletTest when running `pilet debug`. It will show false.

## Expected behavior

There should only be one instance exported to the pilet. The pilet should not get a different import than what the shell exports at runtime.

## Actual behavior

The pilet got served a separate version of the export, which is not the same as the one the shell uses.

**Comment by FlorianRappl** [comment]
I've marked the milestone as 0.8, but we'll try to bring it into 0.7!

**Comment by FlorianRappl** [comment]
This should now be consistent with the new bundling / debugging mode.
Landed in `develop`.
