### ISSUE TITLE
piral-breadcrumbs dependency on react-router v5

### ISSUE THREAD

**Issue by chris-nolan** [smapiot/piral#681]
# Bug Report

The piral-breadcrumbs plugin has a dependency on react-router v5, this makes it incompatible with shells that are using v6.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Piral v1.5.2

## Steps to Reproduce

1. Add react-router v6 as a dependency in a shell
2. Try and use react-breadcrumbs in shell

## Expected behavior

Should be usable with v5 or v6 like other plugins/piral shell

## Actual behavior

Errors occur/plugin not usable

**Comment by FlorianRappl** [comment]
Is part of 1.5.3!

(Please test with the `next` version yourself - in my tests everything seems to be fine with this update; `piral-breadcrumbs` now works independent of React Router / the React Router version.)

**Comment by chris-nolan** [comment]
Awesome! Will check tomorrow.

**Comment by chris-nolan** [comment]
Yep, all good!
