### ISSUE TITLE
Repeat to connect to the server

### ISSUE THREAD

**Issue by carvinlo** [smapiot/piral#687]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

macos
node@18.20.1

## Description

Repeat to connect to the server

## Steps to Reproduce

[MWE](https://github.com/carvinlo/piral/tree/amu/develop-vue3-sample)
1. `yarn && cd src/samples/sample-piral-core && yarn start`
2.  Modify any content of the file `src/samples/sample-piral-core/package.json` and commit to the staging area
![2024-04-15_00-11-15 (1)](https://github.com/smapiot/piral/assets/5674761/12ddd6b1-7740-4bab-ab74-260260e58c75)

## Expected behavior

Do not restart the server repeatedly

## Actual behavior

Repeatedly restart the server

## Possible Origin/Solution

The content of the files `package.json/.krasrc` monitored by fs.watch has not changed, and the server has been restarted.

**Comment by FlorianRappl** [comment]
> The content of the files package.json/.krasrc monitored by fs.watch has not changed, and the server has been restarted.

I don't understand this - the repro steps listen explicitly that the *package.json* should be modified - so yes, with such a modification the server should restart.

I'll have a look with the repro steps, but a server restart is expected if certain files changed (otherwise you'd need to manually shut down the server and restart it again).

**Comment by FlorianRappl** [comment]
Alright, so as this is an edge case (package.json changed, leading to a change for the dev server) we'll exclude it. This implies that changes to the package.json that affect the build (e.g., change of the "app" path) would require a fixed restart. I guess this is a good trade-off, as such scenarios rarely occur and often are expected to come with a manual server restart anyway.

The server would still restart on changes to the krasrc; as it might re-configure the server in crucial areas.

**Comment by carvinlo** [comment]
The server would restart multiple times on changes to the krasrc.
version: 1.5.4-beta.6998
<img width="774" alt="image" src="https://github.com/smapiot/piral/assets/5674761/e772b736-eff6-4682-ad18-969459057c85">

**Comment by carvinlo** [comment]
> The server would restart multiple times on changes to the krasrc. version: 1.5.4-beta.6998 <img alt="image" width="774" src="https://private-user-images.githubusercontent.com/5674761/322894120-e772b736-eff6-4682-ad18-969459057c85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjQ0NDAsIm5iZiI6MTcxMzM2NDE0MCwicGF0aCI6Ii81Njc0NzYxLzMyMjg5NDEyMC1lNzcyYjczNi1lZmY2LTQ2ODItYWQxOC05Njk0NTkwNTdjODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMTQyOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQyZjBiMzU2YmMwNTI1OGQwNzIxMTViMjA2NmExYmMwNjA3ZWI0ZGVhOTJhNDEzMTUxNWZhMjA3MTE0MTEzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XEUrnLnT7mUf2H-DjC-6FM36h9Z033cwrwAZq0IJG_c">

This is also an edge case. This happens when app-shell's webpack.config.js configures a longer build.
But it no longer affects normal development. Thanks for the quick fix.
