### ISSUE TITLE
Validate Command for Piral Instance

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#69]
## Description

Right now the Piral instance is checked in a shallow way to obey to the requirements / spec, e.g., if an `app` key is present (and valid) in the *package.json*.

This should go a bit further and the validation should also be exposed in form of a Piral CLI command, such as `piral validate`.

## Background

If the information, e.g., in `files` is invalid it should be pointed out before scaffolding / running `pilet debug` or similar is tried. It should complain as soon as possible.

## Discussion

What should be verified? Initial guess:

- *package.json* content w.r.t. Piral, such as the `app` field, `pilets` section etc.
- All related files, e.g., if the files in `pilets.files` are valid paths and in case of `app` have a valid content
- Potentially some consistency checks (which ones?)

**Comment by SantoJambit** [comment]
- If a pilets.files directory entry contains subdirectories, issue a warning that it will be shallowly copied?
- If a pilet.files entry contains a .gitignore file (or other file that is not published to npm), issue an error?
- If a pilet.files entry exists, that is not specified in files or maybe specified in .npmignore (i.e. doesn't get published), issue an error?
- Ensure that exported/external dependencies are listed in "dependencies", i.e. not in "devDependencies".
- Maybe a simple schema validation for the pilets part of package.json?

**Comment by FlorianRappl** [comment]
> If a pilets.files directory entry contains subdirectories, issue a warning that it will be shallowly copied?

But that would be rather hostile, right? I mean its the default behavior to leave this out / make a shallow copy (which may be totally desirable). We can make an info output (leaving out "x" files from the subdirectories of) to hint in that direction.

Yep, rest sounds very good - thanks a lot for the fruitful input @SantoJambit !

**Comment by FlorianRappl** [comment]
Landed in `develop`.
