### ISSUE TITLE
Support Standalone Bootstrapping API in piral-ng

### ISSUE THREAD

**Issue by daniel-rck** [smapiot/piral#690]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

In Angular since v15.2 the [standalone bootstrapping API](https://angular.io/guide/standalone-migration#switch-to-standalone-bootstrapping-api) is the default way. That means, there is not `app.module.ts` any more. Also the routing is now defined in a class that is called `ApplicationConfig`, see https://angular.io/guide/router#defining-a-basic-route.

## Background

We would like to stay with the default Angular pattern in the future, so It would be nice if piral-ng support this.

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
This is now available via `piral-ng/standalone`. A dedicated module for creating / converting modern Angular standalone components.
