### ISSUE TITLE
`.krasrc` resolution from `process.cwd()` folder

### ISSUE THREAD

**Issue by yasithA** [smapiot/piral#691]
# New Feature Proposal

## Description

In a monorepo setup, it is likely to have a `.krasrc` file in the project root which applies some config to all pilet projects in the monorepo (i.e. setting the `host` as `::`) so only one time configuration is enough.

At the moment, this must be explicitly given with the `--krasrc` flag.

Would be nice if a `.krasrc` file from the `process.cwd()` directory can be taken by default.

## Background

https://discord.com/channels/1222632475449229352/1230487821677101057

**Comment by FlorianRappl** [comment]
I've pushed an update to the `piral-cli`, which includes the code to consider the current working directory krasrc file, too.

Will be part of the next preview package.

**Comment by FlorianRappl** [comment]
Quick question @yasithA - have you tried the preview version? Does it work for you?

**Comment by yasithA** [comment]
@FlorianRappl I did not yet. Please give me around an hour, will test it and let you know. Is this is the version I should take? 
[1.5.4-beta.7016](https://www.npmjs.com/package/piral-cli/v/1.5.4-beta.7016)

**Comment by yasithA** [comment]
@FlorianRappl Just tested. Working as expected. :) Thanks a lot 🎉

**Comment by FlorianRappl** [comment]
Awesome - thanks for the feedback!
