### ISSUE TITLE
Add "strictPort" configuration property

### ISSUE THREAD

**Issue by peter-at-work** [smapiot/piral#699]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Occasionally, and from external factors, the desired port number for the local server is in-use.  Through the `get-port` npm package, `piral-cli` deals with this by having the local server listen on another random port.

The feature request is a configuration option that would change the server behavior to immediately exit if the desired port is not available.  This is similar to the "strictPort" option introduced in vitejs https://v3.vitejs.dev/config/server-options.html#server-strictport

## Background

When running automated tests, the switch to another random port cannot be readily detected, aside from some indeterminate time limit waiting on the server being available on the desired port number.  An immediate exit on the server with some error code would make this situation immediately detectable and the automated tests can be aborted.

**Comment by FlorianRappl** [comment]
Yes we can add this. I'd propose to call this `--strict-port` with default being false (i.e., `--no-strict-port` is the default); besides the CLI it can be configured via the `.piralrc`, too.

Sounds good?

**Comment by peter-at-work** [comment]
> Yes we can add this. I'd propose to call this `--strict-port` with default being false (i.e., `--no-strict-port` is the default); besides the CLI it can be configured via the `.piralrc`, too.
> 
> Sounds good?

🙏
That is totally fine.  Any which way that the gist of the requested feature can be provided will be helpful to our dev/test workflow.  I really wish I could spare the time writing the PR for this...  just too much other dev work on the table.  We're okay if this gets bumped lower in implementation priority.

**Comment by FlorianRappl** [comment]
Part of the preview for the 1.6.0.

Tested and works.
