### ISSUE TITLE
Validate Command for Pilets

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#70]
## Description

Similar to #69, however, for pilets - `pilet validate`. Besides some obvious checks in the *package.json* (mostly `main`, `devDependencies`, ...) we will check the used version of the Piral instance. If the version can be checked and the currently used version is older than the current one it may yield a warning or negative result.

## Background

Especially CI/CD systems may want a simple way to perform some validation on the pilets before publishing them.

## Discussion

I guess not everyone will agree to all the rules we come up here. Therefore, we could introduce a key in the `pilets` section of the Piral instance's *package.json* - maybe called `validation`. This key could have all the rules specified similar to, e.g., an *eslint.json*. Alternatively, an extra file may be used (*pilint.json*?).

What rules should exist? What could be their values?

Right now I see (up for discussion):

- Checks if the used Piral instance is used at its latest version
  * name: `updated` 
  * values: `required` (otherwise error), `suggest` (otherwise warning), `ignore` (not used)
  * default: `suggest`
- Checks if the used Piral instance is not referenced in the code
  * name: `no-self-reference`
  * values: `active` (check is active), `ignore` (not used)
  * default: `ignore`
- Checks that no other dependencies are bundled in
  * name: `no-third-party-dependency`
  * values: `active` (check is active), `ignore` (not used)
  * default: `ignore`
- Checks that "externals" dependencies have been specified in "peerDependencies".
  * name: `externals-as-peer-dependencies`
  * values: `active` (check is active), `ignore` (not used), maybe `only-used` (only the ones that are used in code)
  * default: `ignore`

The validity of the *package.json* / pilet as a whole is implicit and not exposed as a rule. It will always be validated.

**Comment by SantoJambit** [comment]
- If you are doing code-checking, how are you getting the list of files to check? via tsconfig.json?
- "Checks that no other dependencies are bundled in".. I think if you use this one, an exception list should be possible.
- Checks that "externals" dependencies have been specified in "peerDependencies".
  - name: `externals-as-peer-dependencies`
  - values: `active`  (check is active), `ignore` (not used), maybe  `as-required` (only the ones that are used in code)
  - default: `ignore`

**Comment by FlorianRappl** [comment]
> "Checks that no other dependencies are bundled in".. I think if you use this one, an exception list should be possible.

Right, I think besides `active` and `ignore` we could allow an array, which means "active" with the exceptions as given in the array (type: `'active' | 'ignore' | Array<string>`).

> If you are doing code-checking, how are you getting the list of files to check? via tsconfig.json?

We could do it like that (but this would only work with TS and I would also love to get the JS files if the pilet was not done with TS). I thought of using the bundler to give us the local asset tree, which includes all used (TS) files. We would reduce this graph to the ones below `src` (or not retrieved via `node_modules`).

**Comment by FlorianRappl** [comment]
Landed in `develop`.
