### ISSUE TITLE
--headers not working for pilet-publish 

### ISSUE THREAD

**Issue by akenned8** [smapiot/piral#705]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Pilet version 1.5.3
Mac OS 

## Description

When trying to publish to my own feed service
`npx pilet publish <.tgz file> --url <feed service url> --headers "{\"foo\":\"bar\"}"`
The custom headers I receive are 
```
{
  '0':'{'
  '1':'"'
  '2':'f'
  '3:'o'
  '4':'o'
  '5':'"'
  '6':':'
  '7':'"'
  '8':'b'
  '9:'a'
  '10':'r'
  '11':'"'
  '12':'}'
}
```
I thought I was passing in the headers in the wrong format, and perhaps I still am (an opportunity for documentation if so), but every way I tried passing the headers had this same result.

## Steps to Reproduce

1. Place a breakpoint on the feed service's /feed/update code
2. `npx pilet publish <.tgz file> --url <feed service url> --headers "{\"foo\":\"bar\"}"` (repeat to try any other format for headers)
3. observe the custom headers

## Expected behavior

```
{
  "foo":"bar"
}
```

## Actual behavior

```
{
  '0':'{'
  '1':'"'
  '2':'f'
  '3:'o'
  '4':'o'
  '5':'"'
  '6':':'
  '7':'"'
  '8':'b'
  '9:'a'
  '10':'r'
  '11':'"'
  '12':'}'
}
```

## Possible Origin/Solution

I believe the issue stems from converting headers from type 'unknown' to type 'Record<string, string>' in commands.ts
https://github.com/smapiot/piral/blob/4748c3524b1da3cd677f2f8d299ce11ce7f1bd42/src/tooling/piral-cli/src/commands.ts#L685
https://github.com/smapiot/piral/blob/4748c3524b1da3cd677f2f8d299ce11ce7f1bd42/src/tooling/piral-cli/src/commands.ts#L707

Then this below causes the results in the faulty headers  
https://github.com/smapiot/piral/blob/4748c3524b1da3cd677f2f8d299ce11ce7f1bd42/src/tooling/piral-cli/src/common/http.ts#L218

Here is a script I used to replicate that same process of unknown -> Record<string,string> -> spread
```
import axios from 'axios';
import { Agent } from 'https';

async function process() {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer your_token_here',
  };

  var a: unknown = '{\"abc\":\"ced\"}'
  const test: Record<string, string> = a as Record<string, string>;

  console.log(a)
  console.log(test)

  const newHeaders: Record<string, string> = {
    ...test,
    ...headers,
  };

  console.log(newHeaders)

}

process();
```

**Comment by FlorianRappl** [comment]
> I believe the issue stems from converting headers from type 'unknown' to type 'Record<string, string>' in commands.ts

This is certainly not the root cause as TS has no effect on runtime code.

Your input seems incorrect; headers as a dictionary -- see yargs (options), e.g.,

```sh
npx pilet publish <.tgz file> --url <feed service url> --headers.foo bar
```

See documentation: https://docs.piral.io/tooling/publish-pilet#flags (type is `options` and not `string`!).

Hope that helps!

**Comment by akenned8** [comment]
Ah my apologies, thanks for the quick reply Florian! Huge fan of your product btw 😃

**Comment by FlorianRappl** [comment]
Great that it works - and thanks for the feedback!

For me this means that we need to strengthen the docs here (examples for each flag would help) and have better error handling in the CLI. Will pick that up as an improvement for 1.6.1.
