### ISSUE TITLE
Unable to Accept Invite Discord

### ISSUE THREAD

**Issue by gitisz** [smapiot/piral#707]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version
NA

## Description

Unable to requrest access to Discord server: whoops, Unable to accept Invite.

## Steps to Reproduce

1. Navigate to list https://discord.com/invite/kKJ2FZmK8t
2. Complete human verification
<img width="482" alt="image" src="https://github.com/user-attachments/assets/b9caa118-349f-4746-8858-cdf8b24ed4fb">

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin/Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
The invite link works - I've just checked. Can you give more details on how you use Discord? Are you using it via the web app or via some other mechanism? Since there is a human verification - are you logged in already?

We need more details here (in general this seems to be a problem with Discord, not with Piral - we just distribute the generated invite code).

**Comment by gitisz** [comment]
@FlorianRappl thank you forthe quick response. I am logged in to Discord with a verified user. I am using Discord from my personal laptop and with Chrome, however I get the same result from my phone. Checking a few things on my side, and some responses I found about this issue suggested there may be a server limit. This, plus the previous Gitter is archived, and there isn't another suppor channel, led me to post something here. If there is a better path to support please let me know.

**Comment by FlorianRappl** [comment]
I am not aware of any limits (the invite itself is limit-less and never expires).

Here is a new link - may be this one works for you (would be odd, but who knows): https://discord.gg/kKJ2FZmK8t

**Comment by gitisz** [comment]
It must be my account. I had a friend try and he accepted. We have a MWE trying to get some help on. I'll have him share. Thx!

**Comment by FlorianRappl** [comment]
Yeah let me know if anything comes out here. I don't know Discord well enough to have any clue what's going on there.
