### ISSUE TITLE
shell integrity check problem

### ISSUE THREAD

**Issue by norama** [smapiot/piral#708]
## Description

When developing a shell and a pilet, the install - build process generates an integrity number for the shell. 
Then when installing the shell in the pilet, this integrity number is compared with the one
stored in `package-lock.json`. When repeating the install and build process in another machine, this comparison fails. 

## Steps to Reproduce

1. Create shell.
2. Build the shell.
3. Create a pilet based on the shell.

Checkout the whole project to another machine.

1. Install and build the shell.
2. Install the pilet.

## Expected behavior

The build process runs without error.

## Actual behavior

There is an integrity check failure reported while installing the pilet.
The install process fails.

## Possible Origin/Solution

There are 2 possible solutions for this but neither of them seems to be ideal:
A) copy the required integrity number into the pilet's `package-lock.json` manually, overwriting the integrity number of the shell.
B) before the build process: increase the shell version in the shell's `package.json` as well as in the pilet's `package.json` where the
shell file is referenced. 

Although the B) solution seems to be acceptable, I do not think that this is the intended process, since increasing the shell's version
should mean a change in the pilet API or the shell's behavior, and it is not supposed to be done upon each installation.

What is the ideal process here?

**Comment by FlorianRappl** [comment]
> build process generates an integrity number for the shell.

What are you specifically talking about here?

> When repeating the install and build process in another machine, this comparison fails.

The whole thing sounds like something from your registry actually. The only time I've seen an npm integrity check failing is when transitioning from one registry to another. The integrity number is something that is not coming from the build process or so.

Please provide a clear reproducible for this one. We use Piral in a lot of projects and something similar to what you described has never occurred. Right now this looks to me rather a problem in your setup than an issue with Piral. I'd like to know more.

**Comment by norama** [comment]
Here is a repo with just the basic piral (shell) and pilet from your tutorial:
https://github.com/norama/piral-build

As long as I am on the same computer, everything is fine, even if I make a new clone in an empty directory, the build works.
However, when I clone the project in a different computer, the build fails. (Everything is Windows 11).
Possibly it is related to `vite` build (?) - this is the only thing I have chosen different from the default.
Also, the pilet loading in the shell is hard coded - without a feed service, but this has nothing to do with the build process.

This is how to reproduce:

1. Clone:
```
git clone https://github.com/norama/piral-build.git piral-build
```

2. Build the shell:
```
cd piral-build-example
npm i
npm run build
```
3. Build the pilet:
```
cd pilet-build-example
npm i
``` 

Result:
```
npm warn tarball tarball data for piral-build-example@file:C:\Users\nora.mate\work\tmp\piral-build\piral-build-example\dist\emulator\piral-build-example-1.0.0.tgz (sha512-JNEDIcwkPqP1JWBYTCokH7C+6fKqWxQwV/wGkdR6TetrbONLK0CyE682hDcm7TkUsspPTGckLYc5slZaj65VVA==) seems to be corrupted. Trying again.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn tarball tarball data for piral-build-example@file:C:\Users\nora.mate\work\tmp\piral-build\piral-build-example\dist\emulator\piral-build-example-1.0.0.tgz (sha512-JNEDIcwkPqP1JWBYTCokH7C+6fKqWxQwV/wGkdR6TetrbONLK0CyE682hDcm7TkUsspPTGckLYc5slZaj65VVA==) seems to be corrupted. Trying again.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\nora.mate\\work\\tmp\\piral-build\\pilet-build-example\\node_modules\\@types',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\nora.mate\work\tmp\piral-build\pilet-build-example\node_modules\@types'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\nora.mate\\work\\tmp\\piral-build\\pilet-build-example\\node_modules\\@types'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\nora.mate\\work\\tmp\\piral-build\\pilet-build-example\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\nora.mate\work\tmp\piral-build\pilet-build-example\node_modules\vite\dist\node'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\nora.mate\\work\\tmp\\piral-build\\pilet-build-example\\node_modules\\vite\\dist\\node'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code EINTEGRITY
npm error sha512-JNEDIcwkPqP1JWBYTCokH7C+6fKqWxQwV/wGkdR6TetrbONLK0CyE682hDcm7TkUsspPTGckLYc5slZaj65VVA== integrity checksum failed when using sha512: wanted sha512-JNEDIcwkPqP1JWBYTCokH7C+6fKqWxQwV/wGkdR6TetrbONLK0CyE682hDcm7TkUsspPTGckLYc5slZaj65VVA== but got sha512-vpNAD25wTMUNdtTlV/sphyJdbMbG7EPj5+Fh9qQhZEEvdvXODSgyLsAZFeKwX5ZKiZc4cVKZKHKC7/8Y0CGVrA==. (701809 bytes)
```

**Comment by norama** [comment]
Since it complains some failure of removing directories, I also tried in an admin PowerShell and this complaint is not there but the integrity check error remains.

Node and npm versions:
```
npm -v
10.8.1
node -v
v22.3.0
```

**Comment by FlorianRappl** [comment]
Well as stated the integrity check has nothing to do with the build. It's a validity check of the package-lock.

Could it be that you:

1. Build the shell / package it
2. Scaffold the pilet using the shell (everything works here)
3. Change the shell / package it
4. Reuse the same package-lock file to resolve it again (note that in (3) you did not change the version number)

So obviously that should fail. The integrity only remains the same if the package is identical. Different builds (i.e., different content) should be associated with different packages - so you'll need to change the version number, too.

**Comment by FlorianRappl** [comment]
Just tried following your steps. Everything works if you use it as you should do. Remember that a new release also should have a new version. You would not be able to just publish to a registry using the same version either.

Now regarding your initial question:

> What is the ideal process here?

Well as usual it depends. What do you want to achieve? You can just reference (link) the app shell if you work against it locally (that's, e.g., what you do in a monorepo). There is no emulator required.

Otherwise, what we usually do / recommend is to use the website emulator. It's not an npm package and can just be published like your standard artifacts. This way, every micro frontend always gets the up-to-date version and never needs to manually update an npm package.

https://docs.piral.io/concepts/T01-emulator#website-emulator

**Comment by norama** [comment]
@FlorianRappl Thanks for the quick answer. However, although I am trying to do my best to use the suggested website emulator, I could not fix the build process. I have a feeling that I am missing sg basic here.

This is what I did in [this commit](https://github.com/norama/piral-build/commit/061e956f69fe5865e449c37dcb84d2a593c5a756):

1. Set emulator to "website" in the piral's `piral.json`
2. Added a script `serve` in the piral's `package.json` to serve the contents of `dist/emulator` at localhost:8000
3. Added `debug` section with `defaultFeedUrl` in the `createInstance` config to provide pilets for the emulator,
   where `defaultFeedUrl` is set to http://localhost:1234/api/pilets and the corresponding pilet array JSON 
   is served through Piral's mock service.  

However, I have no idea how to refer the shell `piral-build-example` including the `PiletApi` from the `pilet-build-example` pilet.
As an attempt, I removed the emulator hard-coded .tgz file from `package.json` and tried to add `localhost:8000` as a reference
to the emulator in `pilet.json` but I get an error in `npm install`:
```
Downloading emulator from http://localhost:8000/ ...The "paths[2]" argument must be of type string. Received undefined
```

Could you help with this?
Do you have some example with this website emulator?
Is there a way to configure this by the  `pilet new` CLI command?
Unfortunately your example only shows the way to use the .tgz npm package.

Thanks for your help.

**Comment by FlorianRappl** [comment]
> Do you have some example with this website emulator?

https://github.com/piral-samples/dwx24

> Is there a way to configure this by the pilet new CLI command?

Yes - just enter as the `--source` the URL to the website emulator. (e.g., https://mycompany.com/myappshell/emulator.json)

> Unfortunately your example only shows the way to use the .tgz npm package.

There is no real difference. Instead of using the name of an npm package, or the local path to a tgz, you use the URL to the emulator (specifically, to the emulator.json).

Regarding your initial steps / comments:

1. Check, yes either use the CLI to tell `piral build` to specifically build a website emulator or change the general setting to build a website emulator instead of a package. That's good.
2. Well, here you can use whatever you want. Sure, you can run a local webserver such as `npx http-server dist/emulator` but you can / should also publish it to the internet / intranet (depending on your use case).
3. You don't need this. This setting is only relevant when you visit the website emulator in the browser (i.e., don't use it from your pilet).
4. Either scaffold your pilet with the source being referred to the URL leading to the emulator.json or add a new emulator via `pilet add-piral-instance http://.../emulator.json` (https://docs.piral.io/tooling/add-piral-instance-pilet).

Hope that helps!

**Comment by norama** [comment]
@FlorianRappl 
Thank you, yes, it helped and I managed to run the pilet as well as create another sample pilet in the same fashion.

I want the pilet feed because I want to see all pilets running even in dev mode. 

However, with this setting the app only runs from the emulator base URL http://localhost:8000, while the original http://localhost:1234 URL gives the following error:
```
Error: The fetched pilets metadata is not an array. at http://localhost:1234/index.b6b00c2e.js:25384:15
"The fetched pilets metadata is not an array."
```
I have no idea why. The emulator URL http://localhost:8000 works fine and shows both pilets.

The suggested CLI commands are not working for me as expected:

1. Adding the piral emulator to an existing pilet:

```
pilet add-piral-instance pilet-build-example http://localhost:8000/emulator.json
```
does not seem to do anything (but I could add 
```
"piralInstances": {
    "piral-build-example": {
      "selected": true,
      "url": "http://localhost:8000/emulator.json"
    }
 }
```
in `pilet.json` manually).

2. Creating a new pilet with the piral emulator:

```
pilet new --source http:8000/emulator.json --target pilet-build-sample
+ piral-cli v1.6.0
✖ [0002] Could not install the package "http:8000/emulator.json@latest" using npm. Make sure npm is correctly installed 
``` 

Here the versioning `@latest` is the problem,  http:8000/emulator.json  should have to be used.
So I copied the necessary configurations and references from the first pilet manually.

**Comment by FlorianRappl** [comment]
Your add-pilet-instance command is wrong. Just follow what I wrote (why do you specify something before the URL - there can be just a single source).

For the scaffold your URL is wrong. You need to give it a valid URL. If it does not work in the browser it won't work also when scaffolding ;).

**Comment by norama** [comment]
@FlorianRappl Yes, I was a bit off :-(, you are right. These 2 are working as expected, just have to respect the right URL and syntax.
However, the first problem with the Piral URL still exists: 
http://localhost:1234/
gives an error:
```
Error: The fetched pilets metadata is not an array. at http://localhost:1234/index.94ef83e3.js:25384:15
"The fetched pilets metadata is not an array."
```
But I can use the app through the emulator
http://localhost:8000/
without problem.

**Comment by FlorianRappl** [comment]
Are you still overriding the debug URL? Don't. 

Also if you want to debug multiple pilets then use the pilet debug command with both / multiple sources.

**Comment by norama** [comment]
@FlorianRappl Thanks, the problem was that my pilet URL returns the pilet array directly and not as 
```
items: [...]
```
Anyway, I removed the debug URL as well. App with all pilets now is working both at localhost:1234 (piral) and at localhost:8000 (emulator).

Thanks again for your help and quick reaction.
