### ISSUE TITLE
how to useGlobalState in pilet 

### ISSUE THREAD

**Issue by ayaoshu** [smapiot/piral#717]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ✅] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [✅ ] Are you running the latest version?
- [ ✅] Did you perform a search in the issues?

## Environment Details and Version

Package Version：^1.6.1, OS: mac, Browser: chrome

## Description

when i using  'useGlobalState' in pilet , be like this error: 
TypeError: Cannot destructure property 'state' of 'useGlobalStateContext(...)' as it is undefined.

## Expected behavior

Just like using ’useGlobalState‘ in piral

**Comment by ayaoshu** [comment]
The situation is as follows. I registered slot [slotA] in [piletA], and [slotA] behaved normally in [app shell]. Now I want to use it in [piletB], I am using <ExtensionSlot name="slotA />", because [ExtensionSlot] relies on [useGlobalState], the above error occurs.
I want to know, how can I use slotA in piletB correctly?

**Comment by FlorianRappl** [comment]
What you do is you import from piral / piral-core. These packages are not available in your pilet.

Please follow the documentation. It specifically tells you to use the Extension component living on the pilet API.

So it's not an import - you grab it from the inserted piral prop on your exposed components or by forwarding it (usually already wrapped to the specific slot name - but that's up to you).

**Comment by FlorianRappl** [comment]
We will not add it - you can already add this yourself (remember that you can share any package - so you can also share, e.g., `piral-core`).

Furthermore, you don't have to pass on `piral` / any prop. You can just wrap it in your `setup` function in a context - and then `useContext`.

There are plenty of options and Piral won't decide here what to do for you - this is your choice as this is an architectural decision.

**Comment by toninospiderman123** [comment]
Maybe you didn't get what i wrote.

This is my pilet (example from Piral documentation)

```
export function setup(app: PiletApi) {
  app.registerPage('/my-page', Page);
}
```

if my **Page** is a complex React component builded with other nested react component don't you think that could be boring passing the **app** property between all these components? Or maybe do you write only one big component (this is an anti-pattern) and so for you is not a problem? Don't you think that could be boring each time install piral-hooks-utils and wrap all the registered pages with the provider inside this library?

As i saw Piral is basically for a React developer, so what i'm asking is not something only for me like you wrote (_There are plenty of options and Piral won't decide here what to do for you - this is your choice as this is an architectural decision._) but,  from my point of view (and also from the point of view of who opened this issue i think), this cover a need of a React developer.

**Comment by toninospiderman123** [comment]
I'm sorry Florian if I seemed aggressive, it wasn't my intention.

We have two different approaches and I accept that.

I'm sure I'll find  an alternative way to get to the result, in any case thanks for your availability.

**Comment by FlorianRappl** [comment]
Yes, no problem ❤️ - for such discussions I usually prefer chat or call; it's easier to show things / avoid misunderstandings (this mostly refers to my own messages).

As mentioned the idea is / was to provide that - just you need to opt-in. You can now decide if that opt-in is something that every team / pilet needs to do (e.g., by installing the package / wrapping the component in a HOC) or if that's provided by your Piral instance (e.g., by sharing the package).

In any case let me know if there are problems with the way you've selected. Happy to have you covered!
