### ISSUE TITLE
Uncaught ReferenceError: MutationEvent is not defined

### ISSUE THREAD

**Issue by dheid** [smapiot/piral#724]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

* Chrome version: 130.0.6723.92 (Official Build) (64-bit)
* Operating System: Windows 10

## Description

I'm experiencing an error when using the Piral Blazor converter with my application. The JavaScript console of my Chrome browser (version 130.0.6723.92) shows a repeated exception:

```
Uncaught ReferenceError: MutationEvent is not defined
    at n.Vht (events.js:61:28)
    at s.invokeTask (zone.js:402:33)
    at i.runTask (zone.js:159:47)
    at c.invokeTask [as invoke] (zone.js:483:34)
    at y (zone.js:1138:18)
    at w (zone.js:1169:29)
    at n.x (zone.js:1202:16)
```

This error occurs over 763 times and even more frequently when I move the mouse around.

## Steps to Reproduce

1. Run your application using the Piral Blazor converter.
2. Open the JavaScript console in Chrome (version 130.0.6723.92).
3. Observe the repeated exception messages with `Uncaught ReferenceError: MutationEvent is not defined`.

## Expected behavior

I expect to see no errors or exceptions when running my application using the Piral Blazor converter.

## Actual behavior

There is a huge amount of errors slowing my application down.

## Possible Origin/Solution

Remove the check as the `MutationEvent` is no longer supported by modern browsers.

**Comment by dheid** [comment]
@FlorianRappl Could you look into this, please?

**Comment by FlorianRappl** [comment]
Hi @dheid thanks for the report. Indeed the whole story around mutation events changed drastically this year (the mutation observer is out for a while - but now Chrome is aggressively pushing away the classic methods / events).

Thanks for the PR #725 - I think this is a suitable solution as our only aim is to properly forward the events (for this we use the list as found in the Blazor JS source code).
