### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#90]
## Description

The Piral CLI is already quite nice to operate within the command line, however, a UI integrated in an IDE (such as Visual Studio Code) could be a nice addition. It could simplify common tasks, too - such as running the debug (no need to fiddle with the .vscode / workspace settings).

## Background

Having a plugin that deals with the whole Piral spectrum (e.g., if detecting that the project is an app shell it provides actions relating to "piral" commands under hood, likewise for "pilet" commands). This way debugging, building, validating, and publishing can all be done from the IDE without touching the command line.

## Discussion

Should we use a separate repo for this? I think yes.

**Comment by FlorianRappl** [comment]
We now have an initial version available at [piral-inspector](https://github.com/smapiot/piral-inspector).

Issues, ideas, and all development will be done in the dedicated repository!

Thanks @manuelroemer for setting it all up!

**Comment by carvinlo** [comment]
It would be better if the vscode plugin could include your practical simulated [feed service](https://github.com/smapiot/sample-pilet-service) ! :smiley_cat:

**Comment by FlorianRappl** [comment]
The VS Code plugin just controls the CLI and [we have a CLI plugin for starting the feed](https://www.npmjs.com/package/piral-cli-local-feed).

**Comment by carvinlo** [comment]
I just need it, thanks

**Comment by FlorianRappl** [comment]
Initial version without much functionality is out. Expect more releases and improvements soon!

All issues, enhancements, etc. are handled [in the dedicated repository](https://github.com/smapiot/vscode-piral).
