### ISSUE TITLE
DevTools Extension / Inspector

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#95]
## Description

For debugging a Piral instance or a Pilet it could help to get enhanced support in form of a Browser Extension (e.g., distributed via the Chrome, Firefox, or other stores).

To start with, this extension should allow:

- Removal of pilets
- Addition of pilets
- Refresh of pilets
- Inspection / modification of the current state (maybe)

## Background

While thinking about how to improve dev experience even more we thought about introducing a special developer mode that is only visible via some icon. However, if this icon is not wanted it could be quite a blocker.

Instead, going for a browser extension is always opt-in and could provide even more features (which are then also decoupled from the actually installed Piral version).

## Discussion

What features make sense here? How should the UI look like? We potentially aim for something super simple, that just looks "native" or embedded in most browsers.

We will most likely put this in a separate repo.

**Comment by kpyfan** [comment]
I think something that would be helpful here too is exposing more info on errors too. Right now I'm running into an issue where I'm mocking a feed service (to load in a certain pilet locally) and Piral is giving me `error: Loading`, but there's no info available in the console or anything that would point me to what the issue with the mock feed service is.

**Comment by FlorianRappl** [comment]
Depending on the issue that could be difficult.

If we see, e.g., error 400 coming from the feed service request then sure. If something in your code crashes here - sure again. But we will not be able to go beyond the browser, e.g., to see why your feed service instance crashes or responds with an invalid answer.

There should, however, already be a message in the console / and the network tab should be helpful.

I guess it could just be that the address to the mock service is not set up correctly. How have you integrated the mock service?

**Comment by kpyfan** [comment]
Sorry if I wasn't super clear here - the mock is done in the same way as the "samples" directory by using a file in the `mocks` directory. I've validated that manually navigating to the endpoint for the mock feed does return what looks like properly formatted JSON. However, when navigating to the root page, the console itself was not giving any particularly useful information and the page just gave me the "Error: Loading" message. I'll definitely keep digging from my end as it seems this issue has arisen as I've tried to add another app in via pilet, so it may be an issue on how I have that set up as well.

**Comment by FlorianRappl** [comment]
Sure, so with the integration of the mock service I refer to

```
const instance = createInstance({
  requestPilets() {
    return fetch('...');// what's here?
  }
});
```

So if the mock service is correctly up then fetch should point to its address incl. port. Assuming you got this right, are you also obtaining the pilets array?

```
fetch('...').then(res => res.json()).then(body => body.items)
```

The last part with the `body.items` is crucial. Let me know if this helps!

**Comment by kpyfan** [comment]
Apologies for the late response - been away for the holiday weekend.

So I've tested a couple of different things and my code is a little different now (still not quite working), but `requestPilets()` is calling the URL `/service/v1/pilets`.

On that URL, I'm returning the following JSON:
```
{
  "items": [
    {
      "name": "settings",
      "version": "1.0.0",
      "description": "Fake settings sample page",
      "author": {
        "name": "PSS",
        "email": ""
      },
      "link": "/pilets/settings/index.js",
      "hash": ""
    }
  ]
}
```

and then calling `.then(res => res.json()).then(body => body.items)` on the result.

I've manually gone to my `/service/v1/pilets` endpoint and validated that I'm getting back the correct information from it. I've also validated that the `link` field in the JSON also does return a valid javascript file that is the pilet index.js

**Comment by kpyfan** [comment]
On a slightly less related note - we're also seeing a ton of console errors about failed websocket connections (part of what I'm doing is trying to get the piral instance stood up hosted as static assets on a different web server). Is this something that is expected/potentially the cause of the loading errors we're getting?

**Comment by FlorianRappl** [comment]
Regarding the WS errors: I guess you don't deactivate the GraphQL subscription. In the 0.9 version we'll actually make piral-urql an opt-in plugin, but before that just use something like

```js
import { renderInstance, setupGqlClient } from 'piral';

renderInstance({
    settings: {
      gql: setupGqlClient({
        subscriptionUrl: false,
      }),
    },
    requestPilets,
});
```

This should be completely unrelated to any loading errors.

Regarding the feed: Please provide absolute URLs otherwise finding your pilets can be difficult (i.e., with the given information the "settings" pilet should be located on the same server that your Piral instance is hosted). Are these "proper" pilets (i.e., scaffolded and published via the CLI)?

**Comment by kpyfan** [comment]
Gotcha, I'll use that to get rid of the gql websocket errors.

For the other issue - I managed to figure out what was going on by `console.log`ing all of the output in fetch('...').then(res => res.json()).then(body => body.items). To fix gql being unable to query my backing pilet feed, I actually had swapped over to using `axios.get()` to fetch the list of pilets and the format returned there is different. Nested inside of the promise was a react error for `.json()` not being a defined function of the type returned.

Maybe something could be improved here on the console logging error output on rejected promises?

**Comment by FlorianRappl** [comment]
> Maybe something could be improved here on the console logging error output on rejected promises?

True. We'll fix / improve this in the 0.9.0!

**Comment by FlorianRappl** [comment]
@manuelroemer the repo has been created at: https://github.com/smapiot/piral-inspector

We can talk about details next week!

**Comment by manuelroemer** [comment]
👍 Sounds great!

**Comment by FlorianRappl** [comment]
We now have an initial version available at [piral-inspector](https://github.com/smapiot/piral-inspector).

Issues, ideas, and all development will be done in the dedicated repository!

Thanks @manuelroemer for setting it all up!
